### ISSUE TITLE
无法访问https://www.cnblogs.com/bndong/，卡在加载动画

### ISSUE THREAD

**Issue by 1024th** [BNDong/Cnblogs-Theme-SimpleMemory#10]
![default](https://user-images.githubusercontent.com/47070449/53015469-2c990a80-3486-11e9-82c6-de1377a6c2ec.gif)
已经等了一段时间了。。

**Comment by BNDong** [comment]
尝试重新访问，第一次加载可能稍微慢点，但不会一直卡住！
