### ISSUE TITLE
代码片段能否完全展开？

### ISSUE THREAD

**Issue by sshsu** [BNDong/Cnblogs-Theme-SimpleMemory#101]
请问代码片段能否完全展开，有配置的方法吗？ 
代码片段的滑轮进度条并不好用，而且大多数时候完全展开更适合阅读，谢谢！

**Comment by fatmanhappycode** [comment]
赞同

**Comment by BNDong** [comment]
有时我会在文章中贴很长的代码示例，所以给代码框做了高度限制！关于这个问题我考虑了一下，在 `v1.2.5` 中增加了配置 `codeMaxHeight ` 用以设置是否对代码框进行高度限制！

## codeMaxHeight

限制代码框的最大高度；如开启，代码框高度不会超过页面可视区域的70%，隐藏部分通过滚动的方式查看。

```javascript
window.cnblogsConfig = {
    codeMaxHeight: true,
}
```
