### ISSUE TITLE
自定义部分能否再增加一点

### ISSUE THREAD

**Issue by LonelySinging** [BNDong/Cnblogs-Theme-SimpleMemory#102]
比如首页的那个背景图
以及标语 (⊙﹏⊙) 我找了很久没找到标语在哪里换成自己的

谢谢

**Comment by BNDong** [comment]
1) [主页背景图配置](https://www.dbnuo.com/Cnblogs-Theme-SimpleMemory/docs/v1.1/#/Docs/Customization/config?id=hometopimg-%e4%b8%bb%e9%a1%b5banner%e5%9b%be%e7%89%87)
2) [主页标语配置](https://www.dbnuo.com/Cnblogs-Theme-SimpleMemory/docs/v1.1/#/Docs/Customization/config?id=homebannertext-%e4%b8%bb%e9%a1%b5banner%e4%b8%8a%e7%9a%84%e6%a0%87%e8%af%ad)

**Comment by LonelySinging** [comment]
谢谢
