### ISSUE TITLE
样式建议

### ISSUE THREAD

**Issue by taoyeh** [BNDong/Cnblogs-Theme-SimpleMemory#103]
![image](https://user-images.githubusercontent.com/50255085/76047675-71fb7d80-5f9e-11ea-9ce1-2a13d8e1c683.png)
阅读有些时候感觉眼睛疼，还是希望能弄个白框出来，给人的感觉会好一点
比如这样子的
![image](https://user-images.githubusercontent.com/50255085/76047720-a0795880-5f9e-11ea-83b8-649bbfc682d7.png)
看起来就舒服很多

**Comment by BNDong** [comment]
试着给主体内容增加了阴影效果，效果还可以😄`v1.2.5`  更新进去了！
