### ISSUE TITLE
关于首页图片

### ISSUE THREAD

**Issue by jkfx** [BNDong/Cnblogs-Theme-SimpleMemory#105]
我按照教程配置了CSS和JS（有权限），为啥首页图片一片漆黑，默认需要自己弄图片吗？如果是的话能分享下博主的首页的图片的地址吗？

**Comment by U-s-e-r-Unknown** [comment]
> 我按照教程配置了CSS和JS（有权限），为啥首页图片一片漆黑，默认需要自己弄图片吗？如果是的话能分享下博主的首页的图片的地址吗？

F12可以看到图片链接，就是.webp格式，[Link](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/Docs/Customization/config?id=%e4%b8%bb%e9%a1%b5%e9%85%8d%e7%bd%ae)
