### ISSUE TITLE
博客变成空白，js 被拒绝执行。

### ISSUE THREAD

**Issue by EslSuwen** [BNDong/Cnblogs-Theme-SimpleMemory#107]
v1.2.3
chrome
控制台报错如下
Refused to execute script from 'https://gitee.com/dbnuo/Cnblogs-Theme-SimpleMemory/raw/master/version.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

**Comment by leolulu** [comment]
![image](https://user-images.githubusercontent.com/35873316/76278636-0596bc00-62c7-11ea-8bca-875ef7b3999a.png)
存这个js的仓库被爆了

**Comment by Wfzsec** [comment]
+1

**Comment by BNDong** [comment]
更新版本至 ```v1.2.6```，已替换所有关于 Gitee 的链接！

**Comment by leolulu** [comment]
> 更新版本至 `v1.2.6`，已替换所有关于 Gitee 的链接！

感谢，已正常载入

**Comment by Cpaulyz** [comment]
> 
> 
> 更新版本至 `v1.2.6`，已替换所有关于 Gitee 的链接！

已经更新1.2.6 ，空白问题解决了
但是首页的blogUser的字体样式似乎失效了？之前是一个挺好看的字体，现在变成默认字体了。

**Comment by U-s-e-r-Unknown** [comment]
> > 更新版本至 `v1.2.6`，已替换所有关于 Gitee 的链接！
> 
> 已经更新1.2.6 ，空白问题解决了
> 但是首页的blogUser的字体样式似乎失效了？之前是一个挺好看的字体，现在变成默认字体了。

没有，CSS更换了，我也遇到了，把CSS改为最新版就好了，路径相同

**Comment by Cpaulyz** [comment]
> 
> 
> > > 更新版本至 `v1.2.6`，已替换所有关于 Gitee 的链接！
> > 
> > 
> > 已经更新1.2.6 ，空白问题解决了
> > 但是首页的blogUser的字体样式似乎失效了？之前是一个挺好看的字体，现在变成默认字体了。
> 
> 没有，CSS更换了，我也遇到了，把CSS改为最新版就好了，路径相同

感谢，改完就解决了！

**Comment by SCCQ** [comment]
emmm我的手机端访问时空白，电脑访问没问题，请问是咋回事呢
