### ISSUE TITLE
1366宽的屏幕要缩小页面才会显示目录

### ISSUE THREAD

**Issue by Foxer-Z** [BNDong/Cnblogs-Theme-SimpleMemory#108]
我的屏幕宽度1366，文章目录显示不出来，把页面缩小到90%后才会显示。在控制台看了一下，id="bgCanvas"的canvas 宽度>=1373时会显示目录。我想在css里改，但是控制目录的脚本好像在js里，您方不方便改一下显示目录的屏幕宽度值？

**Comment by BNDong** [comment]
当前可视区域宽度 <= 1360px 就会隐藏文章目录，因为会遮挡文章内容！

等下个版本吧！我给他单独拉出来个配置。

**Comment by Lotus-Blue** [comment]
> 当前可视区域宽度 <= 1360px 就会隐藏文章目录，因为会遮挡文章内容！
> 
> 等下个版本吧！我给他单独拉出来个配置。

建议目录可以做成一个按钮，跟菜单按钮menu一样，点击才会展开

**Comment by Lotus-Blue** [comment]
> 我的屏幕宽度1366，文章目录显示不出来，把页面缩小到90%后才会显示。在控制台看了一下，id="bgCanvas"的canvas 宽度>=1373时会显示目录。我想在css里改，但是控制目录的脚本好像在js里，您方不方便改一下显示目录的屏幕宽度值？

v1.2.7已经解决问题了
