### ISSUE TITLE
今天早上博客页面空白

### ISSUE THREAD

**Issue by U-s-e-r-Unknown** [BNDong/Cnblogs-Theme-SimpleMemory#109]
除了点击特效其他无法显示。
开了Safari的阅读显示器视图后可正常显示文字。
是不是Loader出问题了，或背景到了最上层？
我是用的是1.2.4,您的博客也是如此

**Comment by U-s-e-r-Unknown** [comment]
目前好像只有1.1.9及之前版本显示正常

**Comment by tsvico** [comment]
最新版修复了

**Comment by U-s-e-r-Unknown** [comment]
> 最新版修复了
看到了，谢谢
