### ISSUE TITLE
关于字体

### ISSUE THREAD

**Issue by U-s-e-r-Unknown** [BNDong/Cnblogs-Theme-SimpleMemory#110]
请问您里的字体是如何配置的，以及 GhVersions是否要填写1.2.6

**Comment by U-s-e-r-Unknown** [comment]
已解决，忘记换CSS了

**Comment by BNDong** [comment]
## 如何扩展字体
字体使用的是阿里云字体库，可以使用配置 ```fontIconExtend``` 来扩展字体，详情参考[文档](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/Docs/Customization/fonticon)！
## 如何切换版本
请参考关于版本切换的[文档](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/Docs/GettingStarted/versionSwitch)。

**Comment by U-s-e-r-Unknown** [comment]
> ## 如何扩展字体
> 字体使用的是阿里云字体库，可以使用配置 `fontIconExtend` 来扩展字体，详情参考[文档](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/Docs/Customization/fonticon)！
> 
> ## 如何切换版本
> 请参考关于版本切换的[文档](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/Docs/GettingStarted/versionSwitch)。

谢谢您
