### ISSUE TITLE
建议添加公众号放置功能

### ISSUE THREAD

**Issue by weechang** [BNDong/Cnblogs-Theme-SimpleMemory#112]
RT

**Comment by UnknownRanger** [comment]
> RT

抱歉点到了表情

公众号放置好像可以用链接放到侧边栏吧

比如这个：https://zhidao.baidu.com/question/2144009873273868148.html

**Comment by BNDong** [comment]
目前没有专放公众号的位置，我不确定它放在页面的什么位置比较合适。
不过，你可以试着将公众号配置到：`window.cnblogsConfig.essaySuffix. codeImgUrl `
