### ISSUE TITLE
建议目录可以做成一个按钮，跟菜单按钮menu一样，点击才会展开

### ISSUE THREAD

**Issue by Lotus-Blue** [BNDong/Cnblogs-Theme-SimpleMemory#113]
文章可以显示大纲很有必要，用户可以点击那个按钮显示大纲，需要时才显示，希望作者可以增加这个功能

**Comment by Lotus-Blue** [comment]
效果图可以看https://snowdreams1006.github.io/这个，点击就显示文章大纲

**Comment by UnknownRanger** [comment]
> 文章可以显示大纲很有必要，用户可以点击那个按钮显示大纲，需要时才显示，希望作者可以增加这个功能

使用一级标题分段自动生成目录，类似大纲

**Comment by Lotus-Blue** [comment]
> > 文章可以显示大纲很有必要，用户可以点击那个按钮显示大纲，需要时才显示，希望作者可以增加这个功能
> 
> 使用一级标题分段自动生成目录，类似大纲

你说的那个是只能在文章内容中显示吗？我找到一个自动生成大纲的仓库，https://github.com/chris-peng/markdown_nav 但是不知道怎么加进去的

**Comment by Lotus-Blue** [comment]
说真的，看了几个博客样式，还是这个作者的好看，点赞!

**Comment by Lotus-Blue** [comment]
哦，看到了！原来分辨率问题不显示

**Comment by Lotus-Blue** [comment]
作者在v1.2.7版本中已解决，自行关闭
