### ISSUE TITLE
建议添加"编辑文章"功能

### ISSUE THREAD

**Issue by hs-black** [BNDong/Cnblogs-Theme-SimpleMemory#114]
rt, 较旧版本在文末有"编辑文章"选项, 可以直接跳到管理, 但新版本隐去了, 感觉不太方便, 可以考虑加上"编辑文章"功能, 谢谢😀

**Comment by Lotus-Blue** [comment]
对，感觉这功能挺必要的

**Comment by sshsu** [comment]
是的编辑文章怎么没了，比较麻烦现在

**Comment by sky5454** [comment]
现在要编辑以前的文章，找是找不到的，建议用这个链接： https://i-beta.cnblogs.com/posts/edit;postId=《ID》

如文章 `https://www.cnblogs.com/yucloud/p/6118966.html`

其`ID`为 6118966

所以对应的编辑链接为： `https://i-beta.cnblogs.com/posts/edit;postId=6118977`

**Comment by BNDong** [comment]
等下一版本放开文章页中的 post meta，主页依然不会显示。如需编辑可以去文章页中点击编辑。

**Comment by hs-black** [comment]
> 等下一版本放开文章页中的 post meta，主页依然不会显示。如需编辑可以去文章页中点击编辑。

蟹蟹巨佬, 很喜欢您的主题😃

**Comment by sshsu** [comment]
编辑功能再1.3.0已有，感谢作者大大
