### ISSUE TITLE
dalao，博客今天又打不开了~版本是1.2.7

### ISSUE THREAD

**Issue by DetachmLiu** [BNDong/Cnblogs-Theme-SimpleMemory#115]
进去一片空白，1.2.5一周前也出现过，升为1.2.6好了，今天又挂了TAT

**Comment by Lotus-Blue** [comment]
一切正常阿，昨天已更新到v1.2.7

**Comment by DetachmLiu** [comment]
> 一切正常阿，昨天已更新到v1.2.7

0.0 测试了下，好像是浏览器的锅（无论是我自己的还是您的），换个浏览器成功打开了😅，打不开的浏览器是360极速，内核Chrome78。

**Comment by Lotus-Blue** [comment]
> > 一切正常阿，昨天已更新到v1.2.7
> 
> 0.0 测试了下，好像是浏览器的锅（无论是我自己的还是您的），换个浏览器成功打开了😅，打不开的浏览器是360极速，内核Chrome78。

谷歌浏览器这么好用，没必要用360浏览器吧

**Comment by DetachmLiu** [comment]
> > > 一切正常阿，昨天已更新到v1.2.7
> > 
> > 
> > 0.0 测试了下，好像是浏览器的锅（无论是我自己的还是您的），换个浏览器成功打开了😅，打不开的浏览器是360极速，内核Chrome78。
> 
> 谷歌浏览器这么好用，没必要用360浏览器吧

😂主要是馋同步，每种浏览器都下了~多谢了
