### ISSUE TITLE
怎么设置首页，每一篇文章的摘要呢？

### ISSUE THREAD

**Issue by qld-cf** [BNDong/Cnblogs-Theme-SimpleMemory#116]

**Comment by qld-cf** [comment]
每篇文章的介绍，他的摘要都是默认取前N个字符，想要指定的内容
@BNDong

**Comment by qld-cf** [comment]
想要指定的内容放到摘要里，而不是自动取前N个
谢谢

**Comment by BNDong** [comment]
博客园支持每篇文章自定义设置摘要！
<img width="652" alt="Snipaste_2020-03-19_10-31-45" src="https://user-images.githubusercontent.com/21150911/77025741-de2da680-69cc-11ea-911a-64e0d9536942.png">

**Comment by qld-cf** [comment]
thank you
