### ISSUE TITLE
cnzz

### ISSUE THREAD

**Issue by vito19960522** [BNDong/Cnblogs-Theme-SimpleMemory#117]

**Comment by vito19960522** [comment]
cnzz统计数据返回正常，但是<div id="cnzzInfo"></div>中没有内容，
数据在
<div id="page_end_html">
        <div id="cnzzProtocol" style="display:none">

**Comment by BNDong** [comment]
本人使用无问题，请提供配置示例，以便复现该问题！

**Comment by vito19960522** [comment]
我使用的是12.6版本

**_侧边栏_**

<script type="text/javascript">
    window.cnblogsConfig = {
        GhVersions    : 'v1.2.5', // 版本
        blogUser      : "vito", // 用户名
        blogAvatar    : "https://images.cnblogs.com/cnblogs_com/vito_wang/1661262/o_200305074205640.jpeg", // 用户头像
        blogStartDate : "2016-10-06", // 入园时间，年-月-日。入园时间查看方法：鼠标停留园龄时间上，会显示入园时间
        //主页悬浮图像
        homeTopImg:[
              "https://images.cnblogs.com/cnblogs_com/vito_wang/1661262/o_20031512440681584240852_.pic_hd.jpg",
              "https://images.cnblogs.com/cnblogs_com/vito_wang/1661262/o_2003151250472.jpg",
              "https://images.cnblogs.com/cnblogs_com/vito_wang/1661262/o_2003151251323.jpg",
              "https://images.cnblogs.com/cnblogs_com/vito_wang/1661262/o_200315125157WechatIMG4.jpeg",
        ],
        essayTopImg: [
              "https://images.cnblogs.com/cnblogs_com/vito_wang/1661262/o_20031512440681584240852_.pic_hd.jpg",
              "https://images.cnblogs.com/cnblogs_com/vito_wang/1661262/o_2003151250472.jpg",
              "https://images.cnblogs.com/cnblogs_com/vito_wang/1661262/o_2003151251323.jpg",
              "https://images.cnblogs.com/cnblogs_com/vito_wang/1661262/o_200315125157WechatIMG4.jpeg",
        ],
        homeBannerText: "",
        homeBannerTextType: "one",
        webpageTitleOnblur: '(oﾟvﾟ)ノ Hi', //网页失去焦点文字
        webpageTitleOnblurTimeOut: 500,
        webpageTitleFocus: '(*´∇｀*) 欢迎回来！',
        webpageTitleFocusTimeOut: 1000,
        webpageIcon: "https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@master/img/webp/blog_logo.webp", //网站图标
        homeTopAnimationRendered: true,
        homeTopAnimation: {
             color   : 'random',
        },
        essayCodeHighlightingType: "highlightjs",
        essayCodeHighlighting: "solarized-light",
        footerStyle: 1,
        bottomText: {
            left : "沉舟侧畔千帆过",
            right: "病树前头万木春",
        },
    }
</script>
<script src="https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v1.2.7/src/script/simpleMemory.min.js"></script>

_**页脚**_
<div id="cnzzInfo" style="display:none">
    <script type="text/javascript">document.write(unescape("%3Cspan id='cnzz_stat_icon_1278701969'%3E%3C/span%3E%3Cscript src='https://s4.cnzz.com/z_stat.php%3Fid%3D1278701969%26online%3D1%26show%3Dline' type='text/javascript'%3E%3C/script%3E"));</script>
</div>
