### ISSUE TITLE
文章目录的跳转问题

### ISSUE THREAD

**Issue by gu-chen** [BNDong/Cnblogs-Theme-SimpleMemory#119]
点击文章目录，会跳转到下一个网页。希望通过js来控制

**Comment by BNDong** [comment]
目前文章目录点击不会出现跳转走的情况！请提供地址，以便确认该问题！

**Comment by gu-chen** [comment]
> 目前文章目录点击不会出现跳转走的情况！请提供地址，以便确认该问题！

很抱歉，我之前表达得可能不太清楚。
页面虽然不会跳转走，但是点击目录之后，网址会改变成`https://xxx.xx#标题锚点`，一直点，就一直变，但是浏览器返回上一级的时候，就会跳转到上一个点击过的锚点。
举个例子：我从分类列表中跳转到A文章详情，点击其目录中的title1（网页虽然不会刷新，但网址变成了`https://xxx.xx#title1`），再点击目录中的title2（网页虽然也不会刷新，但是网址`https://xxx.xx#title2`），接着再点击目录中的title3（网页虽然也不会刷新，但是网址`https://xxx.xx#title3`）。此时，我想返回文章列表，但是点击返回的时候，会先返回`https://xxx.xx#title2`、接着返回`https://xxx.xx#title1`，最后再回到文章列表。也就是说，如果我点了5次文章目录，我就需要返回5次。

**Comment by BNDong** [comment]
我明白你说的问题了，这确实是个问题！下个版本会针对对该问题进行处理。
