### ISSUE TITLE
侧边栏icon-list在手机上会显示错位

### ISSUE THREAD

**Issue by yinghualuowu** [BNDong/Cnblogs-Theme-SimpleMemory#12]
但我也不知道是不是只有我手机才有
![image](https://user-images.githubusercontent.com/22371568/55678029-579bc880-5925-11e9-9f98-1a371bd292d0.png)

**Comment by BNDong** [comment]
这个位置确实有兼容性问题，目前在IE和移动端下会出现样式的错误，这个以后我想办法调优！
