### ISSUE TITLE
关于主页文章显示的一些疑问

### ISSUE THREAD

**Issue by mjx-dev** [BNDong/Cnblogs-Theme-SimpleMemory#120]
为什么最新的一篇文章不会折叠？是要配置什么吗？求大佬解答

**Comment by BNDong** [comment]
主题没有针对此进行处理，请检查是否勾选了“置顶随笔显示全文”。
<img width="760" alt="Snipaste_2020-03-23_17-33-19" src="https://user-images.githubusercontent.com/21150911/77302524-6e048500-6d2c-11ea-8516-44e472bdb026.png">

**Comment by mjx-dev** [comment]
谢谢
