### ISSUE TITLE
夜间模式

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#121]
建议将夜间模式的状态存入Cookies

**Comment by sky5454** [comment]
另外：https://www.cnblogs.com/yucloud/p/12548065.html
开启页面模式后，代码框区为白色

**Comment by BNDong** [comment]
## 建议将夜间模式的状态存入Cookies
感谢！Cookies 这个可以加进去，并在测试仓库实现了该功能，每次切换会保存模式状态4个小时！后续会更新进去。

## 开启夜间模式后，代码框区为白色
**代码框目前只能保持原有的高亮样式。** 代码框是文章页处理起来最麻烦、耗时的，原本博客园不同编辑器生成的 html 结构就不同，我还要兼容不同的渲染插件。倒是可以在使用夜间模式时强制更改代码框的渲染主题，但是我无法保证用户在切换回日间模式时，代码框能恢复到原有的高亮样式；特别是博客园原本的代码样式，我无办法改回来！如果生成新的代码框太复杂且影响性能。代码框目前只能保持原有的高亮样式，后续如无可行方案不会改！

**Comment by sky5454** [comment]
可以在代码上加蒙版吗

**Comment by sky5454** [comment]
> 
> 
> 可以在代码上加蒙版吗

用 [filter](https://developer.mozilla.org/zh-CN/docs/Web/CSS/filter) 应该就可以实现

**Comment by BNDong** [comment]
本打算在夜间模式时候增加代码框的透明度，使代码框整体看起来更暗一些，以使白色背景看起来不那么刺眼。现在看来，使用 `filter` 可以做到相同的效果。以前不太熟悉使用 `filter` ，现在详细看了一下。感谢分享！

**Comment by sky5454** [comment]
bug：夜间模式下，代码框没有渲染
标签 : `<div class="cnblogs_Highlighter">`
地址：https://www.cnblogs.com/yucloud/p/12548065.html
代码框：
![image](https://user-images.githubusercontent.com/12370628/80438543-03e88c80-8937-11ea-90c8-23b335fc25a4.png)
