### ISSUE TITLE
CPU资源消耗

### ISSUE THREAD

**Issue by cnsimo** [BNDong/Cnblogs-Theme-SimpleMemory#122]
打开页面之后，cpu好高呀，有没有关闭特效的地方啊

**Comment by cnsimo** [comment]
![image](https://user-images.githubusercontent.com/22788893/77619831-017bc700-6f74-11ea-8e8c-546bbf649b0d.png)

**Comment by BNDong** [comment]
```javascript
window.cnblogsConfig = {
    ... // 其它配置

    homeTopAnimationRendered: false,
    essayTopAnimationRendered: false,
    bgAnimationRendered: false
}
```

**Comment by mumuyinxin** [comment]
对了，博主我想问下为啥码云屏蔽了你的仓库

**Comment by BNDong** [comment]
> 对了，博主我想问下为啥码云屏蔽了你的仓库

一些图片资源使用码云作为了图床，外链流量太大，以至于被屏蔽了！

**Comment by mumuyinxin** [comment]
我看了下，发现是播放器样式和你的冲突了------------------ 原始邮件 ------------------
发件人: "BNDong"<notifications@github.com>
发送时间: 2020年4月15日(星期三) 晚上10:58
收件人: "BNDong/Cnblogs-Theme-SimpleMemory"<Cnblogs-Theme-SimpleMemory@noreply.github.com>;
抄送: "mumuyinxin"<895250178@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [BNDong/Cnblogs-Theme-SimpleMemory] CPU资源消耗 (#122)




  
对了，博主我想问下为啥码云屏蔽了你的仓库
  
一些图片资源使用码云作为了图床，外链流量太大，以至于被屏蔽了！
 
&mdash;
