### ISSUE TITLE
首页古诗能添加自定义随机吗？

### ISSUE THREAD

**Issue by wuxiansen** [BNDong/Cnblogs-Theme-SimpleMemory#124]

**Comment by wuxiansen** [comment]
这个样式应该是全网第一了。 厉害👍

**Comment by BNDong** [comment]
目前可以自定义一句话，但是不能自定义随机！
[参考文档](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/Docs/Customization/config?id=homebannertext-%e4%b8%bb%e9%a1%b5banner%e4%b8%8a%e7%9a%84%e6%a0%87%e8%af%ad)

> 我图片是托管到自己的服务器的，安利一个图片网站：https://wallhaven.cc/
