### ISSUE TITLE
为什么作者的背景是动态的，还可以那么好看

### ISSUE THREAD

**Issue by hulichao** [BNDong/Cnblogs-Theme-SimpleMemory#125]
https://www.cnblogs.com/bndong/
为啥我的是静态的cnblogs.com/hulichao

**Comment by BNDong** [comment]
![20160720190333_vuMZm thumb 1000_0](https://user-images.githubusercontent.com/21150911/77913399-c86e8a00-72c6-11ea-974b-9ecb5e00ee73.png)

**Comment by cressme** [comment]
不懂就问，小白一个，请问动态背景是在哪里改，我们的主页都是固定背景的

**Comment by cressme** [comment]
关键我按照教程改了但是还是不生效

**Comment by zhudu** [comment]
我想他说的是侧边栏头像背后的那个背景为什么是动态的，我也有相同的疑问

**Comment by hulichao** [comment]
作者的私房菜吗？

**Comment by BNDong** [comment]
首先，你要有一个外网可以访问的 gif 动态图。
然后配置：
```javascript
window.cnblogsConfig = {
    ... // 其它配置
    menuUserInfoBgImg: 'https://xxx,jpg', // 动态图 URL
}
```

**Comment by ZZiang** [comment]
一看就是没好好看配置项，非得人家什么都给你们弄好，真懒，作者配置项个性定制开放得非常良心了。
