### ISSUE TITLE
如何关闭loading特效

### ISSUE THREAD

**Issue by lijiext** [BNDong/Cnblogs-Theme-SimpleMemory#129]
### 如何关闭进入网站时的loading特效

**Comment by BNDong** [comment]
## 关于 loading 特效 
loading 的加入本人也是不希望的，但是没办法，博客园的布局是死的，我只能通过 Js 来修改页面的布局。如果取消 loading，将会在页面加载时候看到整个页面在跳动，两个布局之间的转换过程，及其影响用户体验，个人不建议取消这部分功能！ 
## 如何关闭 loading 特效
这个没有办法通过配置来关闭，只能修改源码。
1. 注释 `simpleMemory.js` 文件代码：
```javascript
pageLoading.initRebound();
pageLoading.initSpinner();
pageLoading.spinner.init(pageLoading.spring, true);
```
2. 注释 `base.js` 文件代码：
```javascript
 bndongJs.endLoading();
```
3. 修改 css 样式：
```css
body {
    overflow: auto
}
#loading, a[name=top] {
    display: none;
}
``
