### ISSUE TITLE
请问目前代码框支持哪些字体

### ISSUE THREAD

**Issue by UserUnknownX** [BNDong/Cnblogs-Theme-SimpleMemory#130]
RT

**Comment by BNDong** [comment]
主题只支持代码框默认字体：
```css
font-family: "Ubuntu Mono", monospace
```
其它字体，主题不预设。请自行通过配置扩展！

**Comment by ZZiang** [comment]
> 主题只支持代码框默认字体：
> 
> ```css
> font-family: "Ubuntu Mono", monospace
> ```
> 
> 其它字体，主题不预设。请自行通过配置扩展！

请问有时候代码在本地编辑器上没什么问题一上传到博客上就highlight渲染失败是怎么回事。

**Comment by UserUnknownX** [comment]
> 主题只支持代码框默认字体：
> 
> ```css
> font-family: "Ubuntu Mono", monospace
> ```
> 
> 其它字体，主题不预设。请自行通过配置扩展！

谢谢

**Comment by UserUnknownX** [comment]
> > 主题只支持代码框默认字体：
> > ```css
> > font-family: "Ubuntu Mono", monospace
> > ```
> > 
> > 
> > 其它字体，主题不预设。请自行通过配置扩展！
> 
> 请问有时候代码在本地编辑器上没什么问题一上传到博客上就highlight渲染失败是怎么回事。

可能是因为博客园的Latex有很多不支持

**Comment by BNDong** [comment]
> > 主题只支持代码框默认字体：
> > ```css
> > font-family: "Ubuntu Mono", monospace
> > ```
> > 
> > 
> > 其它字体，主题不预设。请自行通过配置扩展！
> 
> 请问有时候代码在本地编辑器上没什么问题一上传到博客上就highlight渲染失败是怎么回事。

其它问题请单开 issues。
如果代码渲染有问题，可先使用博客园渲染代码，配置：
```javascript
essayCodeHighlightingType: "cnblogs"
```
如果还有问题，应该就是博客园兼容的问题了。
如果博客园渲染代码没问题，使用 `highlightjs ` 或 `prettify ` 插件渲染有问题，可提供示例代码给我，我做排查处理。
