### ISSUE TITLE
增加广告的建议

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#132]
现在的博客园收入应该只是靠广告和招聘吧，现在这个皮肤用得人多了，应该开启博客园自带广告支持一下。

建议增加可选开启广告选项，默认开启。

附上带广告的页面 https://www.cnblogs.com/yxm2020/p/12676323.html

**Comment by mumuyinxin** [comment]
建议增加每个版本新增功能显示在文档里

**Comment by mumuyinxin** [comment]
哦，我找到了
