### ISSUE TITLE
目录可以设置不用一级标题才显示吗。

### ISSUE THREAD

**Issue by Cdreamfly** [BNDong/Cnblogs-Theme-SimpleMemory#134]
我的随笔没用过一级标题因为感觉它太大了，所以可以改成有标题也可以显示目录吗。

**Comment by BNDong** [comment]
目前不可以，无一级标题都不会显示。显示的话不好计算标题序号！

**Comment by Cdreamfly** [comment]
好的，谢谢。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BNDong"<notifications@github.com&gt;; 
发送时间: 2020年4月15日(星期三) 晚上10:47
收件人: "BNDong/Cnblogs-Theme-SimpleMemory"<Cnblogs-Theme-SimpleMemory@noreply.github.com&gt;; 
抄送: "放飞梦想"<2290660986@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [BNDong/Cnblogs-Theme-SimpleMemory] 目录可以设置不用一级标题才显示吗。 (#134)





 
目前不可以，无一级标题都不会显示。显示的话不好计算标题序号！

**Comment by sky5454** [comment]
> 目前不可以，无一级标题都不会显示。显示的话不好计算标题序号！

我记得之前的有一段时间的版本是可以的

**Comment by BNDong** [comment]
> > 目前不可以，无一级标题都不会显示。显示的话不好计算标题序号！
> 
> 我记得之前的有一段时间的版本是可以的

之前版本是可以，但是标题序号会计算错误，我重构了处理逻辑，禁止了！

**Comment by sky5454** [comment]
> 之前版本是可以，但是标题序号会计算错误，我重构了处理逻辑，禁止了！
可以直接做个判断，如果`<h2>`或`<h3>`先出现于`<h1>`就直接不显示标题序号

**Comment by BNDong** [comment]
更新 `v1.3.0`，现在可以自动识别顶级标题了！
