### ISSUE TITLE
[BUG] 代码显示有两个行号

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#136]
https://www.cnblogs.com/yucloud/p/12416823.html

四个折叠代码有两个行号

折叠的代码设置如图
![image](https://user-images.githubusercontent.com/12370628/79131269-e665df80-7dda-11ea-93b6-588fbd29d1a6.png)

**Comment by BNDong** [comment]
不勾选显示行号就好了，主题渲染的行号和博客园渲染不是一个方式

**Comment by sky5454** [comment]
这个行号是这样的，比如 line 3
```
<span class="hljs-number">3</span>
一行代码内容
```
那么只要加上这个全局CSS就可以隐藏它，并且复制的时候也仅仅是每行头多复制了一个空格而已
```CSS
.hljs-number {
    display: none;
}
```

**Comment by sky5454** [comment]
编辑框勾选行号后，会有一段 `<span style="color: #008080;"> 1</span>` 表示行号
然后应该是被 hightlightJS 渲染成了以上所述的情况。

我记得以前的版本好像没有双行号的问题，应该是哪里出错了

**Comment by BNDong** [comment]
这不是一个 bug，我说了，不勾选显示行号就行了。

主题处理代码框行号是单独的，和任何渲染插件都不相关。你勾选显示行号，就会导致博客园处理一次，主题再处理一次，就会变成双行号了。主题所有渲染插件都是提取代码框的文本内容再进行二次渲染的，无法剔除博客园渲染的行号。[code](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/blob/3e7fb7121e9ad31a7ecdde2cbe7a4d1b49f5544f/src/script/base.js#L1345)

以前没有双行号的问题，是主题根本就没渲染行号这个功能！！！

**Comment by sky5454** [comment]
可以这么处理：
1. 代码框头部含有 `<span style="color: #008080;"> 1</span>` 就不渲染行号或者预处理（用正则替换掉）。这个颜色和注释的 HEX 颜色相同，不过有 "空格数字" 的格式，应该不容易误判，
附：
     - 博客园文章[含有行号的文章例子](https://www.cnblogs.com/huangrenhui/p/12712475.html)
     -  初步实现的正则匹配替换 https://regex101.com/r/qilv9Z/1

2. 用 CSS 把原来行号隐藏，不过这个渲染为什么会有这么多种...


之所以这么看重，是因为以前没有渲染行号，所以很多人都勾选了行号，这样阅读者复制代码肯定会复制了行号

**Comment by BNDong** [comment]
下个版本会对三个渲染的行号统一进行一次样式屏蔽！
