### ISSUE TITLE
默认是不允许其他人复制内容的吗？

### ISSUE THREAD

**Issue by gitworldhero** [BNDong/Cnblogs-Theme-SimpleMemory#138]
有点妨碍分享 但是又不知道在哪里设置了 找了半天 ，看上去像是必须登录后才能复制内容

**Comment by gitworldhero** [comment]
游客不能复制，但是大部分访问过来都是游客

**Comment by gitworldhero** [comment]
登录后或者这个随笔有评论   游客就可以复制里面的内容了，通过什么配置改这个权限那

**Comment by gitworldhero** [comment]
官方是这么回复的，您好，我们是博客园团队，这边确认了一下是您的自定义的主题的原因。在非登录情况下，下方的请求登录部分盖住了整个页面导致无法进行操作。
建议您修改主题的配置。

**Comment by BNDong** [comment]
该问题已发现，等我修复！最近比较忙！

**Comment by gitworldhero** [comment]
> 该问题已发现，等我修复！最近比较忙！

ok，感谢关注这个问题！

**Comment by BNDong** [comment]
更新 `v1.3.0`，该问题已修复！
