### ISSUE TITLE
太喜欢你这个样式了，弱弱的问一句，你这个可以单独抽出来自己部署吗

### ISSUE THREAD

**Issue by Raidencoo** [BNDong/Cnblogs-Theme-SimpleMemory#140]

**Comment by BNDong** [comment]
可以 Fork 本库，修改配置加载自己库的代码！

**Comment by dj2kk** [comment]
> 可以Fork本库，修改配置加载自己库的代码！

![image](https://user-images.githubusercontent.com/42986593/80346731-cb48a480-889d-11ea-91f3-8758dc6948d5.png)
加载自己的库为啥这个文件路径没有改变
