### ISSUE TITLE
code 样式会多出一行空行，请问如何修改

### ISSUE THREAD

**Issue by taoyeh** [BNDong/Cnblogs-Theme-SimpleMemory#141]
![image](https://user-images.githubusercontent.com/50255085/80103495-e61dcf00-85a6-11ea-8d38-f0db0afcdf66.png)
![image](https://user-images.githubusercontent.com/50255085/80103512-eb7b1980-85a6-11ea-8518-661838d48ed8.png)

css在哪里呢，我自己修改也行（不修改版本，毕竟个人喜好问题)多谢大佬付出 = v =

**Comment by BNDong** [comment]
个人还是建议更新版本修复问题，明天差不多会发 `v1.3.0`，可以到时候更新一下！

这个现象只有在 makdown 下才会出现，我当初是这么处理这个问题的，你可以参考一下：
![1587726907834](https://user-images.githubusercontent.com/21150911/80207025-0067b380-8660-11ea-8e76-439ed7a3bd4b.jpg)
