### ISSUE TITLE
Formula is blured and can't display well

### ISSUE THREAD

**Issue by NeoDH** [BNDong/Cnblogs-Theme-SimpleMemory#145]
Thanks your pretty theme and I like it very much.

But, when I wrote fomular just now, I found fomulars in my all blogs were blurred, like that
![批注 2020-05-02 134852](https://user-images.githubusercontent.com/40120092/80856478-f441ae80-8c7c-11ea-9a93-ff1a44fc36ce.png)

The theme version is 1.2.9 and my browser is chrome. I don't know it's my computer error or others.

**Comment by Ryedii** [comment]
@NeoDH Oh, I meet the same problem as yours.

It seems still right before 5.1 (emm maybe 5.2).

I also tried other browers, including QQbrowers and Edge, which has the same problem.

**Comment by Ryedii** [comment]
@NeoDH Ah, it seems that the problem is caused by cnblog not this theme.

**Comment by NeoDH** [comment]
> @NeoDH Ah, it seems that the problem is caused by cnblog not this theme.

Yes, I have found the discussion in [cnblogs](https://group.cnblogs.com/topic/92829.html). Incorrect display also exists in other blog themes, like formulas are crossed with text. I have replied and posted my problem. Thanks.

**Comment by NeoDH** [comment]
> @NeoDH Ah, it seems that the problem is caused by cnblog not this theme.

Cnblog have answered this question.
![捕获](https://user-images.githubusercontent.com/40120092/80866012-017f8d00-8cbf-11ea-9ce9-b7d0e1022b5b.PNG)
I will close the issue now.
