### ISSUE TITLE
搜索引擎快照(Cache)问题

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#148]
https://www.cnblogs.com/yxm2020/p/12676323.html
其快照正常: [必应搜索快照-Java数组模拟队列 队列 1、队列的理解](http://cncc.bingj.com/cache.aspx?q=Java%E6%95%B0%E7%BB%84%E6%A8%A1%E6%8B%9F%E9%98%9F%E5%88%97+%E9%98%9F%E5%88%97+1%E3%80%81%E9%98%9F%E5%88%97%E7%9A%84%E7%90%86%E8%A7%A3&d=4987891720659281&mkt=en-US&setlang=en-US&w=HawTC7Fa6HDcO2ClPgYo_NtkFVBwMf3u)

https://www.cnblogs.com/yucloud/p/vs_code_config.html
快照异常,应该还是 JS 堵塞: [必应搜索快照-VS Code 安装与配置（使用MSYS2环境与mingw-w64 编译环境）](http://cncc.bingj.com/cache.aspx?q=VS+Code+%E5%AE%89%E8%A3%85%E4%B8%8E%E9%85%8D%E7%BD%AE%EF%BC%88%E4%BD%BF%E7%94%A8MSYS2%E7%8E%AF%E5%A2%83%E4%B8%8Emingw-w64+%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83%EF%BC%89&d=4697667899694687&mkt=en-US&setlang=en-US&w=UG1awyfbmoNYQKT03e66fTxpWLkHbjxv)

可以确定是本皮肤的问题,因为你的文章我也测试过了,可以复现

**Comment by sky5454** [comment]
看了其他自定义皮肤的，好像都是因为被加载动画遮挡了。
所以有两种改进方式：
1. 遇到搜索引擎爬虫，则不加载启动动画
2. 延时 `0.01s` 加载动画

**Comment by BNDong** [comment]
目前没有办法，搜索引擎快照并不会执行 js！

**Comment by sky5454** [comment]
> 目前没有办法，搜索引擎快照并不会执行 js！

把遮盖层全部放到 JS 里就可以

**Comment by sky5454** [comment]
> 目前没有办法，搜索引擎快照并不会执行 js！

把以下样式表从 CSS 文件里去掉
```
body {
    overflow: hidden;
}
div#loading, a[name=top] {
     background-color: #f0f0f0; 
     z-index: 1099;
}
```
改放到 JS 渲染即可

**Comment by BNDong** [comment]
如果放到 js 中渲染遮罩，那就没有必要了，因为 loading 正式启动时候会再次渲染遮罩的。
css 层面加遮罩的目的同这个问题一样： #129

目前不处理，在意这个问题的，可以自行取消 css 层面的遮罩：
```css
body {
    overflow: auto
}
div#loading, a[name=top] {
    display: none
}
```

**Comment by sky5454** [comment]
刚找到了一个方案，[一种不需要 Loading 的自定义皮肤方案-awescnb-方式三](https://guangzan.gitee.io/awescnb-docs/#%E6%96%B9%E5%BC%8F%E4%B8%89)

亲测有效，确实没有 Loading 动画，在禁用 JS 的情况下也正常，可用于搜索引擎快照
