### ISSUE TITLE
能否取消自动编号

### ISSUE THREAD

**Issue by 1692134188** [BNDong/Cnblogs-Theme-SimpleMemory#152]
有些历史的博客，当时自己定义了一些编号。
现在加上模板的自动编号会有一些冲突，
请问能否去取消模板的自动编号
![QQ截图20200522065748](https://user-images.githubusercontent.com/46103957/82614103-98be6d00-9bf9-11ea-800a-e523b94c3a9b.png)

**Comment by 1692134188** [comment]
![QQ截图20200522065748](https://user-images.githubusercontent.com/46103957/82614168-bc81b300-9bf9-11ea-8d7e-618affd9bbef.png)
![QQ截图20200522065748](https://user-images.githubusercontent.com/46103957/82614208-dae7ae80-9bf9-11ea-8de1-d5f117424cb3.png)

**Comment by JacobZheng0927** [comment]
+1 希望可以配置去除自动编号

**Comment by MakerGYT** [comment]
试试[cnblogs-theme-next](https://github.com/MakerGYT/cnblogs-theme-next)
![](https://static01.imgkr.com/temp/4e9579bc084e4740873687ef112722f5.gif)
[预览](https://www.cnblogs.com/makergyt)

**Comment by BNDong** [comment]
下一版本 v1.3.3 将会增加配置，可以选择是否渲染标题样式，请留意版本更新。
