### ISSUE TITLE
设置了网站图标但是不显示

### ISSUE THREAD

**Issue by Letisl** [BNDong/Cnblogs-Theme-SimpleMemory#156]
我在其中设置了网站图标，之前还是正常的，最近突然无法显示了。

设置如下：
![image](https://user-images.githubusercontent.com/39464969/83100581-e13ac680-a0e2-11ea-8eb8-9a7ed6e41618.png)

但无法显示：
![image](https://user-images.githubusercontent.com/39464969/83100596-e861d480-a0e2-11ea-8316-a5f81df0cca7.png)

**Comment by Letisl** [comment]
还是关于icon的问题，我在页面查看了html：
![image](https://user-images.githubusercontent.com/39464969/83144159-91c9ba00-a125-11ea-91be-aa51d15793f1.png)
![image](https://user-images.githubusercontent.com/39464969/83144182-9a21f500-a125-11ea-92b2-62edcd9d1b28.png)
应该是覆盖了默认的icon的，但是实际上显示的还是默认icon。
具体的表现为有时会闪一下我自己的icon，有时直接不闪，但最后显示的均为默认icon，不知道原因。
贴一个博客页面网址以供有精力的大佬帮忙查找问题，非常感谢！
https://www.cnblogs.com/letisl/p/12377168.html

**Comment by BNDong** [comment]
现在还有这个现象么？很奇怪！我测试时候都没问题！

**Comment by BNDong** [comment]
建议网站图标大小 32*32

**Comment by Letisl** [comment]
已解决此问题。
