### ISSUE TITLE
在标题上的自定义锚点失效

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#162]
在标题上打的锚点，会被替换掉，造成自定义的锚点丢失
如文章原内容的 html 内容为
```
<hr />
<h2><a name="Reference"></a>FAT 系权威资料大全</h2>
<p>维基百科资料</p>
```
皮肤处理后会变成
```
<hr />
<span title-type="h2" class="header__span" style="transform:scale(1.0);"><h2 tid="tid-exGDZm" class="header__dev" id="hid-B5ZdSS"><span style=""><b class="dev__fe"><i>4</i></b><span class="dev__slash">|</span><b class="dev__ux"><i>0</i></b></span><b class="dev__developer"><span class="dev__title">FAT 系权威资料大全</span></b></h2></span>
<p>维基百科资料</p>
```

根据情况来看，不只是丢失锚点，所有附加到标题上的属性都会丢失

**Comment by sky5454** [comment]
复现：https://www.cnblogs.com/yucloud/p/10943215.html#Reference

**Comment by MakerGYT** [comment]
[cnblogs-theme-next](https://github.com/MakerGYT/cnblogs-theme-next)
![](https://static01.imgkr.com/temp/4e9579bc084e4740873687ef112722f5.gif)
[预览](https://www.cnblogs.com/makergyt)

**Comment by BNDong** [comment]
下一版本 v1.3.3 将会增加配置，可以选择是否渲染标题样式，请留意版本更新。
