### ISSUE TITLE
移动端（代码块显示不全）

### ISSUE THREAD

**Issue by mumuyinxin** [BNDong/Cnblogs-Theme-SimpleMemory#165]
代码块在移动端无法显示全部，代码块不全，也拖不动，希望能有友好显示

**Comment by sky5454** [comment]
1.3.x 版本是没有问题的，我记得 1.2.x 某个旧版本有这个问题

**Comment by mumuyinxin** [comment]
我是1.2.9，我尝试更新下，谢谢

**Comment by mumuyinxin** [comment]
出现了个新问题，移动端菜单打开，设置里的分类啥的都没了

**Comment by BNDong** [comment]
代码块的问题 `v1.3.0` 修复了。
你的新问题，请提供示例地址。
