### ISSUE TITLE
自定义仓库皮肤的 bug --- hljs 的 css 地址错误

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#166]
当使用的仓库不为本仓库，而是fork 的仓库时。如果 GhVersions 的值是 hash 值，那么就没有问题
a225e 是我提交的 https://github.com/sky5454/Cnblogs-Theme-SimpleMemory/commit/a225e147cc45f166db936107da57a843e60494b8
样式地址为 https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@a225e147cc45f166db936107da57a843e60494b8/src/style/highlightjs/vs2015.min.css
```JavaScript
   window.cnblogsConfig = {
  GhUserName: 'sky5454',
  GhRepositories: 'Cnblogs-Theme-SimpleMemory',
  GhVersions: 'a225e147cc45f166db936107da57a843e60494b8',
```
如果 GhVersions 的值为 Tag 值时（或者说不为 hash 值），hljs 的 CSS 文件链接会出错。
如以下配置，会让 CSS 路径定位到 https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@sky5454-now/src/style/highlightjs/vs2015.min.css
```
   window.cnblogsConfig = {
  GhUserName: 'sky5454',
  GhRepositories: 'Cnblogs-Theme-SimpleMemory',
  GhVersions: 'sky5454-now',
```

个人认为这个是 jsdeliver.net 的问题，但应该在文档里注明

**Comment by BNDong** [comment]
这个是代码的问题， fork 后的 hljs 样式文件应该引用你仓库的文件而不是我仓库的文件。
感谢！下一版本修复更新此问题。
