### ISSUE TITLE
关于 HighLightJS 的疑惑

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#168]
浏览器抓包可以看到 highlightjs 加载了两个
 - 一个是博客园的cdn：v9.12.0    (大小 36KB)
 - 一个是本皮肤的cdn：v9.13.1    (大小 235KB，而里面大部分是国际各国语言符号，中文博客用不到的）

在 [CDN](https://www.bootcdn.cn/highlight.js/9.13.1/) 下载的 hljs 也没那么大，弱弱地问一下你是不是把全部语言包勾上了(doge)

另外 hljs 更新了版本 [v10](https://github.com/highlightjs/highlight.js)，而且更新的破坏性不大

![image](https://user-images.githubusercontent.com/12370628/84588349-3869c680-ae59-11ea-9396-b51b9fa175ad.png)

**Comment by BNDong** [comment]
这个压缩 js 当初应该是直接从官网下载下来的。我测了一下 v10 版本没什么问题，下个版本直接引用目前最新版 v10.1.1。

**Comment by BNDong** [comment]
感谢🙏
