### ISSUE TITLE
博客园原生功能支持【友情链接、订阅】

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#170]
**【友情链接】**
可以用博客园后台管理界面提供的链接：
https://i.cnblogs.com/links

这个本来就是博客园提供的友链功能。

***【订阅】**
博客园的订阅功能不止是 RSS 订阅，还有站内消息留订阅功能。
详见
https://www.cnblogs.com/gebron/

![image](https://user-images.githubusercontent.com/12370628/85204820-b2aeb500-b349-11ea-9651-d81ddd1fe509.png)

点订阅后，会在博客园首页显示订阅博主的文章
点 `RSS` 按钮，则依然是 RSS 地址

**Comment by BNDong** [comment]
嗯，感谢！这块后续需要调整下，把官方的订阅事件触发下！

最近在公司带团队对接项目，比较忙，已有的问题我抽时间研究下，再次感谢。

**Comment by BNDong** [comment]
下一版本订阅功能更新，可以先去我博客看看效果！
友情链接保持现有的，官方的不太好用，后续有精力单独做一个友链页面！
