### ISSUE TITLE
侧边公告栏的订阅跳转

### ISSUE THREAD

**Issue by like3ong** [BNDong/Cnblogs-Theme-SimpleMemory#174]
跳转页面后出现这个，是需要改源代码吗？
This XML file does not appear to have any style information associated with it. The document tree is shown below.

**Comment by MakerGYT** [comment]
[cnblogs-theme-next](https://github.com/MakerGYT/cnblogs-theme-next)
![](https://static01.imgkr.com/temp/4e9579bc084e4740873687ef112722f5.gif)
[预览](https://www.cnblogs.com/makergyt)

**Comment by BNDong** [comment]
> 跳转页面后出现这个，是需要改源代码吗？
> This XML file does not appear to have any style information associated with it. The document tree is shown below.

那个是 Rss 订阅，以前博客园订阅好像只是 Rss 下一版本兼容现在的订阅方式！
