### ISSUE TITLE
建议采用 DNS-Fetch 技术和 Preload 技术

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#175]
使用例子（GITHUB 是这样用的）
```HTML
<head>
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
  <link rel="preload" href="//js.cdn.com/currentPage-part3.js" as="script">
...
</head>
<body>
...
<script type="text/javascript" src="//js.cdn.com/currentPage-part1.js" defer></script>
</body>
```

用于预解析 DNS 和预加载资源，避免后面花费时间而堵塞了请求。

参考：
- Preload
1. https://segmentfault.com/a/1190000011577248
- DNS-Fetch 
1. https://www.cnblogs.com/goloving/p/9368965.html
2. https://developer.mozilla.org/zh-CN/docs/Controlling_DNS_prefetching
3. https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch

**Comment by sky5454** [comment]
这是某些情况下，DNS 解析耗费的时间
![image](https://user-images.githubusercontent.com/12370628/86505349-ec75c600-bdf5-11ea-852d-cc4b8af0db7c.png)

**Comment by BNDong** [comment]
我需要抽时间评估下，现在页面已经是按需加载不同的 js 文件了
博客园不能修改初始 html 结构，这一点很头疼，Preload 技术并不能很好的应用。我考虑下是否有好的方式使用到 DNS-Fetch 技术。
