### ISSUE TITLE
关于hljs的建议 ： 优化语言高亮的方案

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#176]
提供一个配置让用户自己设置常用的 语言 及其别名

如 `hljs语言名 : 自定义别名`
```json
{
    x86asm: ['nasm', 'asm'],
    cpp : ['c++', 'Visual C++']
}
```

然后程序判断
如果语言不存在于hljs默认包里，就通过 CDN 引入语言包，如 x86asm 语言包的 CDN 地址是 `<script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.1.1/languages/x86asm.min.js"></script>`
存在则直接渲染

渲染实现如下：

```
    document.addEventListener('DOMContentLoaded', (event) => {
        hljs.registerAliases(['nasm','asm'], {languageName :"x86asm"});
        document.querySelectorAll('pre code').forEach((block) => {
             hljs.highlightBlock(block);
        });
    });
```
这样就能按照语言正确渲染了

**Comment by ZZiang** [comment]
请问这样可以解决C++有时会渲染失败的问题吗

**Comment by sky5454** [comment]
> 请问这样可以解决C++有时会渲染失败的问题吗

我试了一下，可以。你给一下地址测试吧。

**Comment by ZZiang** [comment]
https://www.cnblogs.com/Kanoon/p/12711803.html
https://www.cnblogs.com/Kanoon/p/13279773.html

**Comment by sky5454** [comment]
> https://www.cnblogs.com/Kanoon/p/12711803.html
> https://www.cnblogs.com/Kanoon/p/13279773.html

这个暂时没办法，因为你在编辑的时候没有选择代码的语言类型。
另外建议升级到`1.3.2`，加载速度会快一些

**Comment by ZZiang** [comment]
> > https://www.cnblogs.com/Kanoon/p/12711803.html
> > https://www.cnblogs.com/Kanoon/p/13279773.html
> 
> 这个暂时没办法，因为你在编辑的时候没有选择代码的语言类型。
> 另外建议升级到`1.3.2`，加载速度会快一些

emmm，虽然我也想换到最新的版本，但是感觉不同层级的标题样式都一个颜色太单一，而且代码行号需要再手动设置一篇篇地改太麻烦了...

**Comment by sky5454** [comment]
> emmm，虽然我也想换到最新的版本，但是感觉不同层级的标题样式都一个颜色太单一，而且代码行号需要再手动设置一篇篇地改太麻烦了...

这个是 hljs 的自动识别，但是感觉不怎么样，误识别率非常高。
hljs 也提供指定语言渲染的方法，可以看看 hljs 文档
