### ISSUE TITLE
bug： js 地址错误

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#177]
`https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@master/src/script/jquery.mousewheel.min.js`
在 1.3.2 应改为
`https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@master/src/script/lib/jquery.mousewheel.min.js`

另外，基于 master 的改变并不适合，建议基于分支

**Comment by BNDong** [comment]
修复了，这个文件疏忽了。所有执行文件 url 获取都是经过函数 `getJsDelivrUrl` 通过配置信息生成的，本以为改变目录不会影响其它版本的加载。
