### ISSUE TITLE
页脚文字是否可以隐藏或删除

### ISSUE THREAD

**Issue by onyxiakylin** [BNDong/Cnblogs-Theme-SimpleMemory#178]
开发者大大你好，想问下页脚的这些字能否隐藏或删除
比如图中的时长和版本号（Theme Version）
![footer](https://user-images.githubusercontent.com/45504471/87877164-4e961400-ca0f-11ea-88e2-6ed2b01dd09d.png)

若能，还请大大教下我这个小白，感谢！

**Comment by BNDong** [comment]
目前不可以，可以自己通过 css 控制下。

**Comment by onyxiakylin** [comment]
所以具体怎么改可以提示一下吗，我是这方面的小白555
