### ISSUE TITLE
页脚文字是否可以隐藏，比如版本号信息之类的

### ISSUE THREAD

**Issue by wkjCoder** [BNDong/Cnblogs-Theme-SimpleMemory#179]
这些文字是否可以隐藏呢，求大佬指点下
![屏幕快照 2020-07-24 上午8 18 38](https://user-images.githubusercontent.com/17669643/88350679-63173b00-cd86-11ea-8f08-014a2b491906.png)

**Comment by BNDong** [comment]
目前不可以，可通过 css 自己控制下。

**Comment by wkjCoder** [comment]
> 目前不可以，可通过 css 自己控制下。

OK，谢谢，已满足需求了
