### ISSUE TITLE
使用了该主题无法显示评论

### ISSUE THREAD

**Issue by zkm1992** [BNDong/Cnblogs-Theme-SimpleMemory#18]
作者你好，我使用了你的这套博客主题，现在发现评论无法显示，不知道是哪里出了问题。请您指点迷津，因为我是做JAVA后端的，对前端只是略知一二，希望你能提供个思路，我可以根据你的思路去排查一下这个问题，非常感谢！

**Comment by BNDong** [comment]
请提供下地址
