### ISSUE TITLE
关于语法高亮

### ISSUE THREAD

**Issue by hs-black** [BNDong/Cnblogs-Theme-SimpleMemory#180]
本人使用 c++ 语言，代码块有写 cpp，有时候因为代码较长而把头文件略去或者只写关键函数，但这样代码就无法正常渲染了，基本上是随机渲染，请教大神有什么好的解决办法吗。

https://www.cnblogs.com/Hs-black/p/13353508.html

https://www.cnblogs.com/Hs-black/p/13327024.html

https://www.cnblogs.com/Hs-black/p/13320691.html

**Comment by BNDong** [comment]
下一版本 `v1.3.3` 将会增加配置，可以配置使用 hljs 渲染代码时，限制自动识别语言的语言范围。

**Comment by hs-black** [comment]
太感谢力！

**Comment by BNDong** [comment]
已更新！
