### ISSUE TITLE
标题过长会隐藏内容或遮住正文内容

### ISSUE THREAD

**Issue by shouyaya** [BNDong/Cnblogs-Theme-SimpleMemory#183]
## 标题过长会隐藏内容

![image](https://user-images.githubusercontent.com/61981441/89754428-6e9c8d00-db0e-11ea-9172-64a7ccb37e0f.png)

## 标题过长遮住正文内容

![image](https://user-images.githubusercontent.com/61981441/89754452-83792080-db0e-11ea-9f7d-9c2c4ea909f4.png)

**Comment by BNDong** [comment]
下一版本 `v1.3.3` 将会增加配置，可以选择是否渲染标题样式，请留意版本更新。

**Comment by BNDong** [comment]
已更新！
