### ISSUE TITLE
页首homeBannerText实现自定义内容如何换行

### ISSUE THREAD

**Issue by ZhaoZeWen** [BNDong/Cnblogs-Theme-SimpleMemory#185]
页首homeBannerText实现自定义内容后如何还可以新起一行然后再写一行英文内容？看你的博客是三个标签一个h1、h2、h3显示的话如何写配置内容？
![image](https://user-images.githubusercontent.com/37575979/90381833-85b02180-e0b0-11ea-98fe-07b3d9ae5242.png)

**Comment by BNDong** [comment]
自定义，只支持一段内容的配置。
可自己编写 js 写入其它内容。
