### ISSUE TITLE
如何取消标题序号的动效

### ISSUE THREAD

**Issue by haiyang0320** [BNDong/Cnblogs-Theme-SimpleMemory#187]
如图
![批注 2020-08-20 193036](https://user-images.githubusercontent.com/56353822/90764895-ad56f200-e31b-11ea-8227-bc0b047a5827.png)

**Comment by BNDong** [comment]
下一版本 `v1.3.3` 将会增加配置，可以选择是否渲染标题样式，请留意版本更新。

**Comment by BNDong** [comment]
已更新！

**Comment by Letisl** [comment]
请问能否设置为显示序号，但不自动折叠起来呢？
