### ISSUE TITLE
1.3.3版本底部的广告是否可以去除？

### ISSUE THREAD

**Issue by xiaowangtongxue0110** [BNDong/Cnblogs-Theme-SimpleMemory#190]
RT

**Comment by liujianchao1995** [comment]
js中设置
window.cnblogsConfig = {
advertising: false //是否显示博客园广告
}
或者样式中添加
#ad_c1, #ad_c2, #ad_t1, #ad_t2, #cnblogs_c1, #cnblogs_c2, #under_post_kb, #under_post_news {
    display: none !important;
}
