### ISSUE TITLE
如何快速返回首页？

### ISSUE THREAD

**Issue by ZhaoUncle** [BNDong/Cnblogs-Theme-SimpleMemory#192]
每次访问首页，需要跳到首页，都需要点击“MENU”菜单栏，再点击首页，有点繁琐，能不能在某个地方设置一个首页点击跳转的固定按钮呢？

**Comment by ZhaoUncle** [comment]
另外，菜单弹窗设置为悬停打开会不会好一点，不需要每次点击

**Comment by ZhaoUncle** [comment]
分类、标签，是否可以考虑做成这种折叠的方式
![image](https://user-images.githubusercontent.com/31182637/94543481-b6bd6d80-027c-11eb-944f-458790055738.png)

**Comment by steinvenic** [comment]
+1
