### ISSUE TITLE
网络比较慢的时候会一直加载，网络慢还有一个问题就是左侧菜单栏也关闭不了

### ISSUE THREAD

**Issue by XiaoHuiHuiT** [BNDong/Cnblogs-Theme-SimpleMemory#194]
![image](https://user-images.githubusercontent.com/52324484/94698936-5c033f00-036c-11eb-9282-b916518f9fff.png)

![image](https://user-images.githubusercontent.com/52324484/94698981-68879780-036c-11eb-9f9c-42da4251e74f.png)

**Comment by BNDong** [comment]
把你自己自定义的js去了，再提问题！
