### ISSUE TITLE
大佬你好，可以使用这个博皮的部分源码封装一个博客前台吗

### ISSUE THREAD

**Issue by LLiuHuan** [BNDong/Cnblogs-Theme-SimpleMemory#196]
大佬你好，可以使用这个博皮的部分源码封装一个博客前台吗，真的非常喜欢这个样式

**Comment by BNDong** [comment]
感谢！可以是可以，但是，实在没时间弄！
本来也想系统的学习下前端，将代码模块化重构了，但一直没精力弄；
每天手里的项目忙的焦头烂额的，并且这个也是非盈利的。等以后闲下来，我再尝试下。

**Comment by LLiuHuan** [comment]
好的，感谢大佬

**Comment by LLiuHuan** [comment]
我先尝试弄一版   弄完了通知大佬

**Comment by winshu** [comment]
> 我先尝试弄一版 弄完了通知大佬

大兄弟弄出来了么
