### ISSUE TITLE
文章目录深度的扩展

### ISSUE THREAD

**Issue by zqybegin** [BNDong/Cnblogs-Theme-SimpleMemory#197]
您好，如何可以扩展文章目录深度呢？现在的目录深度只有两级，有些不太够用。

**Comment by BNDong** [comment]
目前只支持到二级目录。不想往下兼容，主要也是考虑两个方面：
1）标题的使用不规范；有的用户使用小标题，单纯的只是想加粗文字，并不是为了标题而设置标题！
2）更多的层级计算起来比较复杂；例如，文章目录为`h2  h1 h2 h3 h1 h3 h4 h1 h2 h1 h2`，如果一级标题和子级标题出现断层，怎么目录应该怎么显示也是个问题！！

**Comment by crossyourheart** [comment]
> 目前只支持到二级目录。不想往下兼容，主要也是考虑两个方面：
> 1）标题的使用不规范；有的用户使用小标题，单纯的只是想加粗文字，并不是为了标题而设置标题！
> 2）更多的层级计算起来比较复杂；例如，文章目录为`h2 h1 h2 h3 h1 h3 h4 h1 h2 h1 h2`，如果一级标题和子级标题出现断层，怎么目录应该怎么显示也是个问题！！

请问 如何 设置目录默认是展开的，当前是需要手动点击展开。我在文档上没有看到有这个设置，但是大佬的博客 是默认展开的

**Comment by BNDong** [comment]
最新版本v2.0.0支持多级目录生成。
