### ISSUE TITLE
大佬你好，主页banner上的标语homeBannerText可以支持自定义换行吗？

### ISSUE THREAD

**Issue by burc-li** [BNDong/Cnblogs-Theme-SimpleMemory#200]
配置项homeBannerText只能显示一行，只有文字过长才会自动换行

我想在主页自定义多行文字，自己控制换行时机，这样配置可以吗？
感谢

homeBannerText: [
      {
          firstLine: "第一行",
         secondLine: "第一行",
      },{
          firstLine: "第一行",
         secondLine: "第一行",
      },{
          firstLine: "第一行",
         secondLine: "第一行",
      },
],

**Comment by BNDong** [comment]
目前版本不可以，等下个版本吧！到时候可以通过增加 `<br>` 标签来控制换行。

**Comment by burc-li** [comment]
好的，灰常感谢
