### ISSUE TITLE
使用之后经常加载不出来，也不知道是什么原因

### ISSUE THREAD

**Issue by pengpeng12138** [BNDong/Cnblogs-Theme-SimpleMemory#202]
就一直卡在开始界面的那个三角形，不停的转圈圈。我也没有用其他什么插件啊

**Comment by BNDong** [comment]
给个链接我瞅瞅！

**Comment by pengpeng12138** [comment]
> 给个链接我瞅瞅！

https://www.cnblogs.com/RichRichie/       麻烦老哥看下

**Comment by pengpeng12138** [comment]
我知道了老哥，我少写了一个逗号。我已经搞好啦，很漂亮的博客界面。谢谢老哥~
