### ISSUE TITLE
使用CSS之后打开自己的博客白屏无界面，找博客园他说CSS有问题

### ISSUE THREAD

**Issue by wjt246932** [BNDong/Cnblogs-Theme-SimpleMemory#203]
博客园团队反馈的图片如下![](https://i.loli.net/2020/10/20/h4E9rWqMD1tBo7y.png)
使用最新的版本和之前的大部分版本都不行，博客园地址如下：problem.cnblogs.com

**Comment by BNDong** [comment]
有js权限么？

**Comment by wjt246932** [comment]
有的，在网上随便找一些装修的代码都可以显示

**Comment by wjt246932** [comment]
我太难了

**Comment by BNDong** [comment]
你开启侧边栏公告了么？

**Comment by wjt246932** [comment]
![微信截图_20201022170523](https://user-images.githubusercontent.com/72793439/96849949-d49b7e00-1488-11eb-9c04-93a0030fa0c7.png)

**Comment by wjt246932** [comment]
![](https://i.loli.net/2020/10/22/7W481pQxfOzF3E2.png")

**Comment by wjt246932** [comment]
![截图](https://i.loli.net/2020/10/22/7W481pQxfOzF3E2.png)

**Comment by BNDong** [comment]
安装教程：https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/Docs/GettingStarted/install
视频教程：https://pan.baidu.com/s/1wDCrM1Uo9iZ6ppBZDU7wKQ?errmsg=Auth+Login+Sucess&errno=0&ssnerror=0&

**Comment by wjt246932** [comment]
![截图](https://sm.ms/image/7W481pQxfOzF3E2)

**Comment by wjt246932** [comment]
教程也都看过了，没啥问题，我给您私信，您登陆一下帮我看一下可以吗

**Comment by BNDong** [comment]
可以

**Comment by wjt246932** [comment]
发您dbnuo@foxmail.com这个邮箱了

**Comment by wjt246932** [comment]
仰慕BNDong大佬

**Comment by wjt246932** [comment]
牛逼，弄好了，请教大佬是啥问题

**Comment by BNDong** [comment]
已经解决，账户已退出。

原因：
1）配置有误，v1.0 版本和之后版本不能混用
2）未开启公告选项（不开启的话，即使有js权限也不会运行侧边栏里的js代码）

**Comment by wjt246932** [comment]
感谢大佬
