### ISSUE TITLE
可以加个赞赏码功能么？

### ISSUE THREAD

**Issue by Praying** [BNDong/Cnblogs-Theme-SimpleMemory#208]
如题

**Comment by BNDong** [comment]
有这个配置，去看文档！

**Comment by Praying** [comment]
额，已经配置了，但是有一个问题，就是显示赞赏码的窗口特别小，我刚刚试了下，我自己的赞赏码扫不出来。支付宝和公众号的勉强可以，但是微信赞赏码扫不出来。https://www.cnblogs.com/praying/p/13912818.html

**Comment by BNDong** [comment]
你截个正方形的收款码，像我博客配置的形式！

**Comment by Praying** [comment]
好吧b（￣▽￣）d
