### ISSUE TITLE
电池杀手主题

### ISSUE THREAD

**Issue by daviyang35** [BNDong/Cnblogs-Theme-SimpleMemory#209]
打开此主题的文章，CPU 一个核直奔100%，功耗飙升。

猜测是美化页面的动态效果导致的，且没有开关能关闭。

打开 https://www.cnblogs.com/you-men/p/13909676.html 

![image](https://user-images.githubusercontent.com/4261582/97800747-bb59b500-1c72-11eb-8dd8-6a40acdf869a.png)

**Comment by BNDong** [comment]
你确定不能关闭？
关闭随笔页的动效会好点。
