### ISSUE TITLE
css样式没有生效

### ISSUE THREAD

**Issue by maoxianfei** [BNDong/Cnblogs-Theme-SimpleMemory#21]
![image](https://user-images.githubusercontent.com/17768860/59406810-f5a68600-8de1-11e9-98e3-3b86a1392a04.png)

配置如上
地址：https://www.cnblogs.com/maoxianfei/

**Comment by BNDong** [comment]
页面定制css代码位置，填写的是文件的CSS代码，而不是URL！！

**Comment by maoxianfei** [comment]
我傻逼了。。。感谢，已经可以了
