### ISSUE TITLE
博客园广告屏蔽不完全

### ISSUE THREAD

**Issue by Holaplace** [BNDong/Cnblogs-Theme-SimpleMemory#210]
开发大大，
我在配置的时候，发现评论框还是有两行广告，已在下面的图片中标识出来。
另外，屏蔽之后的原来元素感觉留白空隙稍大。
不知道开发大大是否感觉有必要调整，谢谢
![image](https://user-images.githubusercontent.com/45121260/97981499-5a1a1900-1e0d-11eb-8262-570ecc1387d2.png)

**Comment by BNDong** [comment]
下次调整！
