### ISSUE TITLE
如何自定义markdown的格式

### ISSUE THREAD

**Issue by hsh778205** [BNDong/Cnblogs-Theme-SimpleMemory#219]
我想让我本地的markdown编辑器(Typora)的格式和博客园的样式相同，这样方便于编辑和排版。

本地编辑器用了一个它下载的Purple.CSS

如何把这个css应用到博客园上面？

或者，能不能把博客园的样式和编辑器的样式统一（但是字体要放大）

**Comment by BNDong** [comment]
你这有点难为我了，你可以编辑后保存草稿看看效果，我没法做适配。
