### ISSUE TITLE
多级标题显示不正确，只能显示到二级标题

### ISSUE THREAD

**Issue by Dacyuan** [BNDong/Cnblogs-Theme-SimpleMemory#221]
![屏幕截图 2020-12-04 112031](https://user-images.githubusercontent.com/33952239/101117813-d2e5de00-3622-11eb-83ab-62d13fcc97bc.png)

**Comment by hsh778205** [comment]
这个问题以前有过，是说为了匹配大多人的博客。

有的人会把h3~h6当作加粗来用，或者标题格式很乱而无法渲染所以只现实到h2（？）

**Comment by Dacyuan** [comment]
对，其实也没啥。但是影响观看，右边的导航部分只显示到了二级标题处，三，四，五，都没法显示


| |
chengyuanda19
|
|
chengyuanda19@163.com
|
签名由网易邮箱大师定制
在2020年12月4日 11:28，何劭弘<notifications@github.com> 写道：

这个问题以前有过，是说为了匹配大多人的博客。

有的人会把h3~h6当作加粗来用，或者标题格式很乱而无法渲染所以只现实到h2（？）

**Comment by BNDong** [comment]
最新版本v2.0.0支持多级目录生成。
