### ISSUE TITLE
主题发热严重

### ISSUE THREAD

**Issue by dabuc** [BNDong/Cnblogs-Theme-SimpleMemory#224]
博客页面长时间不关闭，风扇狂转，发热量大

**Comment by LiuZhangpeng** [comment]
+1, 渲染背景动画好像没处理好, 放着放着温度就上来了

**Comment by StarkLiu9973** [comment]
+1，cpu使用率飙升百分之二三十

**Comment by BNDong** [comment]
特效先关关，我看看，后续有精力，我把基础架构重构了

**Comment by Ercilan** [comment]
是的，每次一打开，cpu占用率由个位数上升到20~30%。暂时先弃用了。但是好像如果没有修改过代码的话，好像使用率又没那么高，但是我的代码也没什么很耗性能的，很奇怪

**Comment by zhaoqingqing** [comment]
@BNDong 你好，请问性能问题解决了吗？ 很早之前我想采用这款主题就注意到这个问题了，还有这款主题的加载时间有些长

**Comment by HuangJian** [comment]
[ribbonsEffect.js](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/blob/v2/src/vendor/ribbonsEffect/ribbonsEffect.js) 里有个死循环一直计算以绘制背景动画，导致大量占用 CPU/GPU 资源。

我尝试在 μBlock 添加过滤规则，不载入该文件，就不发热了。
```
||cdn.jsdelivr.net/*RibbonsEffect*$script,domain=www.cnblogs.com
```
