### ISSUE TITLE
你好，请问1.2.7版本更新到1.3.3版本后图标库为什么不生效了

### ISSUE THREAD

**Issue by Layton-sy** [BNDong/Cnblogs-Theme-SimpleMemory#227]
这是我在1.2.7设置的fontIconExtend: "//at.alicdn.com/t/font_543384_ezv3l7gd9r7.css",

放到1.3.3的配置项里面就不生效了

谢谢大佬，大佬nb

**Comment by Layton-sy** [comment]
以及新版本的暗黑模式图片亮度会降低，有配置能不江堤图片的亮度吗，麻烦大佬了~

**Comment by BNDong** [comment]
应该生效的，也可能是样式与默认的冲突了，这个具体我得看下！

暗黑模式图片亮度会降低这个没办法通过配置调整，目前只能这样，我认为这种处理方式体验会更好一些！
