### ISSUE TITLE
你好，我将js文件上传至博客园文件中，loading失败了

### ISSUE THREAD

**Issue by Ceoces** [BNDong/Cnblogs-Theme-SimpleMemory#231]
我将您的代码getJsDelivrUrl()部分修改为：
`
// get file url
function getJsDelivrUrl(file, directory) {
    file = setFileNameMin(file, directory);
    return 'https://blog-static.cnblogs.com/files/HadesBlog/' + (file ? file : '');
}
`
修改后报错：Uncaught ReferenceError: pageLoading is not defined            simpleMemory.js:409
可能是一个请求地址没有通过getJsDelivrUrl()函数构造，这是我404的地址：https://blog-static.cnblogs.com/files/HadesBlog/src/script/loading.min.js
我在您的代码中没有发现请求loading.min.js的部分。而且代码是在这部分的 window.cnblogsConfig.hook.beforeLoading(pageLoading);报错：
`    
// load loadingJs
    $.getScript(getJsDelivrUrl('loading.js'), function () {

        // Loading start
        window.cnblogsConfig.hook.beforeLoading(pageLoading);
        pageLoading.initRebound();
        pageLoading.initSpinner();
        pageLoading.spinner.init(pageLoading.spring, true);

        $.getScript(getJsDelivrUrl('jquery.mCustomScrollbar.min.js'), function () {
            $.getScript(getJsDelivrUrl('require.min.js'), function () {
                $.getScript(getJsDelivrUrl('config.js'), function () {
                    var staticResource = [
                        // 'optiscroll', 'ToProgress', 'rotate',
                        'optiscroll_ToProgress_rotate',
                        'snapSvg', 'classie', 'main4', 'tools'];
                    require(staticResource, function() {
                        require(['base'], function() {
                            (new Base).init();
                        });
                    });
                });
            });
        });
    });
`
想请问一下是不是还有地址需要修改

**Comment by BNDong** [comment]
如果你将文件上传到自己的博客文件中，文件名需要带.min，代码生成URL时候发现没有.min会自动加上！

例如：
`loading.js`  => `loading.min.js`
`require.min.js`  => `require.min.js`
