### ISSUE TITLE
你好，请问如何修改主页的背景图片

### ISSUE THREAD

**Issue by YuiQwert** [BNDong/Cnblogs-Theme-SimpleMemory#234]
似乎没有看到可以修改的地方emm，请问在哪里修改呢，谢谢

**Comment by hsh778205** [comment]
![image](https://user-images.githubusercontent.com/51521470/107747858-19f2fc80-6d53-11eb-8d1a-726fc02c08dc.png)
其中
```
  homeTopImg    : [
            "https://images.cnblogs.com/cnblogs_com/send-off-a-friend/1478490/o_2011021020570072Vf1pgy1foxk7froooj31kw0w0hd1-0-4-0-0.5.jpg"
        ],
```
是我的首页背景，
```
	essayTopImg: [
		"https://images.cnblogs.com/cnblogs_com/send-off-a-friend/1478490/o_201031054623infocenterbg.a1a0d152.jpg"
	],
```
是看随笔时的头部图片。
具体请见[https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/Docs/Customization/config](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/Docs/Customization/config)

**Comment by hsh778205** [comment]
@YuiQwert

**Comment by miaopan607** [comment]
> @YuiQwert

啊懂了，谢谢！
