### ISSUE TITLE
使用highlightjs渲染代码块，一篇博客中包含多处代码块时，渲染会出现问题

### ISSUE THREAD

**Issue by guanidine** [BNDong/Cnblogs-Theme-SimpleMemory#235]
![image](https://user-images.githubusercontent.com/58496879/108800704-da3bd880-75ce-11eb-9eb6-7f3e16a6759d.png)
![image](https://user-images.githubusercontent.com/58496879/108800818-1d964700-75cf-11eb-9d03-74ac0e1b2f43.png)
如上图所示，使用
```js
essayCodeHighlightingType: "highlightjs",
essayCodeHighlighting: "a11y-dark",
```
配置后渲染出的代码块，第一个代码块渲染正常，而后面的代码块渲染颜色就出现了问题。目前C和C++代码块，essayCodeHighlighting使用darcula、atom-one-dark等均会出现相同问题，希望大佬能提供一个解决方案，谢谢Thanks♪(･ω･)ﾉ
这是使用默认渲染的结果
![image](https://user-images.githubusercontent.com/58496879/108800995-8382ce80-75cf-11eb-86cb-e27d02edd71d.png)

**Comment by BNDong** [comment]
使用hljs渲染代码使用的是自动识别语言的模式，可能识别语言不准确造成的。
可以v1版本可以通过配置`essaycodelanguages`来限定语言识别范围，[参考](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/Docs/Customization/config?id=essaycodelanguages)。

目前在重构代码，关于这个问题我考虑下有没有更优的解决方式！

**Comment by guanidine** [comment]
感谢回复，目前问题已经解决了。也有可能是hljs自己优化了识别的算法，现在使用hljs渲染，在不限定语言的情况下已经没有之前所说的问题了。
