### ISSUE TITLE
代码块最后总是会多处一行来

### ISSUE THREAD

**Issue by miaopan607** [BNDong/Cnblogs-Theme-SimpleMemory#236]
代码块的最后总是会多出一行空行

**Comment by BNDong** [comment]
什么版本？之前有版本在使用makdown出现过这个问题，后来更新修复了一次！

**Comment by miaopan607** [comment]
啊这，我本来以为我的是最新版，后来一看不是……

感谢回复

**Comment by miaopan607** [comment]
更新了，无此bug，感谢

不过为什么我在[https://github.com/BNDong/Cnblogs-Theme-SimpleMemory](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory)这里下载的不是最新版啊，是我对GitHub不够熟悉吗？

**Comment by BNDong** [comment]
目前版本升级需要手动切换，应该是我后续升级了版本。
现在我在重构代码，后续热更新也可以做到，到时候我会出文档的。

**Comment by miaopan607** [comment]
为什么总是有两篇博文连在一起？emmmm，就是说：
![image](https://user-images.githubusercontent.com/64201424/114011493-dbcc1200-9897-11eb-9e6d-266b522b0fff.png)

**Comment by BNDong** [comment]
同一天发布的文章会在一起
