### ISSUE TITLE
v2.0.0 的文章后缀信息框好像有点问题？

### ISSUE THREAD

**Issue by Point-King** [BNDong/Cnblogs-Theme-SimpleMemory#239]
新的文章后缀信息框的高度好像存在问题，不能显示全部文字，而且头像不能更换。

同时文末点赞和点踩的图标的高度好像不一致，不知是特意而为还是出问题了。

望解答，谢谢。

**Comment by Point-King** [comment]
还有一个小问题，就是刚进入一个页面的时候默认为跳至底部应该会更好点，现在是默认跳至顶部。

**Comment by Point-King** [comment]
哦，好像点赞和点踩按钮在浏览器不同缩放下的位置不一样，在100%的时候是正常的，但是80%就不正常了。

**Comment by Point-King** [comment]
哦，然后我修改了一下字号发现信息框的高度就没有问题了。。。

**Comment by Point-King** [comment]
感觉我自己快要解决完了（因为都是蠢问题），现在还剩下的问题是：

1. 点赞和点踩按钮在缩放 90%（及以下） 的情况下是一上一下的（这个感觉是小问题，不改问题不大）。
2. 刚进入一个页面的时候默认为跳至底部应该会更好点，现在是默认跳至顶部。
3. 在缩放 80%（及以下）才存在的后缀信息框中的头像不能修改。

应该就这些了，希望大佬能够解决一下，谢谢啦。（或者可以教我一下怎么直接改 css 源码）

**Comment by Point-King** [comment]
我好像又发现一个小错误，就是教程里面的 获取焦点变化延时 的代码的变量名好像是错的。

```
window.cnblogsConfig = {
  title: {
    onblurTime: 1000,
  },
}
```

应该改成

```
window.cnblogsConfig = {
  title: {
    focusTime: 1000,
  },
}
```

**Comment by BNDong** [comment]
1. 点赞和点踩按钮在使用浏览器缩放时出现一上一下的情况修复了，更新最新版本，重新拷贝样式代码。
2. 默认跳至顶部，这个是个BUG，首次加载主题会根据当前页面位置自动设置跳至顶部还是底部，目前修复了，更新最新版本。
3. 后缀信息框中的头像不能修改，这个是新版本重构时候遗漏了一个点，新增加了一个配置 `articleSuffix.imgUrl` 来解决这个问题，更新最新版本。
4. 获取焦点变化延时本就是 `focusTime ` ，`onblurTime ` 是失去焦点变化延时，你应该是看差了。

**Comment by Point-King** [comment]
![](https://cdn.luogu.com.cn/upload/image_hosting/l7xev6zx.png)

我这里看教程 Document 里的的确是写错的？

不过还是谢谢大佬了。

**Comment by BNDong** [comment]
是示例错了，我更正下！😓

**Comment by Point-King** [comment]
辛苦了！
