### ISSUE TITLE
图片和代码显示有问题

### ISSUE THREAD

**Issue by Polaris-zhj** [BNDong/Cnblogs-Theme-SimpleMemory#242]
图片在后台编辑大小、位置后，保存查看文章时文章中的图片大小位置没有变化
代码大小在后台编辑时改动，在查看文章时也没有变化
望解答，谢谢。

**Comment by fatmanhappycode** [comment]
附议，图片改大小都没用了

**Comment by Polaris-zhj** [comment]
能在加载的一瞬间能看到图片大小位置的变化，加载完成后就变回原来的样子了，不知道什么原因

**Comment by BNDong** [comment]
之前自己加的样式有用，后来博客园自己加了个图片灯箱效果，为了不与主题的灯箱效果冲突，重新处理了img标签，所以会有样式丢失的情况。后续我再考虑怎么这个问题吧！

**Comment by Polaris-zhj** [comment]
v1.3.3的版本，没有出现这样的问题

**Comment by BNDong** [comment]
v2.0.3 修复了这个问题
