### ISSUE TITLE
单行代码块没有美化

### ISSUE THREAD

**Issue by DengSchoo** [BNDong/Cnblogs-Theme-SimpleMemory#244]
使用2.0.2版本之后，发现单行代码块没有被美化，检查元素之后发现标签还是md 默认`<code>`标签而不是`<span class="cnblogs_code">`标签。不知道是哪块的问题。哥你抽空康康，顺便解决一下。

**Comment by DengSchoo** [comment]
[Violation] Avoid using document.write().

**Comment by DengSchoo** [comment]
[Violation] Forced reflow while executing JavaScript took <N>ms

**Comment by DengSchoo** [comment]
刷新加载的一瞬间可以看到美化 然后就没有了 `<code>`标签没有被替换，但是我看你的博客就没有这个问题，好怪啊

**Comment by BNDong** [comment]
提供下示例地址，有时间我看下！

**Comment by DengSchoo** [comment]
> 提供下示例地址，有时间我看下！

https://www.cnblogs.com/DengSchoo/p/14727727.html
这个我文章最后是单行代码
使用的是md的``

**Comment by DengSchoo** [comment]
> 提供下示例地址，有时间我看下！

我不知道是哪的问题 查了很多地方 都没有找到 哥你抽空康康叭 感觉是个例 但是我前端知识不多 de不出来bug
现在我的解决方案是：采用多行代码或高亮替代单行代码

**Comment by DengSchoo** [comment]
> 提供下示例地址，有时间我看下！

我不知道是哪的问题 查了很多地方 都没有找到 哥你抽空康康叭 感觉是个例 但是我前端知识不多 de不出来bug
现在我的解决方案是：采用多行代码或高亮替代单行代码

**Comment by BNDong** [comment]
md 的行内代码样式匹配确实有问题，我也不确定时我改了样式还是博客园又调整了页面结构导致的。
下个版本我适配下，正常些吧，以后更新下就行，这个影响不大！

**Comment by BNDong** [comment]
md 的行内代码样式匹配确实有问题，我也不确定时我改了样式还是博客园又调整了页面结构导致的。
下个版本我适配下，正常些吧，以后更新下就行，这个影响不大！

**Comment by DengSchoo** [comment]
好的 感谢！

**Comment by DengSchoo** [comment]
另外，如果首页置顶的随笔字数过多的话会直接显示全文而不是摘要和阅读全文。演示地址：https://www.cnblogs.com/DengSchoo

**Comment by BNDong** [comment]
v2.0.3 修复了这个问题
