### ISSUE TITLE
markdown文档代码滚动条失效

### ISSUE THREAD

**Issue by ellenm9** [BNDong/Cnblogs-Theme-SimpleMemory#245]
markdown文档多次刷新后,代码长度超出文档显示后,滚动条不在显示,只显示代码复制按钮,无法向左滚动代码进行查看,目前测试
essayCodeHighlightingType: cnblogs/highlightjs/prettify 均存在上述问题 .

**Comment by BNDong** [comment]
以前都没出现过这个问题，升级版本试一试呢？

**Comment by ellenm9** [comment]
正解
