### ISSUE TITLE
2.0.3单行markdown样式问题

### ISSUE THREAD

**Issue by 303donatello** [BNDong/Cnblogs-Theme-SimpleMemory#249]
日间模式没有样式，夜间模式看上去是有样式的，2.0.3的版本，然后换了浏览器，应该不是缓存的问题导致样式没有加载出来。

**Comment by BNDong** [comment]
你更新下css，每次切版本最好都要更新css

**Comment by BNDong** [comment]
我在版本发布时候都会写明“更新基础样式“之类的文字，那就是有改动，留意下
