### ISSUE TITLE
你好，我安装配置后点开首页是空白的

### ISSUE THREAD

**Issue by EverydayLearning** [BNDong/Cnblogs-Theme-SimpleMemory#25]
博客链接：https://www.cnblogs.com/mangM/

**Comment by yinghualuowu** [comment]
没看见有什么问题，就是头像没加载出来

**Comment by EverydayLearning** [comment]
> 没看见有什么问题，就是头像没加载出来

是的，之前的问题解决了。现在的问题是头像加载不出来了

**Comment by yinghualuowu** [comment]
![image](https://user-images.githubusercontent.com/22371568/61021740-58854000-a3d5-11e9-9893-1f8dc84dbef5.png)
看报错，感觉这里
`GhUserName: "EverydayLearning"`
少了逗号。看看是不是这里错了

**Comment by EverydayLearning** [comment]
> ![image](https://user-images.githubusercontent.com/22371568/61021740-58854000-a3d5-11e9-9893-1f8dc84dbef5.png)
> 看报错，感觉这里
> `GhUserName: "EverydayLearning"`
> 少了逗号。看看是不是这里错了

ok了 谢谢啦
