### ISSUE TITLE
有没有办法把主页banner禁用掉

### ISSUE THREAD

**Issue by steinvenic** [BNDong/Cnblogs-Theme-SimpleMemory#252]
整体非常好，就是搜内容的话，需要多点一下，但这个问题可以自建一个浏览器搜索引擎，完美解决。

**Comment by steinvenic** [comment]
就是bannner图占据整个屏幕，太影响查看文章了，还要滑呀滑，个人感觉这个就有点花里胡哨了，求作者弄个开关

**Comment by BNDong** [comment]
设计上就是首页第一屏是大图，这个不会处理。有能力的可以自己修改源码。

主页banner上有快速跳转的按钮：
<img width="1400" alt="Snipaste_2021-07-07_09-49-56" src="https://user-images.githubusercontent.com/21150911/124688367-37468400-df09-11eb-94cc-d01f7de1f2cc.png">

**Comment by sky5454** [comment]
> 整体非常好，就是搜内容的话，需要多点一下，但这个问题可以自建一个浏览器搜索引擎，完美解决。

Ctrl+F 可以使用浏览器的页面搜索

**Comment by steinvenic** [comment]
> > 整体非常好，就是搜内容的话，需要多点一下，但这个问题可以自建一个浏览器搜索引擎，完美解决。
> 
> Ctrl+F 可以使用浏览器的页面搜索

这个仅限于搜索本页面

**Comment by sky5454** [comment]
> > > 整体非常好，就是搜内容的话，需要多点一下，但这个问题可以自建一个浏览器搜索引擎，完美解决。
> > 
> > 
> > Ctrl+F 可以使用浏览器的页面搜索
> 
> 这个仅限于搜索本页面

博客园是有搜索功能的
![image](https://user-images.githubusercontent.com/12370628/126855448-84289d56-af21-4443-a1fe-e9c31bdc2bd0.png)
