### ISSUE TITLE
为什么应用皮肤后，刷新博客页面空白？确定不是本地页面缓存问题

### ISSUE THREAD

**Issue by Ricardo-M-Li** [BNDong/Cnblogs-Theme-SimpleMemory#253]

**Comment by Ricardo-M-Li** [comment]
在侧边栏加入打印日志后，也没显示信息。

**Comment by BNDong** [comment]
确认下是否开启公告；是否有js权限！

**Comment by Ricardo-M-Li** [comment]
公告已开启，也有js权限。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月6日(星期二) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BNDong/Cnblogs-Theme-SimpleMemory] 为什么应用皮肤后，刷新博客页面空白？确定不是本地页面缓存问题 (#253)

**Comment by BNDong** [comment]
> 在侧边栏加入打印日志后，也没显示信息。

你console.log都跑不起来的话，更不可能执行主题文件了。应该是执行权限的问题！

**Comment by BNDong** [comment]
贴配置截图
