### ISSUE TITLE
关于 v2.0.5 右下角加入的返回主页

### ISSUE THREAD

**Issue by HRiver2** [BNDong/Cnblogs-Theme-SimpleMemory#255]
这个图标在第一次被触碰到时会显示直接显示字：

![](https://pic.imgdb.cn/item/60f3f5515132923bf85ba72f.jpg)

再触碰之后会显示图标

![](https://pic.imgdb.cn/item/60f3f5455132923bf85b66c8.jpg)

而且字的方向应当是横向，现在是竖向（

**Comment by BNDong** [comment]
更新样式

**Comment by HRiver2** [comment]
> 更新样式

但是现在到 v2.0.7 了好像还是没有变化的样子（
