### ISSUE TITLE
【建议】目录位置是否可以调整到左侧

### ISSUE THREAD

**Issue by Kin-Zhang** [BNDong/Cnblogs-Theme-SimpleMemory#256]
首先感谢作者们的贡献！真的超棒！🥰🥰（就是我发现太晚了）

然后，想问一下如题：目录位置是否可以调整到左侧

主要原因是我们的**阅读习惯一般都是目录在左侧** 😅，例如：PDF阅读，word导航窗口，等等等

然后自己尝试搜索了一下 content关键字也没看到代码块的调整部分（看js css html 比较菜 见谅🙏）

**Comment by BNDong** [comment]
因为左侧有侧边栏，文章目录再放到左侧感觉怪怪的，我再考虑下后期要不要调整！
[文章目录实现参考](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/blob/v2/src/components/articleDirectory/articleDirectory.js)

**Comment by Kin-Zhang** [comment]
感谢回复！

我觉得**保持现有** 仅将目录放置左边即可，类似于保持现在的侧边栏、右下角的东东（我觉得超棒！）

因为在阅读过程中，一般侧边栏是不会打开的，阅读中打开时，也会让文中渐黑，所以目录保持和文中一样渐黑即可。

放置在左侧的建议，确实是因为 **基本上阅读习惯一般都是目录在左侧**<br />(虽然我也看到过在右侧的博客，但是我自己都不太适应，主要是PDF，word，WPS，其余钉钉腾讯文档等各类主流阅读软件 已经让大家有习惯性左侧导航栏。)

不过这也仅是建议~ （要是后期调整了 就请@一下，超期待 (没错 就是看完代码... 发现还得寄存js hhh 太菜了😂 主要不是做前端的选手)）

最后再次表达 对作者这个开源项目的喜爱💖！超棒💖！ YYDS

**Comment by sky5454** [comment]
现在的目录没有自动展开  ，非常不便
1. 访客根本不知道有目录这个功能
2. 博客主人要自己手动点开目录

**Comment by Kin-Zhang** [comment]
> 现在的目录没有自动展开 ，非常不便
> 
> 1. 访客根本不知道有目录这个功能
> 2. 博客主人要自己手动点开目录

是自动展开的啊，我前几天开始用的这个主题，目录都是自动展开的

**Comment by sky5454** [comment]
> > 现在的目录没有自动展开 ，非常不便
> > 
> > 1. 访客根本不知道有目录这个功能
> > 2. 博客主人要自己手动点开目录
> 
> 是自动展开的啊，我前几天开始用的这个主题，目录都是自动展开的

哦哦，是我窗口没最大化

**Comment by Kin-Zhang** [comment]
可能感觉还是开个目录左右“可选”比较好

**Comment by BNDong** [comment]
v2.0.6 加了个配置，可以自己配置目录在左面还是右面

**Comment by Kin-Zhang** [comment]
大佬TQL！！！💖💖💖
