### ISSUE TITLE
那么问题来了

### ISSUE THREAD

**Issue by miaopan607** [BNDong/Cnblogs-Theme-SimpleMemory#257]
如何设置默认为夜间模式？
并且个人感觉夜间模式的代码块偏亮了一些

**Comment by miaopan607** [comment]
![image](https://user-images.githubusercontent.com/64201424/126241774-18a0247a-85cd-46df-826d-719676761d3e.png)

还有这个是什么意思啊

**Comment by Kin-Zhang** [comment]
> ![image](https://user-images.githubusercontent.com/64201424/126241774-18a0247a-85cd-46df-826d-719676761d3e.png)
> 
> 还有这个是什么意思啊

我也一直想问这个是啥 意思...

**Comment by BNDong** [comment]
现在没法默认夜间模式，倒是可以开启自动切换，然后将白天时间设置成1小时

**Comment by BNDong** [comment]
> > ![image](https://user-images.githubusercontent.com/64201424/126241774-18a0247a-85cd-46df-826d-719676761d3e.png)
> > 还有这个是什么意思啊
> 
> 我也一直想问这个是啥 意思...

这个是文章预计阅读时间范围，格式是[分钟:秒]

**Comment by sky5454** [comment]
> 如何设置默认为夜间模式？
> 并且个人感觉夜间模式的代码块偏亮了一些

可以巧妙地利用自动切换，把你不需要的时间设置为白天模式，其他时间设为夜间模式 
[switchDayNight - 日/夜间模式](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2/#/Docs/Customization/config?id=switchdaynight-%e6%97%a5%e5%a4%9c%e9%97%b4%e6%a8%a1%e5%bc%8f)

**Comment by BNDong** [comment]
v2.0.6 增加了强制夜间模式配置
