### ISSUE TITLE
【改进】span高亮在日夜切换时 无法自动

### ISSUE THREAD

**Issue by Kin-Zhang** [BNDong/Cnblogs-Theme-SimpleMemory#259]
首先感谢作者们的贡献！真的超棒！🥰🥰

这是我无意自己查了一种其他可以改变底色的高亮方式，感觉应该是主题代码里没有对其切换时做字体颜色不变处理

黄色是自动的 `<mark> </mark>`这种；浅蓝色是：`<span style="background-color: #CAECF4"> </span>`

现在的示意如下：

![image](https://user-images.githubusercontent.com/35365764/126744766-8812d21a-bde5-4516-8b73-0668f4db7aec.png)

**Comment by Kin-Zhang** [comment]
然后我自己好像想到一种暂时的替代解决方案，就是

```html
<span style="background-color: #CAECF4"><font color=black>这里是文字</font></span>
```

**Comment by sky5454** [comment]
> 然后我自己好像想到一种暂时的替代解决方案，就是
> 
> ```
> <span style="background-color: #CAECF4"><font color=black>这里是文字</font></span>
> ```

可以用 [filter](https://developer.mozilla.org/zh-CN/docs/Web/CSS/filter)

**Comment by Kin-Zhang** [comment]
> > 然后我自己好像想到一种暂时的替代解决方案，就是
> > ```
> > <span style="background-color: #CAECF4"><font color=black>这里是文字</font></span>
> > ```
> 
> 可以用 [filter](https://developer.mozilla.org/zh-CN/docs/Web/CSS/filter)

filter有写在源码里吗？能直接这样 `<span style="background-color: #CAECF4"><filter>这里是文字</filter></span>`吗？

**Comment by sky5454** [comment]
> > > 然后我自己好像想到一种暂时的替代解决方案，就是
> > > ```
> > > <span style="background-color: #CAECF4"><font color=black>这里是文字</font></span>
> > > ```
> > 
> > 
> > 可以用 [filter](https://developer.mozilla.org/zh-CN/docs/Web/CSS/filter)
> 
> filter有写在源码里吗？能直接这样 `<span style="background-color: #CAECF4"><filter>这里是文字</filter></span>`吗？

可以写在 页尾 HTML 覆盖原来的，filter 看 MDN 的使用说明

**Comment by BNDong** [comment]
这种自定义的背景色目前没有太好的办法处理

**Comment by BNDong** [comment]
v2.0.6 增加强制夜间模式配置
