### ISSUE TITLE
大哥，这个怎么用啊

### ISSUE THREAD

**Issue by daiweikuan** [BNDong/Cnblogs-Theme-SimpleMemory#26]

**Comment by sky5454** [comment]
搜索博客园自定义皮肤，遇事请勿直接伸手

**Comment by BNDong** [comment]
请参考[文档](http://doc.dbnuo.org/cnblogs-theme-docs/v1.1.0/#/Docs/GettingStarted/install)配置使用！

有不详细和不理解的地方可以反馈给我！
