### ISSUE TITLE
使用了Highlighting 插件后出现代码不能换行的情况

### ISSUE THREAD

**Issue by jcmik** [BNDong/Cnblogs-Theme-SimpleMemory#260]
如图，代码不换行很难受。但没看到别人出现类似的问题，我的设置也是按照说明文档来的。就感觉很奇怪[示例博客](https://www.cnblogs.com/jfchen/p/15069886.html)
![](https://i.loli.net/2021/07/28/AC4zkLjmwGD8ry2.jpg)
![](https://i.loli.net/2021/07/28/j41JZ2K9swMxSgY.jpg)

**Comment by BNDong** [comment]
<img width="706" alt="Snipaste_2021-07-29_17-26-02" src="https://user-images.githubusercontent.com/21150911/127467663-7ef628cb-6790-48d3-a8c8-472a64bbf02e.png">

很奇怪，我用你页面源码复现不出来，能给个文章源码，或私下账户信息么

**Comment by jcmik** [comment]
> <img alt="Snipaste_2021-07-29_17-26-02" width="706" src="https://user-images.githubusercontent.com/21150911/127467663-7ef628cb-6790-48d3-a8c8-472a64bbf02e.png">
> 
> 很奇怪，我用你页面源码复现不出来，能给个文章源码，或私下账户信息么

打扰了，突然发现是我自己把博客园默认的行号给勾上去造成的结果，去除掉之后就恢复正常了😥
