### ISSUE TITLE
右侧目录定位不准确

### ISSUE THREAD

**Issue by gaotianhao1994** [BNDong/Cnblogs-Theme-SimpleMemory#266]
问题描述：
- 右侧目录会随文章移动而标识出当前所在的位置。
- 但是部分文章定位不准确

问题重现：
1. 使用chrome或火狐浏览器
2. 打开https://www.cnblogs.com/gaotianhao/p/15126954.html
3. 点击右侧目录，如：**4.2 Django使用jinja2模板**
4. 右侧目录会定位到 **jinja2自定义过滤器**

**Comment by BNDong** [comment]
滚动定位使用的 bootstrap 插件实现的，目前没有好的优化方案！
