### ISSUE TITLE
关于文章标题打字机效果开关，导航遮挡文章内容问题

### ISSUE THREAD

**Issue by chaomings** [BNDong/Cnblogs-Theme-SimpleMemory#267]
当显示器到某种宽度的时候导航会遮挡文章的一部分内容。
文章标题需要立即展示，打字机效果是否可以开关，简约掉
![image](https://user-images.githubusercontent.com/25077986/129316372-bc961a5a-6341-4dd3-80cc-1f629940c2ff.png)
源页面：https://www.cnblogs.com/chaomings/articles/15137119.html

**Comment by BNDong** [comment]
文章页banner高度根据文章标题自适应，最低高度40vh

文章目录和标题动效等新版加配置！
