### ISSUE TITLE
使用最新版 2.0.6 首页刷新没有背景图了

### ISSUE THREAD

**Issue by 199457** [BNDong/Cnblogs-Theme-SimpleMemory#269]
如题，按照配置文档步骤操作完成，第一次打开页面是正常的，刷新头部背景图，菜单栏就消失了。
error重现地址：https://www.cnblogs.com/shenshou

**Comment by BNDong** [comment]
我发现问题了，官方又又又又又调整基础HTML结构了，我处理下，下版修复
