### ISSUE TITLE
怎样去掉页面底部footer.png

### ISSUE THREAD

**Issue by 1963609863** [BNDong/Cnblogs-Theme-SimpleMemory#27]

**Comment by BNDong** [comment]
* v1.0.0版本：需要修改CSS样式```.footer-image```，隐藏该样式即可！
* v1.1.*版本：关于footer的样式文件 [src/style/footer.css](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/blob/master/src/style/footer.css)

PS：v1.0.0版本和v1.1.*版本的底部图片不一样（v1.1.*版本更适用一些），你可以看看v1.1.4版本底部图片，如果接受，直接升级版本就成！
