### ISSUE TITLE
应用主题之后的问题

### ISSUE THREAD

**Issue by TotoWang-hhh** [BNDong/Cnblogs-Theme-SimpleMemory#271]
- 折叠的代码块无法展开
- 访问其他网页时，博客标签页标题会变成![image](https://user-images.githubusercontent.com/67090055/130898130-fb40c02d-dc65-4035-b153-e71d67bb2363.png)个人不太喜欢这种设计，请问如何关闭？

**Comment by BNDong** [comment]
1. 折叠的代码块可以展开
2. 麻烦仔细阅读下[文档](https://www.dbnuo.com/Cnblogs-Theme-SimpleMemory/docs/v2/#/Docs/Customization/config?id=onblur-%e5%a4%b1%e5%8e%bb%e7%84%a6%e7%82%b9%e6%a0%87%e7%ad%be%e6%96%87%e5%ad%97)
