### ISSUE TITLE
优化建议：文章目录是否可以增加左右滚动条

### ISSUE THREAD

**Issue by gaotianhao1994** [BNDong/Cnblogs-Theme-SimpleMemory#272]
- 文章自动生成的目录，拥有上下滚动条
- 但是当文章标题长度超出范围后，并没有左右滚动条。
- 如下：不能看到完整的目录
![image](https://user-images.githubusercontent.com/40493450/130919826-259450cb-2efd-4944-9d4e-c2b6305d0afa.png)

**Comment by BNDong** [comment]
我考虑下，后期不行加个配置

**Comment by gaotianhao1994** [comment]
嗯，只是一个建议，全看大佬个人想法。

**Comment by BNDong** [comment]
v2.0.8 增加配置 `articleDirectory.autoWidthScroll` 用以处理该问题

**Comment by gaotianhao1994** [comment]
赞一个~
