### ISSUE TITLE
你Close了我的issue，但我的issue还没解决！

### ISSUE THREAD

**Issue by TotoWang-hhh** [BNDong/Cnblogs-Theme-SimpleMemory#273]
我之前就删掉了有关“当页面失去焦点”的两行代码（我fork了本存储库在js里删掉了相关代码，并且更改了我博客里面的文件链接），可是这么做并没有效果

**Comment by TotoWang-hhh** [comment]
这点可能我的做法有点太硬核了，不过我觉得这样应该可行

**Comment by BNDong** [comment]
找到[src/components/common/comAfter.js](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/blob/v2/src/components/common/comAfter.js)文件

注释#9、#68行代码

运行命令`./buid.sh`，构建新的代码后，提交代码至你的仓库

博客园配置加载文件版本为你提交对应 commit 的全哈希值，保存配置刷新页面就会生效！

**Comment by BNTang** [comment]
你提了就一定要给你解决？

**Comment by TotoWang-hhh** [comment]
> 
> 
> 你提了就一定要给你解决？

不是一定要解决的问题，话还没说完就把issue关了，还没见过有人这么做，于是我只能重写一个issue，我这么写标题就是为了让主题作者知道时我——之前issue被关掉的那个人
