### ISSUE TITLE
Docs全部404了

### ISSUE THREAD

**Issue by fxyQAQ** [BNDong/Cnblogs-Theme-SimpleMemory#274]

**Comment by BNDong** [comment]
[地址一](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2)　

[地址二](https://www.dbnuo.com/Cnblogs-Theme-SimpleMemory/docs/v2/)

试一试呢？

**Comment by fxyQAQ** [comment]
好了，感谢！
