### ISSUE TITLE
请问我这chrome code高亮变成这样了 知道啥原因吗？

### ISSUE THREAD

**Issue by daemon365** [BNDong/Cnblogs-Theme-SimpleMemory#278]
![image](https://user-images.githubusercontent.com/57396775/132797190-f690559d-3f13-47d3-a013-aa35bbabe69e.png)

**Comment by daemon365** [comment]
![image](https://user-images.githubusercontent.com/57396775/132797297-e4fcbb0f-cd96-43c1-a6bd-cfd9d412983c.png)

**Comment by BNDong** [comment]
我现在引的是测试库资源，有缓存，清一下试一试

**Comment by daemon365** [comment]
![image](https://user-images.githubusercontent.com/57396775/133012939-70cca672-ad7e-491f-a22b-0d9ca86cd986.png)
还是不行

**Comment by BNDong** [comment]
无法复现你的情况，请问你是怎么清缓存的？

**Comment by daemon365** [comment]
浏览器清除缓存 所有时间 基本高级 都清除了

**Comment by BNDong** [comment]
无法复现这个问题，麻烦看下控制台输出，有无报错

**Comment by daemon365** [comment]
![image](https://user-images.githubusercontent.com/57396775/133355830-1a0b4490-ca38-4721-ad83-66c880442fac.png)

**Comment by sky5454** [comment]
博客地址都不肯放一下，你叫人家如何帮你

**Comment by daemon365** [comment]
解决了 吧本地的这个 source code pro 字体卸载就好了    https://www.v2ex.com/t/698187
