### ISSUE TITLE
请问为什么markdown引用要用<h6>能改成> 吗

### ISSUE THREAD

**Issue by blknemo** [BNDong/Cnblogs-Theme-SimpleMemory#28]

**Comment by BNDong** [comment]
markdown 的引用就是 ```>```  [文档链接](http://doc.dbnuo.org/cnblogs-theme-docs/v1.1.0/#/Docs/GettingStarted/writtenForm)

|**类型**|**TinyMCE**|**Markdown**|
|:-----:|:-----:|:-----:|
|**一级标题**|```<h1>```|```#```|
|**二级标题**|```<h2>```|```##```|
|**三级标题**|```<h3>```|```###```|
|**引用文字**|```引用 or <h6>```|```>```|
|**行内代码**|```行内代码```| ```|

**Comment by blknemo** [comment]
可能是我想错了，可是用>这个引用，字超出了




------------------ 原始邮件 ------------------
发件人: "BNDong"<notifications@github.com>; 
发送时间: 2019年7月24日(星期三) 晚上9:32
收件人: "BNDong/Cnblogs-Theme-SimpleMemory"<Cnblogs-Theme-SimpleMemory@noreply.github.com>; 
抄送: "小李"<344593119@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [BNDong/Cnblogs-Theme-SimpleMemory] 请问为什么markdown引用要用<h6>能改成> 吗 (#28)




markdown 的引用就是 >  文档链接
    类型 TinyMCE Markdown 
    一级标题 <h1> # 
  二级标题 <h2> ## 
  三级标题 <h3> ### 
  引用文字 引用 or <h6> > 
  行内代码 行内代码 ```

**Comment by BNDong** [comment]
本人测试版本v1.1.4，测试汉字长度350，未发现问题！

是否可以提供所使用的版本和示例文章，以便于我复现该问题。如果有问题我会在后续版本中修复！
