### ISSUE TITLE
建议 articleDirectory 的默认值改为 700

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#281]
```javascript
      articleDirectory: {
        minBodyWeight: 700,
      },
```

因为 1080P 下 Windows 自带的左右分屏宽度是 706.8，把最小宽度设置为 700，刚好手机不会显示目录，而 PC 端分屏可以显示目录，效果非常好 
![image](https://user-images.githubusercontent.com/12370628/133917568-d619bde7-2100-44de-8528-600abfe03272.png)
Windows11/10/8 分屏通用

**Comment by BNDong** [comment]
700有点小，文章目录的首要原则：`不遮挡内容`。还是让使用者自己配置吧，这个没法作为默认值
