### ISSUE TITLE
关于2.0.8的代码高亮问题

### ISSUE THREAD

**Issue by FeiFeinb** [BNDong/Cnblogs-Theme-SimpleMemory#282]
对于typora写的代码，由于代码块的语法是```，因此有些代码块并不能被hljs所识别，也就是说有些代码块将失去高亮效果，希望能优化一下hljs对于不显式指定<pre><code class="language-plaintext">...</code></pre>时的检测。还有一点是想问一下怎么使用默认cnblogs的高亮，然后将字体切换为consolas，cnblogs的字体太不好看了

**Comment by wangyang0210** [comment]
高亮问题，建议升级到最新版本；
https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/

字体切换的话，只需要css引入对应的字体文件，全局使用即可；
