### ISSUE TITLE
评论区分页样式加载有问题【希望该主题越来越好】

### ISSUE THREAD

**Issue by BNTang** [BNDong/Cnblogs-Theme-SimpleMemory#283]
![测试](https://user-images.githubusercontent.com/78400939/134458359-d9246a7a-6ff6-423d-9c2e-779f42c8f85d.gif)

**Comment by zhiyiYo** [comment]
在 comment.js 的 `main()` 函数后面加上这一段代码，这样每当点击排序按钮且收到了服务器响应的评论数据后就能重新渲染评论区的头像和样式：
```javascript
$(document).ajaxSuccess(function (event, xhr, settings) {
    if (settings.url.includes("GetComments.aspx")) {
        setComment();
    }
});
```
可以在我这篇博客的评论区点击排序按钮查看效果：https://www.cnblogs.com/zhiyiYo/p/14877952.html

**Comment by wangyang0210** [comment]
最新版本已经FIX
