### ISSUE TITLE
banner切换动效和鼠标动效无效。

### ISSUE THREAD

**Issue by D06F6E67** [BNDong/Cnblogs-Theme-SimpleMemory#284]
background: { // 背景
        enable: true,
      },
      mouse: { // 鼠标
        enable: true,
      },
      bannerImages: { // banner自动切换
        enable: true,
        options: {
          itemNum: 5, // 图片拆分成几列
          current: 0, // 初始图片的下标，如果为负数则为随机
          sort: 1, // 1 代表每次向下加载一个图片，-1 代表每次向上加载一个图片
          time: 3000 // 每次切换间隔时间，单位：毫秒
        },
      },

这里背景动效是正常的，鼠标和banner自动切换没有效果

**Comment by wddfaith** [comment]
老哥解决了没，我也是这个问题

**Comment by D06F6E67** [comment]
没，之后就没时间看那块的东西了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BNDong/Cnblogs-Theme-SimpleMemory"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 晚上10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BNDong/Cnblogs-Theme-SimpleMemory] banner切换动效和鼠标动效无效。 (#284)





 
老哥解决了没，我也是这个问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
