### ISSUE TITLE
文章页标题动效无法关闭

### ISSUE THREAD

**Issue by longweiqiang** [BNDong/Cnblogs-Theme-SimpleMemory#288]
articleTitle.enable设置为false，依然有标题动效
![image](https://user-images.githubusercontent.com/22344864/136781718-b10362c5-d0f2-4c55-a0cf-2ac7c9f67e47.png)

**Comment by BNTang** [comment]
你到是给个你博客错误的链接进行参考呐

**Comment by longweiqiang** [comment]
> 你到是给个你博客错误的链接进行参考呐

https://www.cnblogs.com/longweiqiang/p/15262319.html
