### ISSUE TITLE
为什么新版本换新的页脚了，感觉没有之前的好看哇

### ISSUE THREAD

**Issue by xiaowangtongxue0110** [BNDong/Cnblogs-Theme-SimpleMemory#29]
**还有语法的话
Posted by  及下面的标签
具体是怎么书写的格式啊？**

**Comment by BNDong** [comment]
1. 之前的页脚太偏向于二次元，有很多人并不是能很好的接受这种风格（我接到了很多私信，问怎么更换页脚），所以在新版本中更换了样式，使样式适用人群更广泛一些！

2. Posted by 和标签这个是自动设置的，这个功能是在v1.1.3版本中增加的，如果想使用，请更新到最新版本。
