### ISSUE TITLE
 引用内容样式问题，原因就是设置成了块级元素导致的

### ISSUE THREAD

**Issue by BNTang** [BNDong/Cnblogs-Theme-SimpleMemory#290]
![image](https://user-images.githubusercontent.com/78400939/137657449-0a3dde44-4b07-4eb0-b648-356c6d0bbb38.png)

**Comment by BNTang** [comment]
BUG文章链接：https://www.cnblogs.com/BNTang/articles/15417204.html

**Comment by BNDong** [comment]
下一版本优化
