### ISSUE TITLE
可否为v2增加标题渲染

### ISSUE THREAD

**Issue by ToryXie** [BNDong/Cnblogs-Theme-SimpleMemory#291]
正在使用v2，非常喜欢新的改动，有了更多自定义项目。同时也很喜欢v1.3.4的标题渲染与目录非激活时折叠和半透明样式的渲染，使较长文章阅读起来不容易枯燥。非常感谢作者大大。 💖

**Comment by BNDong** [comment]
那个标题结构还蛮复杂的，当初移除了也是考虑适配性不太好，后续应该不会加回来了，之前的代码也能复用，感兴趣可以自己尝试一下。
目录现在超长会自动开启滚动，取消折叠是因为用户不能直观看到文章的整体大纲，所以就换了其他方案来处理
