### ISSUE TITLE
首页头图向下移位的问题

### ISSUE THREAD

**Issue by LouisLiuNova** [BNDong/Cnblogs-Theme-SimpleMemory#294]
按照正确方法部署代码后，出现了首页图片向下移位遮挡了文章标题的情况。
使用Edge，Chrome浏览器均稳定复现。演示网站亦出现上述情况。
不确定是feature还是bug。
复现情况如下：
[![5oZgMV.png](https://z3.ax1x.com/2021/10/26/5oZgMV.png)](https://imgtu.com/i/5oZgMV)
[![5oZ6x0.png](https://z3.ax1x.com/2021/10/26/5oZ6x0.png)](https://imgtu.com/i/5oZ6x0)

**Comment by BNDong** [comment]
暂时无法复现这个问题

**Comment by LouisLiuNova** [comment]
> 

在Edge和Chrome下的Private模式中没有此问题，初步推断为extension的问题，正在排查中。
