### ISSUE TITLE
图标问题

### ISSUE THREAD

**Issue by GZYZG** [BNDong/Cnblogs-Theme-SimpleMemory#295]
请问能否支持通过url设置icon，例如[自定义菜单导航](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2/#/Docs/Customization/config?id=navlist-%e8%8f%9c%e5%8d%95%e5%af%bc%e8%88%aa)时传入icon的url，而不是阿里巴巴矢量图标库中的地址

**Comment by BNDong** [comment]
url设置图标可能会存在样式适配的问题，我会留意这个问题，后续再决定是否调整。
