### ISSUE TITLE
:bug:，代码框里面的代码排版问题

### ISSUE THREAD

**Issue by BNTang** [BNDong/Cnblogs-Theme-SimpleMemory#297]
![image](https://user-images.githubusercontent.com/78400939/142519441-8d248257-96c5-4c95-aeb3-032b019b5075.png)
错误案例：https://www.cnblogs.com/BNTang/articles/15570846.html

**Comment by hopeko** [comment]
我的也是，代码排版今天全部失效了。是不是负责代码排版的css的链接失效了？

**Comment by Zioyi** [comment]
我也遇到了，需要将```go```改成```Go```才会生效

**Comment by hopeko** [comment]
> 我也遇到了，需要将`go`改成`Go`才会生效

什么意思，怎么改？

**Comment by HRiver2** [comment]
同，我的也失效了

**Comment by HRiver2** [comment]
> 同，我的也失效了

我常用的是 `C++`，之前我代码块的高亮标识都是 `cpp`，试了一下改成 `Cpp` 才能正常渲染。

**Comment by BNTang** [comment]
当然渲染行号的样式也有问题了

**Comment by BNTang** [comment]
> 我的也是，代码排版今天全部失效了。是不是负责代码排版的css的链接失效了？

发个链接给大家看看你改为Go的代码样式

**Comment by Zioyi** [comment]
![image](https://user-images.githubusercontent.com/23010380/142592695-5a9a131c-302b-439d-843a-f26395f27bbe.png)
注释这块代码，使用默认主题可以的；效果：https://www.cnblogs.com/Zioyi/p/15547465.html

另一种是 将原来在markdown 代码块中用大写来写：
![image](https://user-images.githubusercontent.com/23010380/142597573-261c8cb8-6619-478d-829e-d00784a99f95.png)

**Comment by hopeko** [comment]
还真是，首字母改成大写就行了，这是什么操作。

**Comment by qq305021726** [comment]
什么时候能修复，换个版本可以吗

**Comment by Kin-Zhang** [comment]
我的也是！预览的时候没啥问题，发布后发现的问题 一开始还以为自己写错了
![image](https://user-images.githubusercontent.com/35365764/142797189-acec80db-c7a8-48f0-b5af-8fe87abc8f9f.png)

**Comment by BNDong** [comment]
博客园修改样式导致的，官方将样式没有写到主题默认样式文件里，直接写到了页面源代码里，优先级比主题的高，直接给盖了。解决方案：

一、目前版本和之前版本可以增加css样式解决：
```
.hljs-engine pre[class*='language-'] {white-space: pre !important;}
```

二、最新版会直接修复这个问题
