### ISSUE TITLE
文章后缀本文作者和链接不显示

### ISSUE THREAD

**Issue by jxingh** [BNDong/Cnblogs-Theme-SimpleMemory#299]
博主，你好！附上图片及链接：
![image](https://user-images.githubusercontent.com/57865505/143599039-42bf858a-1423-49ad-b1aa-2206a05a75d3.png)
https://www.cnblogs.com/jxingh/p/15598210.html

**Comment by BNDong** [comment]
https://www.dbnuo.com/Cnblogs-Theme-SimpleMemory/docs/v2/#/Docs/Customization/reprinted
