### ISSUE TITLE
控件显示必须开启公告

### ISSUE THREAD

**Issue by fancunwei** [BNDong/Cnblogs-Theme-SimpleMemory#3]
你好，你提供的皮肤非常好看，我在试用过程中，踩了一些坑。css也调了一大会，
最终发现：
控件显示的公告必须开!
控件显示的公告必须开!
控件显示的公告必须开！
然后就完美了。
不知道其他人是否遇到我的类似问题。

**Comment by BNDong** [comment]
额，我在说明里面写了啊，菜单显示不全的去选项开启对应显示就好了！也有网络造成的可能，定时器检测博客园数据进行设置，源数据没有的话，30S后清空全部定时器就不会再设置了！

**Comment by fancunwei** [comment]
我的意思是我本来不需要开公告的，但是不开公告，用你的皮肤后，全页面灰屏。开了公告就好了，我担心别人也遇到，就特别提了下，太喜欢你提供的皮肤了，大赞！

**Comment by BNDong** [comment]
这问题我还没发现，感谢提醒，今天我更新了代码，我测试一下，要是发现问题直接修复了。
