### ISSUE TITLE
建议（代码框、网络）

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#30]
1. 代码不支持一键复制  
2. 在 Linux 版的火狐浏览器上，浏览代码框内的代码时，发现滚动很慢，但不是卡（Chrome 没有那么慢）   
3. 偶尔会还是无法加载(控制台 `来自“https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v1.1.2/jquery.js”的资源已被阻止，因为 MIME 类型（“text/plain”）不匹配（X-Content-Type-Options: nosniff）。` 404)  
> 建议 JQ 使用其他 CDN 源的

**Comment by sky5454** [comment]
另外建议添加移动设备默认设置为不加载动态特效

**Comment by BNDong** [comment]
1. 博客园原有功能就不是一键复制，我并没有修改原有功能，只是调整了样式。这块也许以后会处理！
2. 你是指拖动滚动条很慢还是正常滚动慢？滚动条是使用插件美化动，我以后会尝试修复它。
3. 这个问题已被发现并且在v1.1.4版本中修复了。请更新版本。（JQuery 使用的是博客园官方的，这个加载本身就不应该存在的！）
4. 目前动态特效在移动设备上的显示已经做了CSS层面的限制，但是在JS中没有做处理，这块以后可能会优化下！

**Comment by sky5454** [comment]
1. 是博客园原有功能，功能是点击后变成文本框并默认全选，默认主题里这个功能用的js是`https://www.cnblogs.com/bundles/blog-common.js` 搜索`copyCnblogsCode`就能找到这个函数  
附上一个用了默认主题的帖子 https://www.cnblogs.com/afan-1999/p/11259007.html
2. 只是代码框内`正常滚动`慢
3. 我昨天改用了 1.1.4 版本，但是刷新了很多次缓存，现在依然加载了 1.1.2 版本的(偶尔还有JQ错误，其他没有问题)。这个应该不是博客园没有刷新的问题，因为我改了 html 代码后能在控制台看到。
 ```html
<script src="https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v1.1.4/src/script/simpleMemory.min.js"></script>
```

**Comment by sky5454** [comment]
其实代码框问题应该尽快搞定，因为现在这个主题虽然很好，但是复制代码时会连着行号一起复制下来，如果手动去掉行号是很麻烦的

**Comment by BNDong** [comment]
1. 博客园这个原有的代码复制功能还是可以正常使用的，就是点击后变成文本框并默认全选，我只是更换了复制图标的样式，其它没动，你可以看下我的[博客](https://bndong.cnblogs.com)，复制功能并没有问题。你描述的问题，我并没有复现出来，这点我很头痛，我添加了带行号的代码，点击复制按钮时候并没有复制行号！

我需要你提供博客地址、相关文章、文章使用的编辑器，以便于我复现问题！

2. 正常滚动慢我感觉是浏览器的问题，这个等我使用该浏览器测试一下再确定。

3. 关于版本的切换我更新了文档：[链接](http://doc.dbnuo.org/cnblogs-theme-docs/v1.1.0/#/Docs/GettingStarted/versionSwitch)，你参考一下，如果配置没问题是绝对不会还是加载1.1.2版本的，因为代码生成的引入文件路径全部都会改变！

**Comment by sky5454** [comment]
[我的博客](https://yucloud.cnblogs.com)  
文章编辑器为 `TinyMCE(推荐)`  
有问题的相关文章
- [1-折叠式(https://www.cnblogs.com/yucloud/p/10943215.html)
- [2-测试](https://www.cnblogs.com/yucloud/p/6118934.html)
我一般用的都是`插入代码(推荐)`即`div.cnblogs_code`那一个  
当然有的也用了 旧版的`插入代码` 即 `div.cnblogs_Highlighter`那个，
我在第二个文章里放了测试

<br>
你的博客以及 用SimpleMemory带不带自定义js的都有复制代码功能，就我没有emmm....


2. 可能是 Firefox Linux 版的 bug，因为我在[百度语音API文档官网](https://ai.baidu.com/docs#/ASR-Android-SDK/top)也复现了，同样的Chrome Linux没那么慢    
3. 我明天测试一下

**Comment by BNDong** [comment]
1. 博客园对少量代码、文字和部分语言是不显示复制按钮的，所以这不算是一个BUG。目前确认了折叠代码复制按钮丢失的问题，你的这个问题我会用代码处理的，后续版本会修复这个问题！

2. 既然是浏览器的问题，这属于兼容性问题了，短时间内我不会尝试解决它！

3. 我看了你的博客设置代码，我真不知道说啥了，你的配置是这样的：
```javascript
    window.cnblogsConfig = {
        GhVersions    : 'v1.1.4',
        blogUser      : "YuCloud", 
        blogAvatar    : "https://xxxx.png",
        blogStartDate : "1979-01-01", 
    }

    window.cnblogsConfig = {
    consoleList: [
         ['YuCloud CNBlogs', 'https://yucloud.cnblogs.com'],
         ['YuCloud GitHub', 'https://github.com/sky5454']
    ]
}

   window.cnblogsConfig = {
    bottomBlogroll: [ 
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud']
    ]
}

window.cnblogsConfig = {
    essaySuffix: {
             aboutHtml    : '热爱技术，喜欢钻研', 
             supportHtml  : '觉得文章对你有帮助，可以点一下【推荐】，另外热烈欢迎：留言探论' 
    }
}
```

```cnblogsConfig```是```window```对象上的一个属性，```window.cnblogsConfig =```是将属性赋值，新的赋值会替换旧的值，所以你这段代码最终生效的只有：

```javascript
   window.cnblogsConfig = {
    bottomBlogroll: [ 
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud']
    ]
```
其它配置都走的默认配置，鸡蛋请放到一个篮子里面，正确的配置应该是这样的：

```javascript
window.cnblogsConfig = {
    GhVersions: 'v1.1.4',
    blogUser: "YuCloud",
    blogAvatar: "https://xxxx.png",
    blogStartDate: "1979-01-01",
    consoleList: [
        ['YuCloud CNBlogs', 'https://yucloud.cnblogs.com'],
        ['YuCloud GitHub', 'https://github.com/sky5454']
    ],
    bottomBlogroll: [
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud'],
        ["申请坑位", 'https://msg.cnblogs.com/send/yucloud']
    ],
    essaySuffix: {
        aboutHtml: '热爱技术，喜欢钻研',
        supportHtml: '觉得文章对你有帮助，可以点一下【推荐】，另外热烈欢迎：留言探论'
    }
};
```

OMG！是我文档写的有歧义么？！！！我没想到这个还需要解释😱😱😱😱

**Comment by sky5454** [comment]
不好意思...傻了，毕竟就写过一次js，见谅。另外还有个bug，是皮肤的。   
编辑器里的效果：  
![image](https://user-images.githubusercontent.com/12370628/62010643-0481a600-b1a0-11e9-9e36-64d26756a56b.png)  
当代码里出现内嵌元素时，博客园原版皮肤是可以解析的，但是现在这个皮肤会直接显示出来  
![image](https://user-images.githubusercontent.com/12370628/62010657-3135bd80-b1a0-11e9-9c07-fba1462d5864.png)  
> [地址](https://www.cnblogs.com/yucloud/p/6118934.html)

**Comment by wzdnzd** [comment]
@BNDong 请教个问题
1）我发现文章编辑器使用markdown时是不会有代码复制按钮的，除了换编辑器，有其他解决方法吗？
2）有方法去掉代码框的滚动条让代码全部显示吗？

[博客地址](https://www.cnblogs.com/betabear/p/10807597.html)

谢谢

**Comment by BNDong** [comment]
统一回复了啊！
1. 关于代码复制按钮和解析错误这个问题下个版本v1.1.5解决。

2. 如果想让代码框全部显示，需要修改CSS限制高度的相关样式！

3. 普通模式下的```<h1>```解析目前没有发现问题，请检查自己书写格式。

4. 图床之所以选择github就是想让这个项目的相关文件放到一个库中，这样便于维护，也便于fork项目的人修改和自定义。

5. 之所以选择这个CDN主要是因为，它可以直接CDN Github 里的文件并具有版本控制和压缩功能，并且在国内拥有节点。

6. 其它功能的完善和样式的优化，在以后的版本中根据优先级慢慢完善，如果你们有建议可以先提出来，我会记录。

> 最近时间比较紧，我会优先解决影响使用的功能！感谢大家的支持！！

**Comment by sky5454** [comment]
3. 如果全文没有`<h1>`，比如只有`<h2>`，那么目录生成后全部都是 `0/1`  
如 https://www.cnblogs.com/yucloud/p/10904129.html

**Comment by sky5454** [comment]
发现新问题： 默认出处那里会显示当前地址，但是连 `#`后面的内容也匹配进去了。如图  

![image](https://user-images.githubusercontent.com/12370628/62388047-e2689900-b58e-11e9-8957-434b62a1fea6.png)


链接：https://www.cnblogs.com/yucloud/p/11291607.html#tomcat-%E7%9A%84-rundebug-%E9%85%8D%E7%BD%AE

**Comment by BNDong** [comment]
谢谢反馈，开始着手处理问题。bug会在下个版本得到修复，功能的优化和完善下个版本会处理部分！
