### ISSUE TITLE
首页无法显示文章

### ISSUE THREAD

**Issue by codegitz** [BNDong/Cnblogs-Theme-SimpleMemory#300]
小伙伴们好！
       无意中浏览到Cnblogs-Theme-SimpleMemory，发现这个主题简洁美观，于是最近我更换博客的皮肤为Cnblogs-Theme-SimpleMemory，但是更换之后首页的文章显示不出来，我是按照文档配置的css和js，检查了好几次没发现那里配置有误，希望小伙伴们能指点一下
> 我使用的版本为2.0.8，参考的配置文档为https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2
![image](https://user-images.githubusercontent.com/29326146/143730465-1af774dc-4836-40b1-9224-67b5631a5937.png)

**Comment by BNDong** [comment]
不使用主题能显示文章？

**Comment by xiaotian1339** [comment]
我的也不显示，按照文档一步步走的，您的解决了吗？

**Comment by baiyanjie** [comment]
> 我的也不显示，按照文档一步步走的，您的解决了吗？

请问解决了吗，我是随笔可以，但写文章不显示

**Comment by wangyang0210** [comment]
这个要自己到博客园配置下，或者发博文的时候勾选允许文章展示到首页；博客园默认不展示到首页；

![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/36377605/83b83936-556b-4737-8e82-5793a7693281)

![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/36377605/98995b9b-7f53-47a0-82cc-12973df7d2e3)

**Comment by baiyanjie** [comment]
> 这个要自己到博客园配置下，或者发博文的时候勾选允许文章展示到首页；博客园默认不展示到首页；
> 
> ![image](https://user-images.githubusercontent.com/36377605/248852613-83b83936-556b-4737-8e82-5793a7693281.png)
> 
> ![image](https://user-images.githubusercontent.com/36377605/248852801-98995b9b-7f53-47a0-82cc-12973df7d2e3.png)

ok，谢谢
