### ISSUE TITLE
通过JS代码动态添加的body元素，在切换到夜间模式不会被遮罩

### ISSUE THREAD

**Issue by BNTang** [BNDong/Cnblogs-Theme-SimpleMemory#302]
![image](https://user-images.githubusercontent.com/78400939/144412471-b6eb0bf6-411e-4e1f-86d8-2e48f5d5857b.png)
切换到了夜间模式没遮罩效果

**Comment by BNTang** [comment]
测试地址：https://www.cnblogs.com/BNTang/p/15627457.html

**Comment by wangyang0210** [comment]
哈哈哈哈,因为那个白色是你图片的底色,你这个图片的背景不是透明的而是白的;

**Comment by BNTang** [comment]
> 哈哈哈哈,因为那个白色是你图片的底色,你这个图片的背景不是透明的而是白的;

意思是自己要在回调函数当中设置图片的透明度咯？

**Comment by wangyang0210** [comment]
> > 哈哈哈哈,因为那个白色是你图片的底色,你这个图片的背景不是透明的而是白的;
> 
> 意思是自己要在回调函数当中设置图片的透明度咯？

和图片的透明度也没关系的，是你图片的底色是白色的，使用ps或者一些在线工具把图片底色设置为透明就好了；

**Comment by BNTang** [comment]
> > > 哈哈哈哈,因为那个白色是你图片的底色,你这个图片的背景不是透明的而是白的;
> > 
> > 
> > 意思是自己要在回调函数当中设置图片的透明度咯？
> 
> 和图片的透明度也没关系的，是你图片的底色是白色的，使用ps或者一些在线工具把图片底色设置为透明就好了；

欧克
