### ISSUE TITLE
🐛 目录没有在浏览器最大化时触发自适应

### ISSUE THREAD

**Issue by hopeko** [BNDong/Cnblogs-Theme-SimpleMemory#304]
version: 2.1.0
如果在浏览器normal时，目录显示省略（“...”），在点击浏览器最大化（宽度足够）后，目录仍然显示省略。

**Comment by wangyang0210** [comment]
https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/reference/configs.html#autowidthscroll-%E6%96%87%E7%AB%A0%E7%9B%AE%E5%BD%95%E6%A8%AA%E5%90%91%E6%BB%9A%E5%8A%A8%E6%9D%A1

操作文档中已增加相应的参数处理，需开启相应的配置；
