### ISSUE TITLE
Markdown 下加粗展示效果不一致

### ISSUE THREAD

**Issue by Flonx55** [BNDong/Cnblogs-Theme-SimpleMemory#305]
1. 内容星号加粗后在预览中依旧显示**, 发表后内容加粗不见星号, 这个小问题
![QQ20211209105900.png](https://imgpp.com/images/2021/12/09/QQ20211209105900.png)
2.在下面这一段加了之后, 博客内容不加粗并且显示*号
![QQ20211209105944.png](https://imgpp.com/images/2021/12/09/QQ20211209105944.png)
编写后这一段内容自动使用这样式, 该样式如下(红线):
[![QQ20211209110015.md.png](https://imgpp.com/images/2021/12/09/QQ20211209110015.md.png)](https://imgpp.com/image/ZXBpm)
望大佬们解惑~~~

**Comment by wangyang0210** [comment]
<img width="1297" alt="image" src="https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/36377605/10f880fa-da87-4eaf-bb34-40d71af9b16a">
图片对应的链接已经挂了，根据内容推测是markdown语法问题，建议使用markdown编辑器，编写完成后可进行预览；
