### ISSUE TITLE
cdn.jsdelivr.net访问edge浏览器访问不了，有什么处理方法？

### ISSUE THREAD

**Issue by GuoJikun** [BNDong/Cnblogs-Theme-SimpleMemory#308]
![image](https://user-images.githubusercontent.com/21582741/146718612-e5790c38-72b9-49d2-84f3-386c41aa0c83.png)

**Comment by BNTang** [comment]
坐等 jsdelivr 修复即可

**Comment by CherryRum** [comment]
> 坐等 jsdelivr 修复即可

貌似isp掉了,暂时没法提供国内cdn了,现在全部切到国际cdn了
