### ISSUE TITLE
配置好浏览器报错：ERR_EMPTY_RESPONSE，且页面是空白的

### ISSUE THREAD

**Issue by xuzihaode** [BNDong/Cnblogs-Theme-SimpleMemory#309]
Error error executing code: <XHR for https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v2.1.0/dist/simpleMemory.js>

GET https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js net::ERR_EMPTY_RESPONSE

GET https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js net::ERR_EMPTY_RESPONSE

DevTools 无法加载 SourceMap： 无法加载 chrome-extension://ljngjbnaijcbncmcnjfhigebomdlkcjo/content-script/browser-polyfill.min.js.map: 的内容HTTP 错误：状态代码 404，net::ERR_UNKNOWN_URL_SCHEME

**Comment by BNTang** [comment]
> Error error executing code: <XHR for [https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v2.1.0/dist/simpleMemory.js>](https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v2.1.0/dist/simpleMemory.js%3E)
> 
> GET https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js net::ERR_EMPTY_RESPONSE
> 
> GET https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js net::ERR_EMPTY_RESPONSE
> 
> DevTools 无法加载 SourceMap： 无法加载 chrome-extension://ljngjbnaijcbncmcnjfhigebomdlkcjo/content-script/browser-polyfill.min.js.map: 的内容HTTP 错误：状态代码 404，net::ERR_UNKNOWN_URL_SCHEME

昨天 jsdelivr 挂了

**Comment by hejianlai** [comment]
很多资源404。。。会修复么？

**Comment by HiFxs** [comment]
确实最近好多404了。希望赶快修复。

**Comment by hejianlai** [comment]
> 确实最近好多404了。希望赶快修复。

旧版估计是不维护了，我换了最新的版本 解决了
