### ISSUE TITLE
基于1.0版本，随笔分类显示(rss)

### ISSUE THREAD

**Issue by yinghualuowu** [BNDong/Cnblogs-Theme-SimpleMemory#31]
![image](https://user-images.githubusercontent.com/22371568/62845213-e025dd80-bcf8-11e9-8696-54ad2a144bfa.png)
因为我用的是老版本，在这个基础上做了很多个人定制的功能，不太好合并最新的版本。想问一下这块有修复过么

**Comment by BNDong** [comment]
这个好像是博客园调整页面才出现的，请帖地址我看下！

**Comment by yinghualuowu** [comment]
今天发现已经没有了，暂时关闭吧~~~~
