### ISSUE TITLE
目录不支持公式标题

### ISSUE THREAD

**Issue by MTandHJ** [BNDong/Cnblogs-Theme-SimpleMemory#312]
![image](https://user-images.githubusercontent.com/60973303/147340494-55697855-a381-4d02-87cb-dc788844a270.png)

当标题中存在$...$公式时, 点击无法跳转. 之前1.3版本是可以的.

**Comment by MTandHJ** [comment]
![image](https://user-images.githubusercontent.com/60973303/147340729-8a5dcc67-12b8-40df-a788-d0aaa4055195.png)
此外因为这个原因底部的样式也出现了偏移 (其它无公式标题的文章没发现这个问题).

**Comment by wangyang0210** [comment]
https://www.cnblogs.com/wangyang1225/p/18290663

**Comment by wangyang0210** [comment]
当前最新版本未复现该问题，公式导航正常；
https://www.cnblogs.com/wangyang1225/p/18290663
