### ISSUE TITLE
首页左边的menu消失了怎么解决

### ISSUE THREAD

**Issue by YuiQwert** [BNDong/Cnblogs-Theme-SimpleMemory#313]
如题

**Comment by Billyas** [comment]
同问

**Comment by Billyas** [comment]
版本1.33
![image](https://user-images.githubusercontent.com/62041096/147377164-559bf1af-da84-490c-86d4-52144740f12a.png)
如上报错。之前一直可以正常使用。

**Comment by Billyas** [comment]
大概明白了，
访问连接问题
原本连接地址是https://cdn.cnblogs.com/jsDelivr/gh/BNDong/Cnblogs-Theme-SimpleMemory@v1.3.3/src/style/optiscroll.min.css
但是仓库内已经没有min.css文件了，只有一个optiscroll.css
然后，自然访问不到报错了，
optiscroll.min.css
menu_bubble.min.css
google-fonts.min.css
这三个文件不存在，导致页面显示失败。

**Comment by Billyas** [comment]
当前解决办法只有升级最新版本了，
1.x的好像都不行。

**Comment by YuiQwert** [comment]
> 当前解决办法只有升级最新版本了， 1.x的好像都不行。

非常感谢qwq，那看来只能等有时间的时候更新了。
