### ISSUE TITLE
🐛 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#-1' is not a valid selector.

### ISSUE THREAD

**Issue by BNTang** [BNDong/Cnblogs-Theme-SimpleMemory#318]
- 文章渲染报错

![image](https://user-images.githubusercontent.com/78400939/147517465-1f196f66-7f4f-4a2c-a711-36613f370fea.png)

文章地址：https://www.cnblogs.com/BNTang/articles/15368157.html

**Comment by Kin-Zhang** [comment]
我也遇到了这个问题原来是渲染报错呀.... https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/issues/327

**Comment by NINLER** [comment]
请问有解决方法吗

**Comment by wangyang0210** [comment]
> * 文章渲染报错
> 
> ![image](https://user-images.githubusercontent.com/78400939/147517465-1f196f66-7f4f-4a2c-a711-36613f370fea.png)
> 
> 文章地址：https://www.cnblogs.com/BNTang/articles/15368157.html
有点奇怪，报错说#-1不是一个有效的选择器，不过我这里竟然没有这个错误。。。
![image](https://user-images.githubusercontent.com/36377605/179766534-c4b5012d-f7b0-465d-be41-6c9929f93822.png)

**Comment by XiaoHuiHuiT** [comment]
> > * 文章渲染报错
> > 
> > ![image](https://user-images.githubusercontent.com/78400939/147517465-1f196f66-7f4f-4a2c-a711-36613f370fea.png)
> > 文章地址：https://www.cnblogs.com/BNTang/articles/15368157.html
> > 有点奇怪，报错说#-1不是一个有效的选择器，不过我这里竟然没有这个错误。。。
> > ![image](https://user-images.githubusercontent.com/36377605/179766534-c4b5012d-f7b0-465d-be41-6c9929f93822.png)

你的是什么浏览器
