### ISSUE TITLE
左侧菜单统计功能

### ISSUE THREAD

**Issue by dennis-dong** [BNDong/Cnblogs-Theme-SimpleMemory#319]
![image](https://user-images.githubusercontent.com/75057705/147725834-a06cdde2-f161-45f5-a4ee-8d6c12a087b8.png)
我用的是2.1.0版本，这个统计希望可以加上

另外，这个cdn的js，为什么我上传到博客园，然后引用就没有用呢，为什么必须要使用cdn才可以呢，不都是同样的js么

**Comment by dennis-dong** [comment]
![image](https://user-images.githubusercontent.com/75057705/147725937-7559c372-f14d-4059-9708-80f07c74bb1d.png)
没有这个统计功能目前

**Comment by 973782523** [comment]
你好, 你知道侧边导航栏的随笔分类可以设置默认展开吗?
