### ISSUE TITLE
2.1.0 的页脚与 banner 背景冲突 且页脚不生效

### ISSUE THREAD

**Issue by RuiYuGanLin** [BNDong/Cnblogs-Theme-SimpleMemory#321]
**我用的是2.1.0版本**
**我参考的文章是：https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2/#/Docs/Customization/config**
**我粘贴的位置是：window.cnblogsConfig = {} 标签中**
**以下是我使用的代码**
```
footer: {
    style: 1,
},
```

**以下是我当前侧边栏内的状态**
```
window.cnblogsConfig = {
      info: {
        name: '瑞雨甘霖', // 用户名
        startDate: '2019-11-09', // 入园时间，年-月-日。入园时间查看方法：鼠标停留园龄时间上，会显示入园时间
        avatar: 'http://r.photo.store.qq.com/psc?/V10nkSRg4N7uWB/45NBuzDIW489QBoVep5mcfedaRmP*ecu9oMwK751Ul4aTuO5ajX.t9VFPGPy7xIWLdTUCTSdBBIgrkAxKAs*Ky3BT5uqdZ.nj35sz7*NEZA!/r', // 用户头像
      },
      banner: {
            home: {
                background: [
                    //此处是主页图片支持多张，每个以逗号结尾，刷新换一个
                    "https://pic3.zhimg.com/v2-44caa359239b8c34155304586440d42f_1440w.jpg?source=172ae18b",
                   // "https://pic2.zhimg.com/80/v2-093094dcc09f5990090df4f358e4e411_720w.jpg",  //
                   // "https://pic1.zhimg.com/80/v2-88219da009e3f20ae204ca2452df57cc_720w.jpg",  //
                ],
                    //此处是主页banner上的标语以逗号结尾，刷新换一个
                title: [
                    '每一个不曾起舞的日子，都是对生命的辜负。',
                    '公主死去了，屠龙的少年还在燃烧',
                ],
            },
      }   
  ```
**当我添加代码后，我发现 banner 图的自定义背景没有了，我注销了banner: {}中的背景也不行**

请大神解惑，感谢~！

我的地址是：https://www.cnblogs.com/rygl/

**Comment by HikigayaHachiman0428** [comment]
同样的问题orz

**Comment by jesee030** [comment]
页脚应用cnzz统计生效后banner 背景无法自定义，只显示默认

**Comment by wangyang0210** [comment]
> **我用的是2.1.0版本** **我参考的文章是：https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2/#/Docs/Customization/config** **我粘贴的位置是：window.cnblogsConfig = {} 标签中** **以下是我使用的代码**
> 
> ```
> footer: {
>     style: 1,
> },
> ```
> 
> **以下是我当前侧边栏内的状态**
> 
> ```
> window.cnblogsConfig = {
>       info: {
>         name: '瑞雨甘霖', // 用户名
>         startDate: '2019-11-09', // 入园时间，年-月-日。入园时间查看方法：鼠标停留园龄时间上，会显示入园时间
>         avatar: 'http://r.photo.store.qq.com/psc?/V10nkSRg4N7uWB/45NBuzDIW489QBoVep5mcfedaRmP*ecu9oMwK751Ul4aTuO5ajX.t9VFPGPy7xIWLdTUCTSdBBIgrkAxKAs*Ky3BT5uqdZ.nj35sz7*NEZA!/r', // 用户头像
>       },
>       banner: {
>             home: {
>                 background: [
>                     //此处是主页图片支持多张，每个以逗号结尾，刷新换一个
>                     "https://pic3.zhimg.com/v2-44caa359239b8c34155304586440d42f_1440w.jpg?source=172ae18b",
>                    // "https://pic2.zhimg.com/80/v2-093094dcc09f5990090df4f358e4e411_720w.jpg",  //
>                    // "https://pic1.zhimg.com/80/v2-88219da009e3f20ae204ca2452df57cc_720w.jpg",  //
>                 ],
>                     //此处是主页banner上的标语以逗号结尾，刷新换一个
>                 title: [
>                     '每一个不曾起舞的日子，都是对生命的辜负。',
>                     '公主死去了，屠龙的少年还在燃烧',
>                 ],
>             },
>       }   
> ```
> 
> **当我添加代码后，我发现 banner 图的自定义背景没有了，我注销了banner: {}中的背景也不行**
> 
> 请大神解惑，感谢~！
> 
> 我的地址是：https://www.cnblogs.com/rygl/

感觉你哪里的配置有问题;
<script type="text/javascript">
    window.cnblogsConfig = {
        info: {
            name: '。思索', // 用户名
            startDate: '2018-2-12', // 入园时间，年-月-日。入园时间查看方法：鼠标停留园龄时间上，会显示入园时间
            avatar: 'https://pic.cnblogs.com/avatar/1334215/20180504110551.png', // 用户头像
            blogIcon: 'https://files.cnblogs.com/files/wangyang0210/blog_logo.gif',
        },
        sidebar: {
            navList: [
                // 列表数据 ['导航名称', '链接', 'icon']
                ['随笔', 'https://i.cnblogs.com/posts/edit', 'icon-brush_fill'],
                ['GitHub', 'https://github.com/wangyang0210', 'icon-github'],
                ['Cnblogs', 'https://www.cnblogs.com/', 'icon-cnblogs'],
            ],
            titleMsg: '欢迎来到本博客~',
            // customList: {
            //     "title1": { // 标题
            //         "data": [ // 列表数据 ['列表', '链接']
            //             ['我的博客1', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客2', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客3', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客4', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客5', 'https://www.cnblogs.com/bndong/'],
            //         ],
            //         "icon": "icon-brush_fill" // 配置图标，参考文档：定制化/字体图标库
            //     },
            //     "title2": { // 标题
            //         "data": [ // 列表数据 ['列表', '链接']
            //             ['我的博客6', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客7', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客8', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客9', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客10', 'https://www.cnblogs.com/bndong/'],
            //         ],
            //         "icon": "icon-brush_fill" // 配置图标，参考文档：定制化/字体图标库
            //     }
            // },
        },
        banner: {
            home: {
                titleSource: 'one',
                background: [
                    "https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_220408081453_wallhaven-6k3oox.jpg",
                    "https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_220408081803_wallhaven-oxzk8m.jpg",
                    "https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_220408081823_wallhaven-vg7lv3.jpg",
                ],
            },
            article: {
                background: [
                    "https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_220408081729_wallhaven-6qpzr6.jpg",
                ],
            },
        },
        loading: {
            rebound: {
                 tension: 16,
            },
            spinner: {
                 id: 'spinner',
                radius: 90,
            }
        },
        progressBar: {
            color: '#77b6ff',
        },
        title: {
            onblur: '(oﾟvﾟ)ノ Hi',
            onblurTime: 500,
            focus: '(*´∇｀*) 欢迎回来！',
            focusTime: 1000,
        },
        footer: {
            style: 2,
            text: {
                left: '学无止境',
                right: '谦卑而行',
                iconFont: {
                    icon:  "icon-xl",
                    color: "red",
                    fontSize: "16px"
                }
            },
        },
        links: {
            footer: [
                ["申请坑位", 'https://msg.cnblogs.com/send/wangyang0210'],
                ["申请坑位", 'https://msg.cnblogs.com/send/wangyang0210'],
                ["申请坑位", 'https://msg.cnblogs.com/send/wangyang0210'],
                ["申请坑位", 'https://msg.cnblogs.com/send/wangyang0210'],
                ["申请坑位", 'https://msg.cnblogs.com/send/wangyang0210'],
            ],
        },
        rtMenu: {
            qrCode: 'https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_210308060412yychengshi.jpg',
            reward: {
                alipay: 'https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_210308061757ali.png',
                wechatpay: 'https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_210308061740wechat.png'
            },
        },
        switchDayNight: {
            enable: true,
            auto: {
                enable: true
            }
        },
        animate: {
            homeBanner: {
                enable: true,
                options: {
                    radius: 15,
                }
            },
            articleTitle: {
                enable: true,
            },
            articleBanner: {
                enable: true,
            },
            background: {
                enable: true,
            },
            bannerImages: {
                enable: true,
            },
            backgroundMouse: {
                enable: false,
            },
            mouse: {
                enable: false,
            },
            infoName: {
                enable: false,
            }
        },
        code: {
            type: 'hljs',
            options: {
                macStyle: true,
                maxHeight: '70vh',
                hljs: {
                    theme: 'a11y-dark',
                    languages: []
                },
            },
        },
        articleDirectory: {
            position: 'right',
            minBodyWeight: 1400,
            autoWidthScroll: true,
        },
        // articleSuffix: {
        //     aboutHtml: "I am a good person",
        // },
        consoleList: [
            ['wangyang0210 CNBlogs', 'https://www.cnblogs.com/wangyang0210'],
            ['wangyang0210 GitHub', 'https://github.com/wangyang0210'],
            ['wangyang0210 Email', 'wangyang.0210@foxmail.com']
        ],
    }
</script>

<script src="https://cdn.jsdelivr.net/gh/wangyang0210/Cnblogs-Theme@2379cec379f21c7694e9aad03a32cd6b20eb6637/dist/simpleMemory.7wtyhmw7.js" defer></script>

我用博主的仓库配置也没出现你页面的情况,应该是哪里配置出问题了;

**Comment by wangyang0210** [comment]
> **我用的是2.1.0版本** **我参考的文章是：https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2/#/Docs/Customization/config** **我粘贴的位置是：window.cnblogsConfig = {} 标签中** **以下是我使用的代码**
> 
> ```
> footer: {
>     style: 1,
> },
> ```
> 
> **以下是我当前侧边栏内的状态**
> 
> ```
> window.cnblogsConfig = {
>       info: {
>         name: '瑞雨甘霖', // 用户名
>         startDate: '2019-11-09', // 入园时间，年-月-日。入园时间查看方法：鼠标停留园龄时间上，会显示入园时间
>         avatar: 'http://r.photo.store.qq.com/psc?/V10nkSRg4N7uWB/45NBuzDIW489QBoVep5mcfedaRmP*ecu9oMwK751Ul4aTuO5ajX.t9VFPGPy7xIWLdTUCTSdBBIgrkAxKAs*Ky3BT5uqdZ.nj35sz7*NEZA!/r', // 用户头像
>       },
>       banner: {
>             home: {
>                 background: [
>                     //此处是主页图片支持多张，每个以逗号结尾，刷新换一个
>                     "https://pic3.zhimg.com/v2-44caa359239b8c34155304586440d42f_1440w.jpg?source=172ae18b",
>                    // "https://pic2.zhimg.com/80/v2-093094dcc09f5990090df4f358e4e411_720w.jpg",  //
>                    // "https://pic1.zhimg.com/80/v2-88219da009e3f20ae204ca2452df57cc_720w.jpg",  //
>                 ],
>                     //此处是主页banner上的标语以逗号结尾，刷新换一个
>                 title: [
>                     '每一个不曾起舞的日子，都是对生命的辜负。',
>                     '公主死去了，屠龙的少年还在燃烧',
>                 ],
>             },
>       }   
> ```
> 
> **当我添加代码后，我发现 banner 图的自定义背景没有了，我注销了banner: {}中的背景也不行**
> 
> 请大神解惑，感谢~！
> 
> 我的地址是：https://www.cnblogs.com/rygl/

感觉是你的配置出问题了,因为样式都没加载出来;

**Comment by wangyang0210** [comment]
```
<script type="text/javascript">
    window.cnblogsConfig = {
        info: {
            name: '。思索', // 用户名
            startDate: '2018-2-12', // 入园时间，年-月-日。入园时间查看方法：鼠标停留园龄时间上，会显示入园时间
            avatar: 'https://pic.cnblogs.com/avatar/1334215/20180504110551.png', // 用户头像
            blogIcon: 'https://files.cnblogs.com/files/wangyang0210/blog_logo.gif',
        },
        sidebar: {
            navList: [
                // 列表数据 ['导航名称', '链接', 'icon']
                ['随笔', 'https://i.cnblogs.com/posts/edit', 'icon-brush_fill'],
                ['GitHub', 'https://github.com/wangyang0210', 'icon-github'],
                ['Cnblogs', 'https://www.cnblogs.com/', 'icon-cnblogs'],
            ],
            titleMsg: '欢迎来到本博客~',
            // customList: {
            //     "title1": { // 标题
            //         "data": [ // 列表数据 ['列表', '链接']
            //             ['我的博客1', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客2', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客3', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客4', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客5', 'https://www.cnblogs.com/bndong/'],
            //         ],
            //         "icon": "icon-brush_fill" // 配置图标，参考文档：定制化/字体图标库
            //     },
            //     "title2": { // 标题
            //         "data": [ // 列表数据 ['列表', '链接']
            //             ['我的博客6', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客7', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客8', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客9', 'https://www.cnblogs.com/bndong/'],
            //             ['我的博客10', 'https://www.cnblogs.com/bndong/'],
            //         ],
            //         "icon": "icon-brush_fill" // 配置图标，参考文档：定制化/字体图标库
            //     }
            // },
        },
        banner: {
            home: {
                titleSource: 'one',
                background: [
                    "https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_220408081453_wallhaven-6k3oox.jpg",
                    "https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_220408081803_wallhaven-oxzk8m.jpg",
                    "https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_220408081823_wallhaven-vg7lv3.jpg",
                ],
            },
            article: {
                background: [
                    "https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_220408081729_wallhaven-6qpzr6.jpg",
                ],
            },
        },
        loading: {
            rebound: {
                 tension: 16,
            },
            spinner: {
                 id: 'spinner',
                radius: 90,
            }
        },
        progressBar: {
            color: '#77b6ff',
        },
        title: {
            onblur: '(oﾟvﾟ)ノ Hi',
            onblurTime: 500,
            focus: '(*´∇｀*) 欢迎回来！',
            focusTime: 1000,
        },
        footer: {
            style: 2,
            text: {
                left: '学无止境',
                right: '谦卑而行',
                iconFont: {
                    icon:  "icon-xl",
                    color: "red",
                    fontSize: "16px"
                }
            },
        },
        links: {
            footer: [
                ["申请坑位", 'https://msg.cnblogs.com/send/wangyang0210'],
                ["申请坑位", 'https://msg.cnblogs.com/send/wangyang0210'],
                ["申请坑位", 'https://msg.cnblogs.com/send/wangyang0210'],
                ["申请坑位", 'https://msg.cnblogs.com/send/wangyang0210'],
                ["申请坑位", 'https://msg.cnblogs.com/send/wangyang0210'],
            ],
        },
        rtMenu: {
            qrCode: 'https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_210308060412yychengshi.jpg',
            reward: {
                alipay: 'https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_210308061757ali.png',
                wechatpay: 'https://images.cnblogs.com/cnblogs_com/wangyang0210/1943283/o_210308061740wechat.png'
            },
        },
        switchDayNight: {
            enable: true,
            auto: {
                enable: true
            }
        },
        animate: {
            homeBanner: {
                enable: true,
                options: {
                    radius: 15,
                }
            },
            articleTitle: {
                enable: true,
            },
            articleBanner: {
                enable: true,
            },
            background: {
                enable: true,
            },
            bannerImages: {
                enable: true,
            },
            backgroundMouse: {
                enable: false,
            },
            mouse: {
                enable: false,
            },
            infoName: {
                enable: false,
            }
        },
        code: {
            type: 'hljs',
            options: {
                macStyle: true,
                maxHeight: '70vh',
                hljs: {
                    theme: 'a11y-dark',
                    languages: []
                },
            },
        },
        articleDirectory: {
            position: 'right',
            minBodyWeight: 1400,
            autoWidthScroll: true,
        },
        // articleSuffix: {
        //     aboutHtml: "I am a good person",
        // },
        consoleList: [
            ['wangyang0210 CNBlogs', 'https://www.cnblogs.com/wangyang0210'],
            ['wangyang0210 GitHub', 'https://github.com/wangyang0210'],
            ['wangyang0210 Email', 'wangyang.0210@foxmail.com']
        ],
    }
</script>

<script src="https://cdn.jsdelivr.net/gh/wangyang0210/Cnblogs-Theme@2379cec379f21c7694e9aad03a32cd6b20eb6637/dist/simpleMemory.7wtyhmw7.js" defer></script>
<!-- <script src="https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v2.1.0/dist/simpleMemory.js" defer></script> -->
```
