### ISSUE TITLE
sidebar的排列嵌套到一起了

### ISSUE THREAD

**Issue by XiaochengYe** [BNDong/Cnblogs-Theme-SimpleMemory#325]
按照文档里面
```
window.cnblogsConfig = {
  sidebar: { // 列表数据 ['导航名称', '链接', 'icon']
    customList: {
        "title1": { // 标题
            "data": [ // 列表数据 ['列表', '链接']
                ['我的博客1', 'https://www.cnblogs.com/bndong/'],
                ['我的博客2', 'https://www.cnblogs.com/bndong/'],
                ['我的博客3', 'https://www.cnblogs.com/bndong/'],
                ['我的博客4', 'https://www.cnblogs.com/bndong/'],
                ['我的博客5', 'https://www.cnblogs.com/bndong/'],
            ],
            "icon": "icon-brush_fill" // 配置图标，参考文档：定制化/字体图标库
        },
        "title2": { // 标题
            "data": [ // 列表数据 ['列表', '链接']
                ['我的博客6', 'https://www.cnblogs.com/bndong/'],
                ['我的博客7', 'https://www.cnblogs.com/bndong/'],
                ['我的博客8', 'https://www.cnblogs.com/bndong/'],
                ['我的博客9', 'https://www.cnblogs.com/bndong/'],
                ['我的博客10', 'https://www.cnblogs.com/bndong/'],
            ],
            "icon": "icon-brush_fill" // 配置图标，参考文档：定制化/字体图标库
        },
    },
  },
}
```
原封不动的写进去的结果显示`title2`会嵌到`title1`里面
[JPG](https://s2.loli.net/2022/02/08/dmN96qcxSEhnDlK.png)

**Comment by wangyang0210** [comment]
> 按照文档里面
> 
> ```
> window.cnblogsConfig = {
>   sidebar: { // 列表数据 ['导航名称', '链接', 'icon']
>     customList: {
>         "title1": { // 标题
>             "data": [ // 列表数据 ['列表', '链接']
>                 ['我的博客1', 'https://www.cnblogs.com/bndong/'],
>                 ['我的博客2', 'https://www.cnblogs.com/bndong/'],
>                 ['我的博客3', 'https://www.cnblogs.com/bndong/'],
>                 ['我的博客4', 'https://www.cnblogs.com/bndong/'],
>                 ['我的博客5', 'https://www.cnblogs.com/bndong/'],
>             ],
>             "icon": "icon-brush_fill" // 配置图标，参考文档：定制化/字体图标库
>         },
>         "title2": { // 标题
>             "data": [ // 列表数据 ['列表', '链接']
>                 ['我的博客6', 'https://www.cnblogs.com/bndong/'],
>                 ['我的博客7', 'https://www.cnblogs.com/bndong/'],
>                 ['我的博客8', 'https://www.cnblogs.com/bndong/'],
>                 ['我的博客9', 'https://www.cnblogs.com/bndong/'],
>                 ['我的博客10', 'https://www.cnblogs.com/bndong/'],
>             ],
>             "icon": "icon-brush_fill" // 配置图标，参考文档：定制化/字体图标库
>         },
>     },
>   },
> }
> ```
> 
> 原封不动的写进去的结果显示`title2`会嵌到`title1`里面 [JPG](https://s2.loli.net/2022/02/08/dmN96qcxSEhnDlK.png)

在我的仓库已经修复了，这个是因为没等所有元素组装完成就直接渲染造成的；
https://github.com/wangyang0210/Cnblogs-Theme
