### ISSUE TITLE
首页与文章的背景图片加载很慢的问题

### ISSUE THREAD

**Issue by zhangliang357** [BNDong/Cnblogs-Theme-SimpleMemory#326]
首页与文章的背景图片加载很慢，文章都加载完成了但是图片还没有加载出来

**Comment by wangyang0210** [comment]
可以把图片放到自己的CDN或者上传到博客园再用博客园的链接

**Comment by justFlipped** [comment]
图片全部保存在了博客园的相册里面，用链接可以访问。但是页面加载出来显示是黑屏
https://images.cnblogs.com/cnblogs_com/ydmysm/2210429/t_220830063919_article.jpg
![image](https://user-images.githubusercontent.com/45199431/187369052-4156c9d4-cd8f-4848-bc10-bfecda50717d.png)

**Comment by wangyang0210** [comment]
> 图片全部保存在了博客园的相册里面，用链接可以访问。但是页面加载出来显示是黑屏 https://images.cnblogs.com/cnblogs_com/ydmysm/2210429/t_220830063919_article.jpg ![image](https://user-images.githubusercontent.com/45199431/187369052-4156c9d4-cd8f-4848-bc10-bfecda50717d.png)

你这个t开头的其实是缩略图，可以把t改成o；

如： t_220830063819 =》 o_220830063819

除此之外建议使用webp格式的图片~
