### ISSUE TITLE
缩进 and 显示有问题

### ISSUE THREAD

**Issue by Kin-Zhang** [BNDong/Cnblogs-Theme-SimpleMemory#327]
版本：2.1.0

好像是最近才发生的，问题如图所示：

1. 目录显示有问题，不知道是不是因为markdown内容太多了嘛？博文地址[click](https://www.cnblogs.com/kin-zhang/p/15894824.html)

![image](https://user-images.githubusercontent.com/35365764/155985205-785d97ad-244a-4104-8a6d-5bf210519dc8.png)

2. 缩进问题 博文地址[click](https://www.cnblogs.com/kin-zhang/p/15879803.html)
![image](https://user-images.githubusercontent.com/35365764/155985406-45a9e479-1adb-4140-add4-0f426c960e5d.png)

![image](https://user-images.githubusercontent.com/35365764/155985516-28f4cced-e4cf-4d13-a13c-c0f0198bba1b.png)

**Comment by Kin-Zhang** [comment]
还是缩进问题：
![image](https://user-images.githubusercontent.com/35365764/160280547-48bd91f3-2196-4447-a8b0-73c802faab5b.png)

博文地址：[https://www.cnblogs.com/kin-zhang/p/16047601.html](https://www.cnblogs.com/kin-zhang/p/16047601.html)

**Comment by Kin-Zhang** [comment]
似乎问题越来越严重了 emmm：
![image](https://user-images.githubusercontent.com/35365764/161781525-7b2339b9-c031-437b-a80f-7453f3fe486e.png)

https://www.cnblogs.com/kin-zhang/p/16104211.html

**Comment by wangyang0210** [comment]
1. 目录显示问题,应该是你文章中的markdown标题的问题,可以看下文档中的说明,我这边文章看着只要标题级别没问题,那显示应该是正常的( https://www.cnblogs.com/wangyang0210/p/14299395.html);
    https://wangyang0210.github.io/Cnblogs-Theme/v2/#/Docs/Guide/articleDirectory
3. 缩进问题,可以的话,贴下那块的markdown源码,这块光看文章的话只能看到缩进的很奇葩,哈哈哈哈哈

**Comment by Kin-Zhang** [comment]
1. 目录应该没问题，同一个文章我放到CSDN那边 目录是正常生成的，我感觉是不是emoji的锅？
2. 缩进使用typora直接生成的，在typora中没啥问题

**Comment by Kin-Zhang** [comment]
同步 目录问题已在最新版 作者的更新后 正常显示

---

但是缩进的问题还是存在

**Comment by wangyang0210** [comment]
> 同步 目录问题已在最新版 作者的更新后 正常显示
> 
> 但是缩进的问题还是存在

这一块和主题本身无关的，是博客园本身的问题；尝试了下，如果在博客园本身再编辑处理一下就不会有问题；

https://www.cnblogs.com/wangyang1225/p/17547211.html

**Comment by Kin-Zhang** [comment]
原来如此，谢谢！ @wangyang0210 

能多问一句，在`博客园本身再编辑处理` 这步操作具体是什么步骤呀

**Comment by wangyang0210** [comment]
> 原来如此，谢谢！ @wangyang0210
> 
> 能多问一句，在`博客园本身再编辑处理` 这步操作具体是什么步骤呀

就是针对这块待办事项的代码块重新编辑下；

![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/36377605/dccdf522-3fa2-434a-a700-4a378200e372)

**Comment by Kin-Zhang** [comment]
奥 看懂了 谢谢~ 那我关闭啦
