### ISSUE TITLE
字体库图标404

### ISSUE THREAD

**Issue by ZimengYuan** [BNDong/Cnblogs-Theme-SimpleMemory#329]
github page无法显示 一直404

**Comment by wangyang0210** [comment]
> github page无法显示 一直404

这个是因为md里面使用的是相对路径引用造成的换成link就好了
https://wangyang0210.github.io/Cnblogs-Theme/v2/#/Docs/Customization/fonticon
![image](https://user-images.githubusercontent.com/36377605/179757609-d0aede9e-769e-4fc1-975f-2af64faf1999.png)
