### ISSUE TITLE
首页偶尔出现空白，你的博客主页也是如此。

### ISSUE THREAD

**Issue by juejian** [BNDong/Cnblogs-Theme-SimpleMemory#33]
你的博客主页：<https://bndong.cnblogs.com/>显示正常。

但主页的另一种链接：<https://www.cnblogs.com/bndong/> 首页偶尔只剩一片空白了。

这种连接形式还是博客园默认的啊。

使用默认的主题2种连接形式访问均正常，使用你的主题会出现上面所说的问题。

这2个连接对于博客园来说，是一样的啊。

你的所有文章打开也都是空白了，是不是你正在修改代码 or 更新cdn仓库？ 但是查看网页源代码却是完整的啊。

另一个使用你主题的同胞：<https://www.cnblogs.com/wangyang0210> 页面显示全是正常的啊。

这个到底是咋回事啊，想不明白。

**Comment by BNDong** [comment]
这个是近期才出现的问题，是博客园导致的，主要原因是侧边栏中配置的相关代码不会执行，所以主题设置不上，才会导致这个情况出现！这个问题波及是一定范围的，有的人好使有的人不好使！

关于这个问题我也反馈到了博客园，希望官方能尽快解决！
