### ISSUE TITLE
知道侧边导航栏的随笔分类可以设置默认展开吗?

### ISSUE THREAD

**Issue by 973782523** [BNDong/Cnblogs-Theme-SimpleMemory#332]
主要我记录自己的学习的时候, 我会经常去看自己这个月写了多少偏博客, 我希望有个默认展开的功能, 实在不行我用js编写展开

**Comment by RockNRoll250313** [comment]
我也觉得默认展开 会对我更好。哈哈

**Comment by MangoWAY** [comment]
+1，希望像原来的版本那样默认展开。

**Comment by wangyang0210** [comment]
> 主要我记录自己的学习的时候, 我会经常去看自己这个月写了多少偏博客, 我希望有个默认展开的功能, 实在不行我用js编写展开

这个如果展开不会太多了嘛?不过的确是可以写个配置项来控制是否展开;

**Comment by wangyang0210** [comment]
如果只是为了看这个月写了几篇,我觉得随笔档案可能更合适,或者说展开的时候直接给一个提示,如果全部展开会有点多,侧边栏会很长;

**Comment by wangyang0210** [comment]
https://wangyang0210.github.io/Cnblogs-Theme/v2/#/Docs/Customization/config?id=submenu-%e4%be%a7%e8%be%b9%e6%a0%8f%e6%98%af%e5%90%a6%e5%b1%95%e5%bc%80%e9%85%8d%e7%bd%ae
