### ISSUE TITLE
v2.1.0不支持MarkDown插入图片的格式

### ISSUE THREAD

**Issue by Hyacinth-Android** [BNDong/Cnblogs-Theme-SimpleMemory#336]
在Typora中插入的图片居中、缩放，但复制到博客园中就失效了。
比如，我在Typora中放置一张图片并缩放`<img src="assets/baymax.jpg" alt="image-20220410110401874" style="zoom:50%;" />`，在Typora中居中显示且缩放，但复制到博客园中，居中缩放样式就失效了。

**Comment by wangyang0210** [comment]
> 在Typora中插入的图片居中、缩放，但复制到博客园中就失效了。 比如，我在Typora中放置一张图片并缩放`<img src="assets/baymax.jpg" alt="image-20220410110401874" style="zoom:50%;" />`，在Typora中居中显示且缩放，但复制到博客园中，居中缩放样式就失效了。

因为imgBox中没有处理alt和style,已调整;
![image](https://user-images.githubusercontent.com/36377605/179788640-83200039-12a6-47a2-96f2-9ef1cd8285af.png)
https://github.com/wangyang0210/Cnblogs-Theme
