### ISSUE TITLE
关于字体图标库

### ISSUE THREAD

**Issue by Jason-Guo2008** [BNDong/Cnblogs-Theme-SimpleMemory#337]
请问一下博主，那一个字体图标库是怎么配置的呢？我不是很懂（主要是教程那，好像只能写名称，且不能指定的呀）
![image](https://user-images.githubusercontent.com/76830748/163525297-969be140-bdfb-4b47-9b94-dda3f213f55b.png)
望各位大佬帮帮我吧QwQ！

**Comment by wangyang0210** [comment]
本身是基于阿里iconfont来的，所以配置里只需要写对应的icon的名字即可；

https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/reference/fonticon.html
