### ISSUE TITLE
反馈亿个图标自定义相关的BUG

### ISSUE THREAD

**Issue by TotoWang-hhh** [BNDong/Cnblogs-Theme-SimpleMemory#339]
## 这只是已知的
- 帮助文档里关于已收录的图标那里有问题，会404。实测这个网页可以看见所有图标https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2/iconfontDemo/demo_index.html
- 图标严重缺少，甚至没有电子邮件的图标
- Bilibili的图标过大，放在界面上会比背景上的格子大，出现了奇怪的BUG，详见图1
- 在上述的图表展示网页中，所有的图标代码前面都会有个多余的“.”，很容易误导用户把这个点也复制走，导致图标显示不出

图1
![image](https://user-images.githubusercontent.com/67090055/164166842-00535711-0ee6-4c5a-b4ca-d47a34c81693.png)

**Comment by LINNGRAN** [comment]
多余的“."这个没必要说，本来那个就不是在这个场景下

**Comment by wangyang0210** [comment]
https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/reference/fonticon.html

https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/reference/configs.html#fonticonextend-%E5%AD%97%E4%BD%93%E5%9B%BE%E6%A0%87%E5%BA%93%E6%89%A9%E5%B1%95
