### ISSUE TITLE
手机端打不开博客，一直卡在加载的页面

### ISSUE THREAD

**Issue by q314872695** [BNDong/Cnblogs-Theme-SimpleMemory#34]
![image](https://user-images.githubusercontent.com/41626157/63205063-7da25800-c0d1-11e9-8fd9-afe48a4cd63b.png)
就是这个页面一直转

**Comment by q314872695** [comment]
我使用的是手机自带的浏览器

**Comment by BNDong** [comment]
我这面测试是正常的，请提供下地址，以便我复现改情况！

**Comment by q314872695** [comment]
https://www.cnblogs.com/lxy0/              我的手机是联想z5 Pro，后来手机下载了谷歌浏览器访问正常，自带浏览器就卡在了那个加载的页面




------------------ 原始邮件 ------------------
发件人: "BNDong"<notifications@github.com>; 
发送时间: 2019年8月17日(星期六) 晚上7:41
收件人: "BNDong/Cnblogs-Theme-SimpleMemory"<Cnblogs-Theme-SimpleMemory@noreply.github.com>; 
抄送: "三国梦；"<314872695@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [BNDong/Cnblogs-Theme-SimpleMemory] 手机端打不开博客，一直卡在加载的页面 (#34)




我这面测试是正常的，请提供下地址，以便我复现改情况！

**Comment by BNDong** [comment]
非常抱歉！我无法找到该型号的手机，无法复现该问题。我使用我周边的手机都不会出现这个问题！关于这个问题我平时会多留意一下。
