### ISSUE TITLE
主页的用户名触碰变彩色可否取消

### ISSUE THREAD

**Issue by Leventseleveil** [BNDong/Cnblogs-Theme-SimpleMemory#340]
就是指主页标语上边那个用户名，个人感觉有些抖音风 不喜欢，但是好像在文档里没有找到取消的办法...

**Comment by Leventseleveil** [comment]
<img width="220" alt="image" src="https://user-images.githubusercontent.com/41777761/165468712-d6c888e5-54d5-47f9-b9fd-289d6a371bd7.png">

**Comment by Saudade-Li** [comment]
![image](https://user-images.githubusercontent.com/78409663/165659417-24f966be-48f1-4230-9f82-d89b8e96318a.png)
这个咋改哩，不能够横向显示了

**Comment by wangyang0210** [comment]
> 就是指主页标语上边那个用户名，个人感觉有些抖音风 不喜欢，但是好像在文档里没有找到取消的办法...

https://wangyang0210.github.io/Cnblogs-Theme/v2/#/Docs/Customization/config?id=infoname-%e4%b8%bb%e9%a1%b5name%e5%8a%a8%e6%95%88

增加了一个infoName的配置项,除了配置更新还需要把博客园自定义CSS的CSS进行更新https://github.com/wangyang0210/Cnblogs-Theme/blob/v2/dist/simpleMemory.css

**Comment by wangyang0210** [comment]
https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2/#/Docs/Customization/config?id=homebannertitle-%e4%b8%bb%e9%a1%b5banner%e4%b8%8aname%e7%9a%84%e5%8a%a8%e6%95%88

新版本已经有对应的配置支持，等发布的时候可以进行更新；
