### ISSUE TITLE
TAG显示标签有问题，不是横向显示

### ISSUE THREAD

**Issue by Saudade-Li** [BNDong/Cnblogs-Theme-SimpleMemory#341]
![image](https://user-images.githubusercontent.com/78409663/165659321-76a1d735-cf14-4635-ae12-28d40d9cb360.png)

**Comment by wangyang0210** [comment]
![image](https://user-images.githubusercontent.com/36377605/179743015-fa0d0c32-7f8a-4f26-b62a-cc8639450bf4.png)

方便的话给下你的博客地址,我这边显示都是正常的~
> ![image](https://user-images.githubusercontent.com/78409663/165659321-76a1d735-cf14-4635-ae12-28d40d9cb360.png)

**Comment by Saudade-Li** [comment]
现在弄好了
