### ISSUE TITLE
侧边栏sidebar的customList出现问题

### ISSUE THREAD

**Issue by LovelyFang** [BNDong/Cnblogs-Theme-SimpleMemory#344]
![1](https://user-images.githubusercontent.com/76636113/167628819-baedc9fb-fcc2-4e29-ada7-1c2e1602c528.png)
![2](https://user-images.githubusercontent.com/76636113/167628825-0e62e7cf-bf18-4678-9624-e7cf3782b19b.png)

2.1.0版本出现这个问题
换成2.0.9和之前的就没有
请问是什么原因吖？求告知 喜欢2.1.0的这个导航

**Comment by wangyang0210** [comment]
> ![1](https://user-images.githubusercontent.com/76636113/167628819-baedc9fb-fcc2-4e29-ada7-1c2e1602c528.png) ![2](https://user-images.githubusercontent.com/76636113/167628825-0e62e7cf-bf18-4678-9624-e7cf3782b19b.png)
> 
> 2.1.0版本出现这个问题 换成2.0.9和之前的就没有 请问是什么原因吖？求告知 喜欢2.1.0的这个导航

我在我的仓库中修复了,https://github.com/wangyang0210/Cnblogs-Theme,你可以直接fork或者直接引用<script src="https://cdn.jsdelivr.net/gh/wangyang0210/Cnblogs-Theme@01a42637f4d1981f65a9edbcc3ccd2dd7bfb39fd/dist/simpleMemory.kp5cj2dw.js" defer></script>

**Comment by wangyang0210** [comment]
![image](https://user-images.githubusercontent.com/36377605/179742579-0b65f85d-97ba-4b67-8eb4-ed667436b290.png)

**Comment by wangyang0210** [comment]
原因是因为没等所有的html组装完成就去渲染造成的

**Comment by LovelyFang** [comment]
成功解决 十分感谢

**Comment by LovelyFang** [comment]
> 原因是因为没等所有的html组装完成就去渲染造成的

成功解决 十分感谢

**Comment by LovelyFang** [comment]
> 原因是因为没等所有的html组装完成就去渲染造成的

解决了  十分感谢
