### ISSUE TITLE
控制台输出无效

### ISSUE THREAD

**Issue by ghost** [BNDong/Cnblogs-Theme-SimpleMemory#348]
我的地址：https://www.cnblogs.com/zhaifanhua

**Comment by wangyang0210** [comment]
我看你博客园配置的生成出来是正常的唉~

**Comment by wangyang0210** [comment]
不过你里面有个配置是有点问题的,infoBackground这个配置,如果没有图片可以直接默认为空;

> 我的地址：https://www.cnblogs.com/zhaifanhua
