### ISSUE TITLE
CNZZ不能用了？

### ISSUE THREAD

**Issue by BNTang** [BNDong/Cnblogs-Theme-SimpleMemory#353]

**Comment by wangyang0210** [comment]
cnzz开始收费了,如果开通了,还可以继续用,不过肯定数据是都没了,而且那个收费还挺贵~~

**Comment by BNTang** [comment]
> cnzz开始收费了,如果开通了,还可以继续用,不过肯定数据是都没了,而且那个收费还挺贵~~

那算了，不用了

**Comment by Kin-Zhang** [comment]
其实有 https://clustrmaps.com/ 但是我估计cnblog里用 得加一下html option，我主页用过这个 还行
