### ISSUE TITLE
使用该主题将导致搜索引擎错误识别发帖日期

### ISSUE THREAD

**Issue by theores** [BNDong/Cnblogs-Theme-SimpleMemory#354]
在博客套用该主题后，博文详情上方的日期时间缩写将导致搜索引擎把年-月-日错误识别为日-月-年，以致搜索结果极难搜到该贴。
如图：

- ### **例一：**

>  ![image](https://user-images.githubusercontent.com/31613432/178882664-f2166be4-01df-4ab9-b017-48f094347033.png)

>  ![image](https://user-images.githubusercontent.com/31613432/178882647-d70059f8-0e32-49ba-aade-394f74d78a43.png)

- ### **例二：**

>  ![image](https://user-images.githubusercontent.com/31613432/178882761-c1fb5b31-758b-4d23-a789-8ddb10b1a074.png)
>  ![image](https://user-images.githubusercontent.com/31613432/178882789-934bac0a-73d8-480b-a447-1048df996a62.png)

- ### **例三（主题作者BNDong博文）：**

>  ![image](https://user-images.githubusercontent.com/31613432/178883501-2ba2d866-b22a-4a23-945b-a6570c1802fe.png)
>  ![image](https://user-images.githubusercontent.com/31613432/178883550-55f08ef0-0161-4bc5-8a1f-32ba8d1b30eb.png)

**Comment by Billyas** [comment]
您好！我 之前也遇见过相同问题，我已经解决。
参考该[链接](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/issues/333)
我已经提交PR，但是由于原作者一直没有更新，无奈关闭。
然后可以将链接转移到我fork的仓库。具体参考链接内教程

**Comment by Billyas** [comment]
### 博客时间问题，已修复方案
修复过程，原本找到了js的代码位置，仅仅是一个substring的问题，但是苦于环境无法编译
我最后只能直接修改生产的dict文件，该文件位于`page-common-comArticle.b054622b.js`，仅仅删除其substring [page-common-comArticle.b054622b.js](https://github.com/Billyas/Cnblogs-Theme-SimpleMemory/commit/cd7c34364c979447a0813f0aba87cfee5891a70e)，由于jsdelivr缓存问题，我新生成了一个tage [v2.1.1](https://github.com/Billyas/Cnblogs-Theme-SimpleMemory/tree/v2.1.1)，可直接引用我的Fork仓库 [https://github.com/Billyas/Cnblogs-Theme-SimpleMemory.git](https://github.com/Billyas/Cnblogs-Theme-SimpleMemory.git)。  

配置时仅需进行如下修改
![image](https://user-images.githubusercontent.com/62041096/161761823-54d3ebf3-e27d-44f3-906d-414ccf81b0aa.png)

[https://cdn.jsdelivr.net/gh/Billyas/Cnblogs-Theme-SimpleMemory@v2.1.1/dist/simpleMemory.js](https://cdn.jsdelivr.net/gh/Billyas/Cnblogs-Theme-SimpleMemory@v2.1.1/dist/simpleMemory.js)


经过校验发现，必须是2022-04-08 这种格式方能被bing搜索识别位置正确日期。重新修改。


[https://cdn.jsdelivr.net/gh/Billyas/Cnblogs-Theme-SimpleMemory@v2.1.2/dist/simpleMemory.js](https://cdn.jsdelivr.net/gh/Billyas/Cnblogs-Theme-SimpleMemory@v2.1.2/dist/simpleMemory.js)

_Originally posted by @Billyas in https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/issues/333#issuecomment-1088690174_

**Comment by theores** [comment]
@Billyas 非常感谢，已经换成你的了。

**Comment by wangyang0210** [comment]
编译的时候因为google-fonts的问题会出现编译错误,目前我是先把google-fonts给注释掉了

**Comment by Billyas** [comment]
## 博客时间格式问题已在新版本内修复
可以替换链接为最新版本
```<script src="https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v2.1.2/dist/simpleMemory.js" defer></script>```
