### ISSUE TITLE
文章目录居中

### ISSUE THREAD

**Issue by Lustrewilkin** [BNDong/Cnblogs-Theme-SimpleMemory#356]
您好，很荣幸使用您的作品，真的很棒

有一个小问题或者建议，能让目录居中吗，望着右上角稍微有点奇怪
期待您的回复~~~

**Comment by wangyang0210** [comment]
<img width="554" alt="image" src="https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/36377605/24eb4e08-14bd-4652-9ef4-b8ea06270402">
鼠标移动到标题，点击图标会显示相应的目录；
