### ISSUE TITLE
可以修改一下文章各级标题的大小以及加入横线隔开不

### ISSUE THREAD

**Issue by troyluce** [BNDong/Cnblogs-Theme-SimpleMemory#358]
非常好的主题，非常喜欢这种简洁的感觉。但感觉标题大小过小了，我用四级标题大小已经比正文大小小许多了，可以稍作修改

**Comment by wangyang0210** [comment]
https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/reference/configs.html#prefixicon-%E6%96%87%E7%AB%A0%E6%A0%87%E9%A2%98%E5%89%8D%E5%9B%BE%E6%A0%87-379

可升级版本并设置prefixIcon
