### ISSUE TITLE
能不能把字体图标库的内容讲的再详细一点？

### ISSUE THREAD

**Issue by 1diamondplus** [BNDong/Cnblogs-Theme-SimpleMemory#361]
内置图标那一块全都404了，拓展图标那一块讲的不清楚哎，求详细讲解

**Comment by wangyang0210** [comment]
> 内置图标那一块全都404了，拓展图标那一块讲的不清楚哎，求详细讲解

扩展图标其实就是，使用第三方的字体图标地址，然后在你需要使用的地方直接引用对应的class名称就好了；比如说在侧边栏中，内置的字体图标你都不喜欢，你去iconfont自己配置了一套，那么你在扩展图标引入对应的链接后，就可以配置你自己的图标了；

window.cnblogsConfig = {
  sidebar: { // 列表数据 ['导航名称', '链接', 'icon']
    navList: [xxx
        ['我的博客1', 'https://www.cnblogs.com/bndong/', 'icon-xxx'],
        ['我的博客2', 'https://www.cnblogs.com/bndong/', 'icon-xxx'],
    ],
  },
}
