### ISSUE TITLE
关于代码自动识别错误问题

### ISSUE THREAD

**Issue by huanngzh** [BNDong/Cnblogs-Theme-SimpleMemory#362]
我在markdown中使用以下语法指定代码块语言时，在博客却显示其他语言，怀疑是hightlight自动识别的问题，如下：

![image](https://user-images.githubusercontent.com/78398294/185735184-eab8f606-74f0-4564-8494-b8b2b52346be.png)

在作者的博客中也发现了错误的现象：

![image](https://user-images.githubusercontent.com/78398294/185735174-9ef4ed0d-5beb-430b-bd5c-962195041be7.png)

请问有什么办法能关闭代码块自动识别语言嘛？

**Comment by wangyang0210** [comment]
这块的却是hightlight识别的问题,不过是可以改造的
