### ISSUE TITLE
如何自定义侧边栏的显示

### ISSUE THREAD

**Issue by adroitwolf** [BNDong/Cnblogs-Theme-SimpleMemory#366]
侧边栏比如积分排名或者推荐排行之类的不想显示，请问怎么关掉？

**Comment by JavaLiuTongXue** [comment]
同问

**Comment by wangyang0210** [comment]
如果只是侧边栏的展示和不展示,你们可以通过博客园后台管理界面去控制;
![image](https://user-images.githubusercontent.com/36377605/200788502-9232a32b-563b-4e4c-b9d3-dc68a9087873.png)

**Comment by adroitwolf** [comment]
感谢
