### ISSUE TITLE
首页文章标题及文章正文没有居中，都靠右对齐了，这是为啥呢

### ISSUE THREAD

**Issue by JavaLiuTongXue** [BNDong/Cnblogs-Theme-SimpleMemory#367]
![image](https://user-images.githubusercontent.com/44133039/198495949-eb3eb29d-2444-45dc-99b3-fce0a66303f2.png)

**Comment by BNDong** [comment]
禁用默认css应该就好了

**Comment by fengzengfly** [comment]
> 禁用默认css应该就好了

禁用了还是不行呀
![image](https://user-images.githubusercontent.com/48151231/230815032-ef4713f0-a052-48a1-a814-b0d7ecd76ee0.png)

**Comment by Orionxty** [comment]
应该是css的问题, 重新复制一下呢, 我今天也是, 不过我是把那个css格式化再放上去的, 就出现了你那种情况

**Comment by wangyang0210** [comment]
> > 禁用默认css应该就好了
> 
> 禁用了还是不行呀 ![image](https://user-images.githubusercontent.com/48151231/230815032-ef4713f0-a052-48a1-a814-b0d7ecd76ee0.png)

建议直接复制制品中的simpleMemory.css的内容,粘贴到页面定制的CSS代码的代码框中；
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/36377605/87ca48ea-2934-486b-b269-031349eaf075)
