### ISSUE TITLE
目前支持侧边栏目录吗？如何设置； 

### ISSUE THREAD

**Issue by juejian** [BNDong/Cnblogs-Theme-SimpleMemory#37]
问题如上。

希望能实现这样的侧边栏目录。

![image](https://user-images.githubusercontent.com/12257223/63254633-a4fe4e00-c2a6-11e9-9041-6b3251e72f2b.png)

**Comment by sky5454** [comment]
使用 HTML 的 `<h1> <h2> ` 或者 MarkDown的 `# ##` 即可
