### ISSUE TITLE
博皮抽离提交PR列表

### ISSUE THREAD

**Issue by wangyang0210** [BNDong/Cnblogs-Theme-SimpleMemory#385]
- [x]  标签分类展示优化
- [x]  自定义背景飘落特效 | 配置项
- [x]  评论展示优化 | 【添加|删除|排序】评论
- [x]  头像旋转     | 配置项
- [x]  代码折叠     | 扩展语法
- [x]  引用扩展     | 扩展语法
- [x]  文章标题前缀图标 | 配置项
- [x]  公告显示优化 
- [x]  文章目录导航优化 | 针对数字，特殊符号，标签为标题时优化
- [x]  评论框背景   | 配置项
- [ ]  主题更新提醒 | 配置项
- [x]  评论打字特效 | 配置项
- [x]  手绘风格标记 | 配置项
- [x]  音乐播放器   | 配置项
- [x]  侧边栏展开   | 配置项
- [x]  公祭日网页置灰   | 配置项
- [x]  复制携带版权信息 | 配置项
- [x]  编译优化统一使用webpack
- [x]  适配博客园VIP相关内容
 ~增加缺省配置项[待定] | 静态资源统一走博客园或者国内公共CDN (其实博主的博皮博客园默认会进行CDN加速的)~
 ~增加npm发布渠道[待定]~
~网站访问统计 | 配置项 => 基于开源的umami | 不够灵活 ｜ 需要同时对umami做改造并自主搭建~

**Comment by BNDong** [comment]
感谢，最近实在太忙了，陆续开始处理了！

**Comment by BNDong** [comment]
我添加了协作者邀请：https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/invitations

**Comment by wangyang0210** [comment]
最近有点忙,等月底忙完,我再继续来提交😘

**Comment by wangyang0210** [comment]
主题更新提醒 | 配置项
