### ISSUE TITLE
css的代码框太丑了，而且还不能修改

### ISSUE THREAD

**Issue by justincnn** [BNDong/Cnblogs-Theme-SimpleMemory#389]
默认就是这种mac的框框，
字体颜色和背景太相近，阅读困难，
而且在后台设置代码框配置，也不起作用

![iTTZtc.png](https://i.328888.xyz/2023/05/05/iTTZtc.png)

**Comment by 1inuxboy** [comment]
我也遇到了这个情况，目前已经解决了，只需要在后台调整一下代码主题即可

**Comment by justincnn** [comment]
> 我也遇到了这个情况，目前已经解决了，只需要在后台调整一下代码主题即可

你好，请问如何修改

**Comment by BNDong** [comment]
这是因为报错了，导致的代码高亮没有正确渲染，博客园调整了页面结构，这两天修复更新。

**Comment by justincnn** [comment]
> 这是因为报错了，导致的代码高亮没有正确渲染，博客园调整了页面结构，这两天修复更新。

感谢大神的及时回复，谢谢

**Comment by GG-zhanghuan** [comment]
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/96737531/1008396b-ada4-4674-a0d2-32c7463bedd4)
各位大佬，这种是什么情况。

**Comment by KalebZeng** [comment]
> > 我也遇到了这个情况，目前已经解决了，只需要在后台调整一下代码主题即可
> 
> 你好，请问如何修改

朋友你好，我在Win11上用新Edge浏览自己的博客时也遇到了和你同样的问题，后来尝试了几乎所有博客园自带的代码块配色，最后发现将浅色与深色主题分别设置为 `atom-one-light` 与 `atom-one-dark` 能够正常显示代码（不会出现白底白字），希望能够帮到你。

**博客园后台设置：**
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/44630725/e18c52d8-a6b7-4c2a-8c94-1febd61e4747)

**代码块显示效果：**
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/44630725/ff998a4b-f20f-4e64-b97c-d07486ac57f1)

**Comment by justincnn** [comment]
> > > 我也遇到了这个情况，目前已经解决了，只需要在后台调整一下代码主题即可
> > 
> > 你好，请问如何修改
> 
> 朋友你好，我在Win11上用新Edge浏览自己的博客时也遇到了和你同样的问题，后来尝试了几乎所有博客园自带的代码块配色，最后发现将浅色与深色主题分别设置为 `atom-one-light` 与 `atom-one-dark` 能够正常显示代码（不会出现白底白字），希望能够帮到你。
> 
> **博客园后台设置：**
> ![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/44630725/e18c52d8-a6b7-4c2a-8c94-1febd61e4747)
> 
> **代码块显示效果：**
> ![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/44630725/ff998a4b-f20f-4e64-b97c-d07486ac57f1)
> 
> 

感谢，完美解决问题
