### ISSUE TITLE
v1.1.4版本，markdown toc 自动生成的一级，二级目录点击不能跳转到文章中相应位置？

### ISSUE THREAD

**Issue by juejian** [BNDong/Cnblogs-Theme-SimpleMemory#39]
但是toc 自动生成的3级到6级目录，点击可以跳转到指定位置。

而且三级目录显示成这样了（“#”号都没解析完整）
![image](https://user-images.githubusercontent.com/12257223/63315749-f8bc7600-c33e-11e9-9947-089854c1923b.png)

**Comment by juejian** [comment]
把生成目录和标题的js代码全删了，发现问题解决了

**Comment by BNDong** [comment]
1. markdown toc 自动生成的跳转目前不可以（这个是我测试忽略的一个点），因为页面锚点改变了，这块我考虑一下把，一时间可能改不完。
2 三级标题样式前面本就会多一个 # 号的样式，样式就是如此，不是解析问题！
