### ISSUE TITLE
项目 .md 文件中的 Logo 图片如何生成的

### ISSUE THREAD

**Issue by BNTang** [BNDong/Cnblogs-Theme-SimpleMemory#394]

**Comment by BNDong** [comment]
https://logo-maker.freelogodesign.org/?companyName=GccLoan&_gl=1*1lr9ecj*_ga*MTI0OTY0NDQ5Mi4xNjY5MDI3NDUy*_ga_0PR6284HMM*MTY2OTAyNzQ1Mi4xLjAuMTY2OTAyNzQ1Mi42MC4wLjA.
