### ISSUE TITLE
wen右侧栏的滑块宽度可以调大一点？这样好推拽。

### ISSUE THREAD

**Issue by Cdreamfly** [BNDong/Cnblogs-Theme-SimpleMemory#395]
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/43066112/e63d159b-8465-4b39-b8ac-329855556100)

**Comment by wangyang0210** [comment]
> ![image](https://user-images.githubusercontent.com/43066112/251962879-e63d159b-8465-4b39-b8ac-329855556100.png)

可以自己调整下伪类；

```
::-webkit-scrollbar {
  height: 3px;
  width: 3px
}
```

**Comment by Cdreamfly** [comment]
谢谢了！
