### ISSUE TITLE
有两种主页格式吗？如何配置

### ISSUE THREAD

**Issue by ydteng** [BNDong/Cnblogs-Theme-SimpleMemory#396]
我看这个项目作者的博客园有两种首页，一种打开是全屏的图片（<https://www.cnblogs.com/bndong>），另一种打开就能看到文章列表（<https://www.cnblogs.com/bndong/>），这两种差别再最后面有没有斜线“/”，找了半天配置也没找到。请问一下如何修改的

**Comment by wangyang0210** [comment]
> 我看这个项目作者的博客园有两种首页，一种打开是全屏的图片（https://www.cnblogs.com/bndong），另一种打开就能看到文章列表（https://www.cnblogs.com/bndong/），这两种差别再最后面有没有斜线“/”，找了半天配置也没找到。请问一下如何修改的

不需要配置，这个版本就是当前仓库的版本，还没有发布呢；

**Comment by BNDong** [comment]
已修复
