### ISSUE TITLE
提示文字过长

### ISSUE THREAD

**Issue by fancunwei** [BNDong/Cnblogs-Theme-SimpleMemory#4]
页首背景文字过长时，手机端博文列表第一个会被隐藏，我个人通过限制页首文字的maxheight，和去掉page...author元素的方式解决掉了。
大部分不影响，也可以控制文字长度实现，看作者你是否认为是否需要修复。

**Comment by fancunwei** [comment]
是遮到了列表的第一个。

**Comment by fancunwei** [comment]
是遮到了列表的第一个。

**Comment by BNDong** [comment]
问题已收集，有时间会修复了，可能会限制文字显示的行数了。

**Comment by BNDong** [comment]
已修复

**Comment by fancunwei** [comment]
我已经按自己的方式解决了，就不测了。。。
