### ISSUE TITLE
用自己的oss存储dist后，博客打开字体不能正常显示

### ISSUE THREAD

**Issue by Vanilla-Yukirin** [BNDong/Cnblogs-Theme-SimpleMemory#403]
用自己的oss（阿里云）存了dist，然后按照[https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2/#/Docs/Guide/cdn](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2/#/Docs/Guide/cdn)这里的教程修改了“博客侧边栏公告”中的内容。

能够正常显示大部分内容，但是还有很多问题比如字体等

![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/51521470/edab9762-9394-406c-88dd-b8e94ec43a63)

变回了普通的字体

控制台报错：

![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/51521470/2e2ca978-5fc9-40b3-86b2-5a877ee8256d)

```
Access to font at 'https://vanilla-picture-with-picgo.oss-cn-shenzhen.aliyuncs.com/dist/fonts/7840367fef8abb3b9f8a.woff2' from origin 'https://www.cnblogs.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

百度了一下是说跨域问题：浏览器出于安全考虑，限制访问本站点以为的资源。

我是前后端小白，所以来请教一下各位大佬。谢谢！

**Comment by BNDong** [comment]
对象存储/Bucket 列表/{你的bucket}/数据安全/跨域设置

**Comment by Vanilla-Yukirin** [comment]
@BNDong 您好，我这样设置可以吗？
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/51521470/a305ad38-3fb0-4279-a1b8-5b8838bc83cd)

**Comment by Vanilla-Yukirin** [comment]
噢我勾选了最后一个返回Vary：Origin之后 字体就正常了！

谢谢！
