### ISSUE TITLE
建议切CDN

### ISSUE THREAD

**Issue by Chendaqian** [BNDong/Cnblogs-Theme-SimpleMemory#405]
Staticaly | https://cdn.staticaly.com/gh/{{owner}}/{{repo}}@{{branch}}/{{path}} |  
-- | -- | --
ChinaJsDelivr | https://jsd.cdn.zzko.cn/gh/{{owner}}/{{repo}}@{{branch}}/{{path}} |  
jsDelivr | https://cdn.jsdelivr.net/gh/{{owner}}/{{repo}}@{{branch}}/{{path}}

jsDelivr太不稳定了 国内还是使用 ChinaJsDelivr  吧，另外你博客在北京已经访问不了...

**Comment by nikolay167** [comment]
> jsDelivr太不稳定了 国内还是使用 ChinaJsDelivr 吧，另外你博客在北京已经访问不了...

Hi! 

If needed can provide cdn delivery in China without ICP licenses for any type of projects

**Comment by hsh778205** [comment]
小白，不懂就问。这个CDN里面就存了一个js（https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v2.1.3/dist/simpleMemory.js）对嘛？我有自己的OSS，能不能我把这个文件存在里面然后自己的cnblogs访问呢？

**Comment by sky5454** [comment]
ChinaJsDelivr 有问题，如下

```js
链接地址：
https://jsd.cdn.zzko.cn/gh/BNDong/Cnblogs-Theme-SimpleMemory@2.1.4/dist/images/6d995b207bae4175ff28.webp
请求方法:GET
状态代码:403 Forbidden
```

> Staticaly	[https://cdn.staticaly.com/gh/{{owner}}/{{repo}}@{{branch}}/{{path}}](https://cdn.staticaly.com/gh/%7B%7Bowner%7D%7D/%7B%7Brepo%7D%7D@%7B%7Bbranch%7D%7D/%7B%7Bpath%7D%7D)	 
> ChinaJsDelivr	[https://jsd.cdn.zzko.cn/gh/{{owner}}/{{repo}}@{{branch}}/{{path}}](https://jsd.cdn.zzko.cn/gh/%7B%7Bowner%7D%7D/%7B%7Brepo%7D%7D@%7B%7Bbranch%7D%7D/%7B%7Bpath%7D%7D)	 
> jsDelivr	[https://cdn.jsdelivr.net/gh/{{owner}}/{{repo}}@{{branch}}/{{path}}](https://cdn.jsdelivr.net/gh/%7B%7Bowner%7D%7D/%7B%7Brepo%7D%7D@%7B%7Bbranch%7D%7D/%7B%7Bpath%7D%7D)	
> jsDelivr太不稳定了 国内还是使用 ChinaJsDelivr 吧，另外你博客在北京已经访问不了...

**Comment by nikolay167** [comment]
> ChinaJsDelivr 有问题，如下
> 
> 
> 
> ```js
> 
> 链接地址：
> 
> https://jsd.cdn.zzko.cn/gh/BNDong/Cnblogs-Theme-SimpleMemory@2.1.4/dist/images/6d995b207bae4175ff28.webp
> 
> 请求方法:GET
> 
> 状态代码:403 Forbidden
> 
> ```
> 
> 
> 
> > Staticaly	[https://cdn.staticaly.com/gh/{{owner}}/{{repo}}@{{branch}}/{{path}}](https://cdn.staticaly.com/gh/%7B%7Bowner%7D%7D/%7B%7Brepo%7D%7D@%7B%7Bbranch%7D%7D/%7B%7Bpath%7D%7D)	 
> 
> > ChinaJsDelivr	[https://jsd.cdn.zzko.cn/gh/{{owner}}/{{repo}}@{{branch}}/{{path}}](https://jsd.cdn.zzko.cn/gh/%7B%7Bowner%7D%7D/%7B%7Brepo%7D%7D@%7B%7Bbranch%7D%7D/%7B%7Bpath%7D%7D)	 
> 
> > jsDelivr	[https://cdn.jsdelivr.net/gh/{{owner}}/{{repo}}@{{branch}}/{{path}}](https://cdn.jsdelivr.net/gh/%7B%7Bowner%7D%7D/%7B%7Brepo%7D%7D@%7B%7Bbranch%7D%7D/%7B%7Bpath%7D%7D)	
> 
> > jsDelivr太不稳定了 国内还是使用 ChinaJsDelivr 吧，另外你博客在北京已经访问不了...
> 
> 
> 
> 

Hey! 

Let me know if you need, we can provide our  China cdn for you?
