### ISSUE TITLE
页脚标语中间图标不显示

### ISSUE THREAD

**Issue by YX916** [BNDong/Cnblogs-Theme-SimpleMemory#409]
具体配置
```
// 页脚
footer: {
    style:2,
        text: {
            left: 'A',
            right:'B',
            iconFont: {
                icon:  "icon-xin",
                color: "red",
                fontSize: "16px"
            }
        }
}
```
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/114701555/76e32326-89f6-4ab3-aef2-851a7ce38e5c)
版本
`<script src="https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@2.1.3/dist/simpleMemory.js" defer></script>`

**Comment by wangyang0210** [comment]
合并到issue #410
