### ISSUE TITLE
2.1.3页脚标语小红心图标没了

### ISSUE THREAD

**Issue by mharvay** [BNDong/Cnblogs-Theme-SimpleMemory#410]
2.1.3版本，页脚标语小红心图标没了，头像也无法旋转了

**Comment by wangyang0210** [comment]
头像旋转的动效增加了相应的配置；
https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/reference/configs.html#avatar-%E5%A4%B4%E5%83%8F%E6%97%8B%E8%BD%AC%E5%8A%A8%E6%95%88-383

**Comment by wangyang0210** [comment]
临时可以在页脚或者侧边栏增加以下代码

```
<script type="text/javascript">
$('.footer-text-icon span').addClass('simple-memory-icon-xin')
</script>
```
