### ISSUE TITLE
如何分别设置主页banner的name为园子名称，文章后缀里的name为作者名字

### ISSUE THREAD

**Issue by penguin345** [BNDong/Cnblogs-Theme-SimpleMemory#416]
window.cnblogsConfig = {
  info: {
    name: 'userName',
  },
}
用上面这个设置后主页banner和文章后缀都是同一个名字，我想要主页显示园子名称，文章后缀才是作者名称，现在两个地方的名字是同一个，如何将这两个分别设置

**Comment by wangyang0210** [comment]
一个有趣的需求，不过这个当前不支持配置，一般来说园子名称默认就是作者名称；

**Comment by wangyang0210** [comment]
今天看了下，转载文章的这个用法基本满足你的需求；

https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/reference/reprinted.html#%E8%BD%AC%E8%BD%BD%E6%96%87%E7%AB%A0
