### ISSUE TITLE
代码渲染左上角突然重复渲染了几个样式

### ISSUE THREAD

**Issue by luoChunhui-1024** [BNDong/Cnblogs-Theme-SimpleMemory#417]
代码框渲染时突然重复渲染了三个点，大佬知道这个可能是啥原因吗，之前都是好好的，这两天看博客的时候突然出现了这个问题，我重新按照教程设置了一次，还是这样

一个示例：https://www.cnblogs.com/hi3254014978/p/17738306.html

<img width="1064" alt="image" src="https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/58315453/1cbea469-9d9b-417f-b239-34c4c64936ca">

**Comment by luoChunhui-1024** [comment]
一个示例：https://www.cnblogs.com/hi3254014978/p/17738306.html

**Comment by luoChunhui-1024** [comment]
找到原因了，不知道啥时候多开了一个「Mac风格」，关闭之后就恢复正常了
<img width="1287" alt="image" src="https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/58315453/ae2c2944-99f3-404b-bb9d-5a1da07f24fa">

**Comment by wangyang0210** [comment]
如果启用了博皮的代码高亮的配置的话，建议关闭博客园本身的代码高亮；
