### ISSUE TITLE
如何把页面标题从“hi”、“欢迎回来”改回普通的显示标题？

### ISSUE THREAD

**Issue by ChdarkMoon** [BNDong/Cnblogs-Theme-SimpleMemory#421]
感觉这个美化略显没有必要，又有点挡标题，所以想要删掉，请问有什么方法改回去吗？谢谢！

**Comment by wangyang0210** [comment]
https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/reference/configs.html#title-%E9%A1%B5%E9%9D%A2%E6%A0%87%E7%AD%BE

设置为-1即可

**Comment by ChdarkMoon** [comment]
已解决，谢谢您！
