### ISSUE TITLE
一步一步按照教程设置，但是博客主页一片空白，不显示

### ISSUE THREAD

**Issue by InftySky** [BNDong/Cnblogs-Theme-SimpleMemory#422]

**Comment by InftySky** [comment]
![](https://cdn.luogu.com.cn/upload/image_hosting/0kwpknib.png)

设置如上，版本是v2.1.4，已经打开禁用模板默认CSS、公告控件、使用SimplemMemory 主题，但是不显示内容。

博客地址：https://www.cnblogs.com/-Prulystic-

**Comment by ChdarkMoon** [comment]
你看一下侧边栏那串代码，最下面有一串双引号括起来的链接，里面有一个{VERSION}，改成v2.1.4。我是因为这个没改所以全白的

**Comment by wangyang0210** [comment]
<img width="1260" alt="image" src="https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/36377605/c48a13d1-169c-4548-8af6-ec5401770020">
版本信息替换下；
