### ISSUE TITLE
希望可以增加随笔二级分类

### ISSUE THREAD

**Issue by hetailang** [BNDong/Cnblogs-Theme-SimpleMemory#423]
随笔使用二级分类后，子分类无法正常显示
<img width="843" alt="image" src="https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/89838629/cac830d1-80be-408f-bb5f-6dd0fd638633">

**Comment by hetailang** [comment]
<img width="865" alt="image" src="https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/89838629/ca0cdd0d-1b55-4556-b252-538a26698f0a">

**Comment by wangyang0210** [comment]
这个不是博皮的原因，是因为一级分类下的却没有文章，文章只会在对应的分类下去展现，点击对应的二级分类是可以查看到对应的文章才对；
