### ISSUE TITLE
关于配置侧边栏title信息失败

### ISSUE THREAD

**Issue by ServantHxx** [BNDong/Cnblogs-Theme-SimpleMemory#424]
sidebar: {
        //侧边栏背景图
        titleMsg: "我要成为代码糕手！",
        infoBackground: 'https://pic.imgdb.cn/item/65e7004a9f345e8d03619f82.jpg',
   },
这是我的代码，但是我的博客显示为默认值"欢迎访问本博客~"。

**Comment by Nicolasking007** [comment]
window.cnblogsConfig 格式问题
