### ISSUE TITLE
关于文章页面info修改的问题

### ISSUE THREAD

**Issue by bhxdne** [BNDong/Cnblogs-Theme-SimpleMemory#426]
新的文章页面
2024-04-30 18:11   3    0   0    229    0:27 ~ 0:45
旧的文章页面：
发表于 2021-10-25 23:42阅读：391评论：3推荐：1

我想换回旧的文章页面，就是带文字的，我该怎么进行修改呢

**Comment by wangyang0210** [comment]
这个需要修改设置文章信息相关的代码了，当前没有配置项来配置；

**Comment by wangyang0210** [comment]
https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/blob/v2/src/components/articleInfo/articleInfo.js#L45

**Comment by bhxdne** [comment]
我通过修改\dist\script\page-common-comArticle.785b4ec4.js#L167，已经成功解决问题。
