### ISSUE TITLE
文章底部上一篇和下一篇指向友链和书单

### ISSUE THREAD

**Issue by moondream69** [BNDong/Cnblogs-Theme-SimpleMemory#427]
如图，我的其他文章页面可以进到友链和书单去，但是我看BNDong大佬的文章页面就会自动过滤掉友链和书单，指向下一篇文章，这是怎么弄的？
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/94357296/b760beb1-4f96-4e42-aab2-0516f517eaed)
我的博客链接：https://www.cnblogs.com/blog-moondream

**Comment by wangyang0210** [comment]
文章发布的时候，不勾选发布到主页就行了

**Comment by wangyang0210** [comment]
<img width="1512" alt="image" src="https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/36377605/6ce4beb7-f65d-4c79-b479-bd65c4262ba2">
