### ISSUE TITLE
希望给友链增加分类支持

### ISSUE THREAD

**Issue by moondream69** [BNDong/Cnblogs-Theme-SimpleMemory#428]
如图：
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/94357296/b9f91921-8611-4f0c-80fd-ef400709867a)
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/94357296/3350589c-4c6f-4922-9574-35e027c03c03)
具体代码可以参考BNTang大佬基于本博客二改的友链页处理：
https://github.com/BNTang/Cnblogs-Theme-SimpleMemory/blob/master/src/page/links.js
https://github.com/BNTang/Cnblogs-Theme-SimpleMemory/blob/master/docs/v2/Docs/Customization/links.md

**Comment by wangyang0210** [comment]
我记得这个本身就已经支持了吧；

**Comment by wangyang0210** [comment]
<img width="935" alt="image" src="https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/36377605/05eea98e-41a7-4f7c-8aba-1caea8b42b00">
我记得这个本身就已经支持了才对，我配置都有；

**Comment by wangyang0210** [comment]
哦，忘了，我当前用的是自己仓库的代码，这个我后续PR下
