### ISSUE TITLE
左侧子分类中如果没有文章，会显示异常

### ISSUE THREAD

**Issue by 1092845214** [BNDong/Cnblogs-Theme-SimpleMemory#432]
左侧分类栏，如果父分类被点开，子分类中没有内容，会显示异常
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/42507101/1098097f-f7d5-484b-bc90-fbc6fdc47224)

如果子分类都有内容，就没问题（空的就是异常）
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/42507101/544e93ad-7a90-4d15-a4d2-f7b5a9edffa7)
![image](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/42507101/42df4869-0d50-428e-a718-77297233a2e6)

**Comment by wangyang0210** [comment]
1. 主题版本

**Comment by wangyang0210** [comment]
按着你上面说的没有复现，麻烦提供下详细的信息；

1. 主题版本
2. 博客链接
3. 操作步骤（如何设置可复现该问题）

**Comment by wangyang0210** [comment]
当前最新版本，v2.1.5版本没有复现该问题，issue长时间没有回复，暂时关闭；
