### ISSUE TITLE
主页文章之间无分割线

### ISSUE THREAD

**Issue by ymk2004** [BNDong/Cnblogs-Theme-SimpleMemory#433]
您好，我是一名您的粉丝，看到你分享的博客样式美化，于是自己动手尝试了下，效果非常好。但是我现在遇到了一个小小的问题，想要向您请教：
![msedge_mu3KFDkhrC](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/assets/125185256/b9588ee9-39a3-4deb-aae4-61924d156972)

1.主页文章之间存在无分割线的问题，即第一篇和第二篇文章之间的分割线消失了。
2.想请教下css代码中哪一部分是有关分割线样式的

打扰您了，还望得到您的解决，万分感谢！

**Comment by wangyang0210** [comment]
同一天发表的文章之间本身就是没有分割线的，这个分割线是非同一天文章之间才会有的；

**Comment by ymk2004** [comment]
***@***.***的自动回复邮件。您好，我已经收到了您的邮件，我将会在稍后的一段时间内给您回复，谢谢?0?5。
