### ISSUE TITLE
主页背景图片设置未生效

### ISSUE THREAD

**Issue by zhang33ya** [BNDong/Cnblogs-Theme-SimpleMemory#434]
v2.1.4

window.cnblogsConfig = {
    homeTopImg: [
        "https://p4.itc.cn/q_70/images03/20230512/32c7ad09b5904bea8506d74f96483000.png",
    ],
}

按以上参数配置后未生效

**Comment by wangyang0210** [comment]
v2.1.4的配置请参考最新的文档；

https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/reference/configs.html#background-%E4%B8%BB%E9%A1%B5-banner-%E5%9B%BE%E7%89%87

**Comment by wangyang0210** [comment]
v2.1.4的配置请参考最新的文档，上面的配置错误；

https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/reference/configs.html#background-%E4%B8%BB%E9%A1%B5-banner-%E5%9B%BE%E7%89%87

**Comment by zhang33ya** [comment]
> v2.1.4的配置请参考最新的文档，上面的配置错误；
> 
> https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v2.1/dist/reference/configs.html#background-%E4%B8%BB%E9%A1%B5-banner-%E5%9B%BE%E7%89%87

问题已解决,thanks
