### ISSUE TITLE
非常喜欢你的模板，请问一下如果我想自己建站如何使用你的站点模板？

### ISSUE THREAD

**Issue by zhang33ya** [BNDong/Cnblogs-Theme-SimpleMemory#438]
我想建立一个自己的网站
希望可以从这里获取到你的模板以及简易的导入方法，thanks very much much

**Comment by wangyang0210** [comment]
这个模版是基于博客园来适配的，如果你想搭建可能要自行适配下；如果是基于typecho的话可以基于https://github.com/wangyang0210/EasyBe 来进行搭建，这个是typecho的适配版本；

**Comment by zhang33ya** [comment]
> 这个模版是基于博客园来适配的，如果你想搭建可能要自行适配下；如果是基于typecho的话可以基于https://github.com/wangyang0210/EasyBe 来进行搭建，这个是typecho的适配版本；

谢谢你提供的信息，对我非常有用。你是除了我妈之外，不用pay money情况下对我最好的人之一，感谢你的开源精神。祝你发大财享大运。
