### ISSUE TITLE
底栏'关注博主'按钮位置奇怪

### ISSUE THREAD

**Issue by alloverzyt** [BNDong/Cnblogs-Theme-SimpleMemory#442]
![111](https://github.com/user-attachments/assets/7338275b-e385-457e-aa95-7ab2cc186def)
如图，配置了最新一版的博皮

**Comment by alloverzyt** [comment]
刚刚看到更新历史2.1.5版本修复了这个问题，于是重新更新了CSS代码，但是问题任然存在

**Comment by wangyang0210** [comment]
博客的地址丢一下

**Comment by wangyang0210** [comment]
看了下你的博客对应的css并未更新，建议js也同步更新到最新版本

**Comment by wangyang0210** [comment]
> 刚刚看到更新历史2.1.5版本修复了这个问题，于是重新更新了CSS代码，但是问题任然存在

需要降博皮更新到2.1.5版本，这个只替换CSS并不会生效，因为页面的css是通过js去动态加载的；

**Comment by wangyang0210** [comment]
看了下你当前的博皮，版本是2.1.0，升级下吧；

**Comment by alloverzyt** [comment]
配置文档没有说明要添加JS代码，博客园在html页脚里添加后报错

**Comment by alloverzyt** [comment]
> > 刚刚看到更新历史2.1.5版本修复了这个问题，于是重新更新了CSS代码，但是问题任然存在
> 
> 需要降博皮更新到2.1.5版本，这个只替换CSS并不会生效，因为页面的css是通过js去动态加载的；

请指导一下如何升级JS代码

**Comment by alloverzyt** [comment]
> 看了下你当前的博皮，版本是2.1.0，升级下吧；

解决问题了，js代码是在侧边栏公告里，script src引用的，改成2.1.5版本后已修复，建议在配置文件里加入如何升级
