### ISSUE TITLE
customList 里面的icon标签配置不起作用，不能显示图标

### ISSUE THREAD

**Issue by Song-hcc** [BNDong/Cnblogs-Theme-SimpleMemory#443]
customList: {
        "title1": { // 标题
            "data": [ // 列表数据 ['列表', '链接']
                ['我的博客1', 'https://www.cnblogs.com/bndong/'],
                ['我的博客2', 'https://www.cnblogs.com/bndong/'],
                ['我的博客3', 'https://www.cnblogs.com/bndong/'],
                ['我的博客4', 'https://www.cnblogs.com/bndong/'],
                ['我的博客5', 'https://www.cnblogs.com/bndong/'],
            ],
            "icon": "icon-brush_fill" // 配置图标，参考文档：字体图标
        },
        "title2": { // 标题
            "data": [ // 列表数据 ['列表', '链接']
                ['我的博客6', 'https://www.cnblogs.com/bndong/'],
                ['我的博客7', 'https://www.cnblogs.com/bndong/'],
                ['我的博客8', 'https://www.cnblogs.com/bndong/'],
                ['我的博客9', 'https://www.cnblogs.com/bndong/'],
                ['我的博客10', 'https://www.cnblogs.com/bndong/'],
            ],
            "icon": "icon-brush_fill" // 配置图标，参考文档：字体图标
        },
    },

**Comment by wangyang0210** [comment]
博客的地址给一下吧，方便排查；

**Comment by Song-hcc** [comment]
https://www.cnblogs.com/songpoetry

**Comment by wangyang0210** [comment]
使用`simple-memory-icon-brush_fill`去替代`icon-brush_fill`

**Comment by Song-hcc** [comment]
已解决，十分感谢。
