### ISSUE TITLE
无法下滑

### ISSUE THREAD

**Issue by ghost** [BNDong/Cnblogs-Theme-SimpleMemory#447]
windows & macos 都试过了

但是无痕都可以，什么缘故？？？

link:[link](https://www.cnblogs.com/kimi0705)

**Comment by ghost** [comment]
配置文件：https://gist.github.com/zjx-kimi/5b728055ab258a16741dc22bf33fe175

**Comment by ghost** [comment]
@BNDong @BNDong @BNDong @BNDong @BNDong

**Comment by JianXiao0039** [comment]
我操，我说winPC不能正常下拉，但是手机和Pad都可以。难蚌

**Comment by wangyang0210** [comment]
我刚才试了，可以正常下滑

**Comment by wangyang0210** [comment]
@zjx-kimi 刚才访问了你的博客，是可以正常下滑，看博客引用的资源是2.1版本的，建议升级到最新版本。

**Comment by wangyang0210** [comment]
系统：macOS sequoia（15.0.1）
浏览器：chrome 版本 129.0.6668.100（正式版本） (arm64)

**Comment by ghost** [comment]
> @zjx-kimi 刚才访问了你的博客，是可以正常下滑，看博客引用的资源是2.1版本的，建议升级到最新版本。


我是学校机房用户，如果第一次打开这种主题的博客的时候梯子没有关，那么会导致无法下滑，如果把梯子关了是可以下滑的。

无痕和新建用户是没有问题的都可以下滑，是不是 cdn 设置的问题。

**Comment by ghost** [comment]
谢谢，现在一切正常

**Comment by ghost** [comment]
永远支持
