### ISSUE TITLE
PC端页面无法下滑

### ISSUE THREAD

**Issue by JianXiao0039** [BNDong/Cnblogs-Theme-SimpleMemory#448]
呃啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊
希望尽快调试一下
万分感谢！！！！！！！！！！！！

**Comment by wangyang0210** [comment]
麻烦提供下基本信息，如操作系统，博客地址、浏览器信息和版本等

**Comment by JianXiao0039** [comment]
https://www.cnblogs.com/3cH0-Nu1L
安卓手机，鸿蒙pad都可以用浏览器正常浏览，只有win11PC不行，Google、edge、火狐都试了
https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v2.1.5/dist/simpleMemory.js

**Comment by wangyang0210** [comment]
好的，我今晚在同样的环境下访问下看看

**Comment by JianXiao0039** [comment]
感谢！

**Comment by wangyang0210** [comment]
系统：windows11 专业工作站版 浏览器：chrome、edge 

这里访问是没有问题的，因为当前2.1.5版本其实博客园本身有缓存资源，只要资源正常加载成功，应该不会出现这种问题。

**Comment by wangyang0210** [comment]
![time#1](https://github.com/user-attachments/assets/3a4cf71e-7fe6-43aa-bd84-a0e539b761fa)

**Comment by JianXiao0039** [comment]
好的那我再调试调试吧
因为我把浏览器关于博客园以及我的博客所有信息清除之后还是会卡顿。
有的时候是直接卡在封面，有的时候是往下滑动几下然后就卡住了，无法继续上滑或下滑，我在抽时间重新搭一下吧。
感谢大佬！！！
