### ISSUE TITLE
关于PC端页面无法正常下滑的反馈

### ISSUE THREAD

**Issue by JianXiao0039** [BNDong/Cnblogs-Theme-SimpleMemory#450]
前几天版主做了测试没有任何问题
今天开Chrome浏览器的隐私模式也完全正常，然后就开始把扩展程序轮流打开允许无痕模式权限进行试错，
最终结果是因为挂了最近广告打得很多的Kimi这个AIGC扩展，移除拓展以后博客页面就一切正常了。
再次感谢版主前期的测试与解答

**Comment by wangyang0210** [comment]
👍
