### ISSUE TITLE
二维码清晰度

### ISSUE THREAD

**Issue by JianXiao0039** [BNDong/Cnblogs-Theme-SimpleMemory#451]
![打赏](https://github.com/user-attachments/assets/d74efbe0-197f-4f33-a51a-c19c938d89c2)
打赏功能弹出的二维码比例和像素发生变化导致大多数情况无法正常扫码，
麻烦有时间调试一下
感谢

**Comment by wangyang0210** [comment]
这个其实可以自己裁剪下图片大小即可，365x365尺寸即可。
https://www.cnblogs.com/wangyang0210

**Comment by JianXiao0039** [comment]
嗷嗷好滴~
