### ISSUE TITLE
博客园网页图标更新问题

### ISSUE THREAD

**Issue by moondream69** [BNDong/Cnblogs-Theme-SimpleMemory#452]
博客园样式更新导致主题网页图标配置失效
![image](https://github.com/user-attachments/assets/deda7a04-b042-499b-a9cc-1f162b7c6696)
![image](https://github.com/user-attachments/assets/cd46f47c-3d42-4da0-914d-b25095aa657e)

**Comment by wangyang0210** [comment]
已合并待发布
