### ISSUE TITLE
侧边栏infoBackground 失效

### ISSUE THREAD

**Issue by amluckydave** [BNDong/Cnblogs-Theme-SimpleMemory#456]
sidebar: {
	titleMsg: '欢迎来到我的世界, 亲爱的旅人~',
	infoBackground: 'https://wkphoto.cdn.bcebos.com/503d269759ee3d6d114b52a753166d224e4adec9.jpg',
},

infoBackground 配置后侧边栏背景图片不加载，ver 2.1.6

**Comment by wangyang0210** [comment]
图片访问403呢

**Comment by wangyang0210** [comment]
建议将侧边栏图片上传到博客园相册后，再使用博客园相册对应的链接。

**Comment by amluckydave** [comment]
可以啦 谢谢
