### ISSUE TITLE
代码标签还有问题

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#47]
版本 1.1.5  
有问题的标签：
` div.cnblogs_Highlighter `  
文章路径：https://www.cnblogs.com/yucloud/p/vs_code_config.html#4%E5%8F%98%E9%87%8F%E9%85%8D%E7%BD%AE  
效果图：
![image](https://user-images.githubusercontent.com/12370628/63752298-9980d780-c8e3-11e9-9e30-29cfac017aac.png)

<hr>
以及，代码收起按钮失效了（有时候代码收起是给不同程度的阅读者准备的，所以这个功能还是很有用的。）
 另外，代码框里的滚动条应该一直显示着，不然容易让人误以为代码就这么多。

**Comment by sky5454** [comment]
![image](https://user-images.githubusercontent.com/12370628/63753150-16608100-c8e5-11e9-9410-e1a4994b0c04.png)
微信图标肿大

**Comment by mumuyinxin** [comment]
加载不出底部评论区域

**Comment by sky5454** [comment]
> 加载不出底部评论区域

我的可以，你用的是什么DNS，我用119.29.29.29是没问题的

**Comment by BNDong** [comment]
文章解析的问题请给出基本的示例和编辑器

微信图标变形，我的没问题，自己排查下

评论样式问题，博客园更改页面结构了，等我解决！

**Comment by sky5454** [comment]
> 文章解析的问题请给出基本的示例和编辑器（学会提问题）

图中问号那一部分的代码框是非常黑的，黑到看不清字，问题描述很清晰了，你做开发者是知道`div.cnblogs_Highlighter`是哪一个标签的

**Comment by sky5454** [comment]
问题已解决，是hightlightjs导致的

**Comment by BNDong** [comment]
问题会修复的。基本的示例和编辑器是方便我复现和调试问题。你经常调试博客园的页面就知道了，博客园生成的页面结构并不统一（而且会变），每个编辑器输出的结构都不一样，有时候会莫名多出一堆嵌套，单给我个标签我还真看不出问题，问题都不能复现我又谈何解决！

**Comment by mumuyinxin** [comment]
有个疑问，文章到了三级标签，就显示的不是那么友好了，会多于个#号
希望目录的生成能尽量生成这个文章，二级有点不够用

**Comment by mumuyinxin** [comment]
好奇，你博客加载图片放在哪个网站，是自己搭的图床么

**Comment by BNDong** [comment]
主题中一些图片现在全是github做图床，以前使用博客园的文件系统

我自己的配置，使用外链别的站，没做图床！

**Comment by BNDong** [comment]
关于代码框的一些问题，今天修复了，重新设置了版本，cdn缓存更新需要时间（关于刷新缓存的权限已经向官方申请了）
