### ISSUE TITLE
页面配置

### ISSUE THREAD

**Issue by 1346735074** [BNDong/Cnblogs-Theme-SimpleMemory#48]
很高兴看到你的项目，表示支持。
请问可以提供下 https://www.cnblogs.com/bndong/ 你的博客默认的配置吗。
我们可以直接配置下成你的。
感谢。

**Comment by BNDong** [comment]
我文档给了应用主题的基础配置，也给出了扩展配置的方法，又为什么要配置成我的？

**Comment by 1346735074** [comment]
感谢你的回复，按照最基础的配置加载，页面效果当然没有你的博客丰富。拓展配置没有仔细去配，觉得你的博客挺好看的，图片加载什么的，都蛮好看，复制你的图片链接什么的，都挺慢的。索性来问你要你的博客配置拉

**Comment by 1346735074** [comment]
其实 可以把你博客配置的原版贴出来  供我们参考下
