### ISSUE TITLE
设置失败

### ISSUE THREAD

**Issue by smilellr** [BNDong/Cnblogs-Theme-SimpleMemory#51]
为何我按配置文档操作，将css代码填入保存后，刷新博客，一片空白？？

**Comment by BNDong** [comment]
你有JS权限么？为什么别人可以？问问题最起码你贴个地址吧？

**Comment by Tomotoes** [comment]
我的也是一片空白

**Comment by Ruffianjiang** [comment]
可能是没禁用主题的css

**Comment by qld-cf** [comment]
@smilellr 
f12打开调试
应该是缺少conf
去你的github，fork这个项目即可
