### ISSUE TITLE
首页的背景图设置了之后，还是请求了默认的

### ISSUE THREAD

**Issue by Ruffianjiang** [BNDong/Cnblogs-Theme-SimpleMemory#54]
首页的背景图设置了之后，还是请求了默认的图片，home_top_bg.jpg，这个图片请求挺慢的。  
设置了首页的被进图之后，这个请求可以优化掉吗

https://raw.githubusercontent.com/BNDong/Cnblogs-Theme-SimpleMemory/master/img/home_top_bg.jpg

**Comment by BNDong** [comment]
下次更新优化

**Comment by BNDong** [comment]
v1.1.8 已处理

**Comment by hsh778205** [comment]
> 首页的背景图设置了之后，还是请求了默认的图片，home_top_bg.jpg，这个图片请求挺慢的。
> 设置了首页的被进图之后，这个请求可以优化掉吗
> 
> https://raw.githubusercontent.com/BNDong/Cnblogs-Theme-SimpleMemory/master/img/home_top_bg.jpg

请问，背景图片在哪里替换？看说明文件没有找到qaq
