### ISSUE TITLE
功能需求：菜单信息上的 积分排名 可以优先加上吗

### ISSUE THREAD

**Issue by Ruffianjiang** [BNDong/Cnblogs-Theme-SimpleMemory#55]
菜单信息上的 积分排名 可以优先加上吗？看到其他的用户有加上的，非常感谢开发这套主题，博主辛苦了❤
https://www.cnblogs.com/jajian

**Comment by BNDong** [comment]
可以加上，下次更新加入。

> 我一直感觉积分排名这个玩意没啥用，所以一直没处理！:)

**Comment by marsggbo** [comment]
@Ruffianjiang  @BNDong 请问加上了 积分排名 了吗？怎么加的？

**Comment by Ruffianjiang** [comment]
> @Ruffianjiang @BNDong 请问加上了 积分排名 了吗？怎么加的？

还没有，看提交记录，作者应该还在忙

**Comment by marsggbo** [comment]
@Ruffianjiang 我已经改好了，你可以看一下我的分支更改情况，改的地方有两个：
- 一个是`src/js/simpleMemory.js`,主要是添加了【积分排名】的div
- 另一个写在了`docs/v1.1/Docs/GettingStarted/install.md`里面，也就是你需要在博客园后台的【博客侧边栏公告（支持HTML代码）（支持JS代码）】最后添加如下代码：
```javascript
<script type="text/javascript">
    var lis = $(".catListBlogRank ul")[0];
    $("#sb-sidebarRank ul").html(lis.innerHTML);
    $("#sb-sidebarRank ul").css("color","white");
    console.log(lis.innerHTML);
</script>
```

@BNDong 楼主，谢谢你的代码分享~我做了一小点贡献，pull request了，能通过不~~~~哈哈哈

**Comment by BNDong** [comment]
v1.1.8 已添加该功能，感谢！
