### ISSUE TITLE
那个，那个foot图以后可以自定义配置吗？

### ISSUE THREAD

**Issue by yinghualuowu** [BNDong/Cnblogs-Theme-SimpleMemory#58]
实话，我其实蛮喜欢以前那种的。
就是下面这张
![image](https://user-images.githubusercontent.com/22371568/64885039-a9dfd300-d695-11e9-92e5-06686b4f18d9.png)

**Comment by BNDong** [comment]
之所以更换了风格，主要是部分人并不能接受这种，我想将主题做的更通用一些。

1.0 和 1.1 两个版本的页脚的 html 结构不一样，处理的方式也不同，关于两者兼容的功能我考虑一下要不要处理！

> 如果希望保留这种风格的人增多，我会尝试将两个风格都保留下来，并可以通过配置进行切换！

**Comment by BNDong** [comment]
v1.1.8 已支持该功能，具体查看文档！
