### ISSUE TITLE
有个问题，无法显示分页了

### ISSUE THREAD

**Issue by qld-cf** [BNDong/Cnblogs-Theme-SimpleMemory#59]
@BNDong

**Comment by BNDong** [comment]
请问是那里的分页？我这面测试显示正常的！

**Comment by qld-cf** [comment]
https://www.cnblogs.com/mapleChain   找不到第二页数据，也没看到分页器 dom是空的 @BNDong

**Comment by BNDong** [comment]
分页功能没发现问题，请确认文章数量是否达到分页的数量？!

**Comment by qld-cf** [comment]
> 分页功能没发现问题，请确认文章数量是否达到分页的数量？!

现在可以了 应该是博客园问题
