### ISSUE TITLE
谷歌字体导致的博客加载慢的问题

### ISSUE THREAD

**Issue by ManWingloeng** [BNDong/Cnblogs-Theme-SimpleMemory#64]
![image](https://user-images.githubusercontent.com/20945688/66252839-e6818480-e792-11e9-986b-8a48583dad10.png)
发现总是这两个加载很慢，导致博客加载慢，请问有什么解决办法？
- css?family=Playball
- analytics.js
主要是谷歌字体和另一个js的问题：
https://fonts.googleapis.com/css?family=Playball
https://www.google-analytics.com/analytics.js

**Comment by BNDong** [comment]
可能是网络的问题，我测试时这两个文件加载时间都在100ms以内！

**Comment by sky5454** [comment]
### 原因
严重的DNS劫持和不可描述的污染

### 解决方案
使用浏览器插件：
Replace Google CDN

该插件Github仓库：https://github.com/justjavac/ReplaceGoogleCDN

原理是使用中科大的google字体等库反向代理
主要源码：
![image](https://user-images.githubusercontent.com/12370628/66574703-40c18180-eba7-11e9-99a8-682ca07b3dff.png)

![image](https://user-images.githubusercontent.com/12370628/66574577-0f48b600-eba7-11e9-91cf-752b25ef6944.png)


至于使用中科大反代，我提过建议，但楼上作者没有采纳

**Comment by ManWingloeng** [comment]
> ### 原因
> 严重的DNS劫持和不可描述的污染
> 
> ### 解决方案
> 使用浏览器插件：
> Replace Google CDN
> 
> 该插件Github仓库：https://github.com/justjavac/ReplaceGoogleCDN
> 
> 原理是使用中科大的google字体等库反向代理
> 主要源码：
> ![image](https://user-images.githubusercontent.com/12370628/66574703-40c18180-eba7-11e9-99a8-682ca07b3dff.png)
> 
> ![image](https://user-images.githubusercontent.com/12370628/66574577-0f48b600-eba7-11e9-91cf-752b25ef6944.png)
> 
> 至于使用中科大反代，我提过建议，但楼上作者没有采纳

我装插件没用啊，我是想读我的博客的人可以加载快一些，我分享给妹子打开太慢了...

**Comment by BNDong** [comment]
这个插件中：```fonts.googleapis.com``` 使用的代理是 ```fonts.googleapis.com```

但是你使用 ```fonts.googleapis.com``` 其请求资源的时候它只是 302 跳转到了```fonts.googleapis.com```

```
Request URL: https://fonts.proxy.ustclug.org/css?family=Playball
Request Method: GET
Status Code: 302 
Remote Address: 127.0.0.1:8888
Referrer Policy: no-referrer-when-downgrade

content-type: text/html
date: Thu, 17 Oct 2019 02:12:23 GMT
location: https://fonts.googleapis.com/css?family=Playball
server: nginx
status: 302
:authority: fonts.proxy.ustclug.org
:method: GET
:path: /css?family=Playball
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9
dnt: 1
sec-fetch-mode: navigate
sec-fetch-site: none
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
family: Playball
```

所以使用这个代理没有意义。

**Comment by sky5454** [comment]
> 
> 
> 这个插件中：`fonts.googleapis.com` 使用的代理是 `fonts.proxy.ustclug.org`
> 
> 但是你使用 `fonts.proxy.ustclug.org` 请求资源的时候它只是 302 跳转到了`fonts.googleapis.com`
> 
> ```
> Request URL: https://fonts.proxy.ustclug.org/css?family=Playball
> Request Method: GET
> Status Code: 302 
> Remote Address: 127.0.0.1:8888
> Referrer Policy: no-referrer-when-downgrade
> 
> content-type: text/html
> date: Thu, 17 Oct 2019 02:12:23 GMT
> location: https://fonts.googleapis.com/css?family=Playball
> server: nginx
> status: 302
> :authority: fonts.proxy.ustclug.org
> :method: GET
> :path: /css?family=Playball
> :scheme: https
> accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
> accept-encoding: gzip, deflate, br
> accept-language: zh-CN,zh;q=0.9
> dnt: 1
> sec-fetch-mode: navigate
> sec-fetch-site: none
> upgrade-insecure-requests: 1
> user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
> family: Playball
> ```
> 
> 所以使用这个代理没有意义。

只是这个地址跳转而已， 其他地址没有，而且的确使用之后打开就不卡页面了。你那里应该是没有DNS/iptable 类型的污染，我这边就很多。卡住的不止是这一个请求

**Comment by BNDong** [comment]
嗯，涉及入口文件，目前这个版本没法替换了，只能下个版本处理了。下个版本我把这个替换了，将一些页面代码迁移出来。
