### ISSUE TITLE
那个标题显示了，但是目录中还是没有显示，已经更新到最新版本

### ISSUE THREAD

**Issue by xuweiweishishui** [BNDong/Cnblogs-Theme-SimpleMemory#65]
![QQ截图20191007182849](https://user-images.githubusercontent.com/32082910/66304988-f8009300-e930-11e9-8d68-f50b4acd1e32.png)

**Comment by BNDong** [comment]
稍等，我处理下！

**Comment by BNDong** [comment]
重新刷新页面应该就没问题了

**Comment by xuweiweishishui** [comment]
好了 我看到了 谢谢啦
