### ISSUE TITLE
功能建议   折叠“随笔档案”

### ISSUE THREAD

**Issue by sky5454** [BNDong/Cnblogs-Theme-SimpleMemory#67]
![image](https://user-images.githubusercontent.com/12370628/66573867-e4119700-eba5-11e9-80bb-6d1751330127.png)
如图，相信很多人和我一样，这随笔档案都只是用来看自己哪个月写了多少篇而已，作用不大，建议增加折叠开关，就只是折叠起来，但不关闭该功能。

**Comment by BNDong** [comment]
这个改动起来可能稍微麻烦一些，我考虑下吧，时间充裕的情况下我会添加这个功能。
