### ISSUE TITLE
最近进入博客详情页 出现的问题

### ISSUE THREAD

**Issue by qld-cf** [BNDong/Cnblogs-Theme-SimpleMemory#69]
<img width="1429" alt="1" src="https://user-images.githubusercontent.com/26295134/67084579-cc529800-f1cf-11e9-9779-5083a6853a14.png">
<img width="1434" alt="2" src="https://user-images.githubusercontent.com/26295134/67084586-ceb4f200-f1cf-11e9-8eea-d59d5f3ddbb5.png">
最近进入博客详情页 出现的问题
如果有空可以帮忙看下吗 谢谢 @BNDong

**Comment by qld-cf** [comment]
https://www.cnblogs.com/mapleChain/p/11527645.html

**Comment by mumuyinxin** [comment]
就是有的有问题，有的没问题，对么

**Comment by BNDong** [comment]
这个问题已修复，这个是博客园调整页面导致的解析问题（关于评论的id莫名多了半个括号），我已经做了正则检验，请更新到最新版本v1.1.8
