### ISSUE TITLE
大佬，请教个问题

### ISSUE THREAD

**Issue by mumuyinxin** [BNDong/Cnblogs-Theme-SimpleMemory#70]
https://www.cnblogs.com/mumuyinxin/p/9551925.html
我这个页面用markdown格式，打开异常

https://www.cnblogs.com/mumuyinxin/p/11316861.html
其它同样的页面却能打得开

用的都是你的模板1.1.8

**Comment by BNDong** [comment]
你使用的是自己的库，拉取我最新的代码
