### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by mumuyinxin** [BNDong/Cnblogs-Theme-SimpleMemory#71]
优化代码块的滚动条颜色，以区别代码背景颜色

**Comment by mumuyinxin** [comment]
可以的话，点下复制按钮，直接复制当前区域代码到剪切板，提示已复制到剪切板
个人感觉这样更直接，希望采纳

**Comment by BNDong** [comment]
代码块滚动条的颜色是自动设置的，颜色与代码注释颜色一致！
代码复制这个延后，非必要功能一时不会添加（增加页面处理负荷）

**Comment by mumuyinxin** [comment]
嗯

**Comment by mumuyinxin** [comment]
如果能手动设置代码块颜色就更好了，黑色，比较影响观看
