### ISSUE TITLE
获取资源配置文件会失败(新出现)

### ISSUE THREAD

**Issue by jingliming** [BNDong/Cnblogs-Theme-SimpleMemory#73]
今天开始出现获取资源配置文件超时，错误信息如图
![image](https://user-images.githubusercontent.com/9865050/67666042-ecd7da80-f9a5-11e9-8d1c-620f4eb6bcc0.png)
导致博客加载时间会变得很长，如果浏览器走代理就没有超时，应该还是github的问题

**Comment by jingliming** [comment]
导致博客加载时间会变得很长

**Comment by jingliming** [comment]
走代理就没问题了，还是github的问题😂

**Comment by sky5454** [comment]
DNS污染

**Comment by K1ngram4** [comment]
怎么解决呢

**Comment by jingliming** [comment]
> DNS污染

确实是，清空dns后就可以了

**Comment by jingliming** [comment]
> 怎么解决呢

搜索如何清楚dns缓存

**Comment by BNDong** [comment]
已经将资源迁移，更新下版本 ```v1.1.9```

## What's new?
* 将引入的 GitHub Raw 的静态资源文件，更换至 Gitee
* 修改检查版本映射的逻辑
* ```fonts.googleapis.com``` 使用反向代理 ```fonts.proxy.ustclug.org```
---
> * 使用本 Repository 的（BNDong/Cnblogs-Theme-SimpleMemory），直接请求 Gitee 仓库的配置文件 /version.js
>
> * 使用自己 Repository 的，为了兼容，将请求自己 Repository 的配置文件 /version.conf （如因此导致加载缓慢，可以在自己仓库自行修改 simpleMemory.js 文件中的方法 getVersionConfig）
