### ISSUE TITLE
点击下一页无法正常显示

### ISSUE THREAD

**Issue by xsh13148** [BNDong/Cnblogs-Theme-SimpleMemory#74]
在首页点击下一页的按钮后跳转到第二页后没有显示文章，就连上一页的按钮也没了，只有banner区域和底部区域

**Comment by BNDong** [comment]
我这面测试没有问题，请提供下地址，我复查下！

> 说明下，上下页功能是博客园原有，本主题目前对上下页除了做样式（css）的调整，没有对其做任何的修改！
