### ISSUE TITLE
你好，你的主题是我这么久看到最好看的主题，请问怎么使用

### ISSUE THREAD

**Issue by 1354586675** [BNDong/Cnblogs-Theme-SimpleMemory#75]

**Comment by BNDong** [comment]
https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/

**Comment by 1354586675** [comment]
谢谢你，我已经看到教程了，之前没有看到。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BNDong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 上午10:41
收件人:&nbsp;"BNDong/Cnblogs-Theme-SimpleMemory"<Cnblogs-Theme-SimpleMemory@noreply.github.com&gt;;
抄送:&nbsp;"回忆"<1354586675@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BNDong/Cnblogs-Theme-SimpleMemory] 你好，你的主题是我这么久看到最好看的主题，请问怎么使用 (#75)




https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/
