### ISSUE TITLE
请问如何添加侧边栏目录？

### ISSUE THREAD

**Issue by Letisl** [BNDong/Cnblogs-Theme-SimpleMemory#76]
![image](https://user-images.githubusercontent.com/39464969/68273294-01505d00-00a1-11ea-99f9-2e2e2913f580.png)
您好，在Issue中看到这样的目录很好看，也很实用。请问这个目录是如何添加的？按照配置流程配置后没有目录，https://www.cnblogs.com/bndong/中也没有这样的目录。谢谢！

**Comment by BNDong** [comment]
自动添加的，会根据1、2级标题自动生成。不显示应该是屏幕宽度不够，这个我后期会优化一下！

**Comment by Letisl** [comment]
![image](https://user-images.githubusercontent.com/39464969/68374962-d76e6780-0180-11ea-804e-698bc5980a4d.png)
这个宽度应该不小了，在手机页面也没有显示。
期待大佬的优化

**Comment by Letisl** [comment]
`<script language="javascript" type="text/javascript">
 
// 生成目录索引列表
function GenerateContentList()
{
 var mainContent = $('#cnblogs_post_body');
 var h2_list = $('#cnblogs_post_body h2');//如果你的章节标题不是h2,只需要将这里的h2换掉即可
 
 if(mainContent.length < 1)
 return;
  
 if(h2_list.length>0)
 {
 var content = '<a name="_labelTop"></a>';
 content += '<div id="navCategory">';
 content += '<p style="font-size:18px"><b>本文目录</b></p>';
 content += '<ul>';
 for(var i=0; i<h2_list.length; i++)
 {
  var go_to_top = '<div style="text-align: right"><a href="#_labelTop" rel="external nofollow" rel="external nofollow" >回到顶部</a><a name="_label' + i + '"></a></div>';
  $(h2_list[i]).before(go_to_top);
   
  var h3_list = $(h2_list[i]).nextAll("h3");
  var li3_content = '';
  for(var j=0; j<h3_list.length; j++)
  {
  var tmp = $(h3_list[j]).prevAll('h2').first();
  if(!tmp.is(h2_list[i]))
   break;
  var li3_anchor = '<a name="_label' + i + '_' + j + '"></a>';
  $(h3_list[j]).before(li3_anchor);
  li3_content += '<li><a href="#_label' + i + '_' + j + '" rel="external nofollow" >' + $(h3_list[j]).text() + '</a></li>';
  }
   
  var li2_content = '';
  if(li3_content.length > 0)
  li2_content = '<li><a href="#_label' + i + '" rel="external nofollow" rel="external nofollow" rel="external nofollow" rel="external nofollow" >' + $(h2_list[i]).text() + '</a><ul>' + li3_content + '</ul></li>';
  else
  li2_content = '<li><a href="#_label' + i + '" rel="external nofollow" rel="external nofollow" rel="external nofollow" rel="external nofollow" >' + $(h2_list[i]).text() + '</a></li>';
  content += li2_content;
 }
 content += '</ul>';
 content += '</div><p> </p>';
 //content += '<p style="font-size:18px"><b>正文</b></p>';
 if($('#cnblogs_post_body').length != 0 )
 {
  $($('#cnblogs_post_body')[0]).prepend(content);
 }
 } 
}
 
GenerateContentList();
</script>`
由于现在无法显示，所以添加了页脚HTML代码加入目录，可以添加但是点击目录和“回到顶部”均无效，能否请大佬看看是怎么回事？

**Comment by Letisl** [comment]
<script language="javascript" type="text/javascript">
 
// 生成目录索引列表
function GenerateContentList()
{
 var mainContent = $('#cnblogs_post_body');
 var h2_list = $('#cnblogs_post_body h2');//如果你的章节标题不是h2,只需要将这里的h2换掉即可
 
 if(mainContent.length < 1)
 return;
  
 if(h2_list.length>0)
 {
 var content = '<a name="_labelTop"></a>';
 content += '<div id="navCategory">';
 content += '<p style="font-size:18px"><b>本文目录</b></p>';
 content += '<ul>';
 for(var i=0; i<h2_list.length; i++)
 {
  var go_to_top = '<div style="text-align: right"><a href="#_labelTop" rel="external nofollow" rel="external nofollow" >回到顶部</a><a name="_label' + i + '"></a></div>';
  $(h2_list[i]).before(go_to_top);
   
  var h3_list = $(h2_list[i]).nextAll("h3");
  var li3_content = '';
  for(var j=0; j<h3_list.length; j++)
  {
  var tmp = $(h3_list[j]).prevAll('h2').first();
  if(!tmp.is(h2_list[i]))
   break;
  var li3_anchor = '<a name="_label' + i + '_' + j + '"></a>';
  $(h3_list[j]).before(li3_anchor);
  li3_content += '<li><a href="#_label' + i + '_' + j + '" rel="external nofollow" >' + $(h3_list[j]).text() + '</a></li>';
  }
   
  var li2_content = '';
  if(li3_content.length > 0)
  li2_content = '<li><a href="#_label' + i + '" rel="external nofollow" rel="external nofollow" rel="external nofollow" rel="external nofollow" >' + $(h2_list[i]).text() + '</a><ul>' + li3_content + '</ul></li>';
  else
  li2_content = '<li><a href="#_label' + i + '" rel="external nofollow" rel="external nofollow" rel="external nofollow" rel="external nofollow" >' + $(h2_list[i]).text() + '</a></li>';
  content += li2_content;
 }
 content += '</ul>';
 content += '</div><p> </p>';
 //content += '<p style="font-size:18px"><b>正文</b></p>';
 if($('#cnblogs_post_body').length != 0 )
 {
  $($('#cnblogs_post_body')[0]).prepend(content);
 }
 } 
}
 
GenerateContentList();
</script>

因为目录无法显示，现在添加了网上找到的页脚HTML代码实现二级目录，可以添加到正文上面，但是点击目录或者是“回到顶部”却无效，能否麻烦大佬有时间的话看看怎么回事？

另外，建议大佬的侧边栏目录增加可选h2、h3为目录。

**Comment by BNDong** [comment]
目录是可以正常显示的，目前目录不显示可能是两个原因：
- 文章中无```h1```标题
- 屏幕分辨率过低，宽度过小

目前目录生成只支持```h1```、```h2```

实现参考：https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/blob/master/src/script/marvin.nav2.js
