### ISSUE TITLE
代码框出现2个ctr+c复制

### ISSUE THREAD

**Issue by woozs** [BNDong/Cnblogs-Theme-SimpleMemory#77]
![image](https://user-images.githubusercontent.com/31236551/68293503-0b865180-00c9-11ea-95ae-07a294a14584.png)
![image](https://user-images.githubusercontent.com/31236551/68293535-150fb980-00c9-11ea-905f-65bc0a13a421.png)

**Comment by BNDong** [comment]
博客园自带的复制功能就是这个样子的，这个不做处理！！
