### ISSUE TITLE
你好，我采用 v1.2.0 出现博客打开空白

### ISSUE THREAD

**Issue by gclm** [BNDong/Cnblogs-Theme-SimpleMemory#78]
你好，大佬

 目前采用主题出现打开博客空白，但是没检查出来问题。可以帮我看看嘛

博客地址： https://www.cnblogs.com/gclm

表现形式：

![image](https://user-images.githubusercontent.com/27618687/68986588-d5c93180-085b-11ea-9ad5-6a3c3998780f.png)

配置项：

![image](https://user-images.githubusercontent.com/27618687/68986613-f5f8f080-085b-11ea-81fe-3714288f143f.png)
![image](https://user-images.githubusercontent.com/27618687/68986616-fbeed180-085b-11ea-831b-be731eab474d.png)

**Comment by gclm** [comment]
希望得到大佬的指点，更刚换到 1.9.0 发现还是不行

**Comment by BNDong** [comment]
请确认下JS权限！
