### ISSUE TITLE
部分样式受cnblogsConfigDefault.GhUserName干扰。

### ISSUE THREAD

**Issue by weilai1917** [BNDong/Cnblogs-Theme-SimpleMemory#79]
开始只想替换footer的背景图片，发现fork的项目，还会走Default的footer.css。

**Comment by BNDong** [comment]
你好！能详细说明下么？

**Comment by weilai1917** [comment]
![image](https://user-images.githubusercontent.com/9894021/69249057-44a1e400-0be8-11ea-838a-39de82ed16db.png)

实际上，前面我是fork了项目，然后只改了clouds的背景样式，但是怎么都不生效。
原来发现资源里仍然使用的是cnblogsConfigDefault的请求路径，资源没有使用。

项目中，https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/blob/d4f6a8faa8801b04e5e281ad70b6877a20cb6482/src/script/simpleMemory.js#L288 拼接的也是default的

**Comment by BNDong** [comment]
对于此问题给你造成的困扰我很抱歉！这是代码的问题，由于当初 GitHub 访问经常404，我就重新处理了 ```getVersionConfig``` 以缓解加载的问题，这里使用的配置其实应该是 ```cnblogsConfig``` 而不是 ```cnblogsConfigDefault``` （当时可能脑抽了），我发布了新的版本 ```v1.2.1``` 修复了这个问题（由于是入口文件修改，受 CDN 缓存限制，只能更改版本更新代码），请拉取最新代码解决该问题！

受此问题影响的版本：```v1.1.9```、```v1.2.0```
