### ISSUE TITLE
唔...标题生成貌似出了些问题。

### ISSUE THREAD

**Issue by water-mi** [BNDong/Cnblogs-Theme-SimpleMemory#8]
如图（这是文章中的标题）：
![kV6VdH.png](https://s2.ax1x.com/2019/01/23/kV6VdH.png)
下图是生成后的目录
![kV6Eee.png](https://s2.ax1x.com/2019/01/23/kV6Eee.png)
这应该算是一个比较严重的bug了，望作者百忙之中能抽空修复一下，辛苦了！

**Comment by BNDong** [comment]
感谢反馈，现已修复！
