### ISSUE TITLE
使用过程中遇到的问题

### ISSUE THREAD

**Issue by ChuanErbao** [BNDong/Cnblogs-Theme-SimpleMemory#82]
1.点击返回顶部无效
2.没有了返回首页的按钮，添加上体验会不会更好一些

**Comment by BNDong** [comment]
1. 目前没发现这种情况，能否提供示例链接！
2. 页首等页面相关导航链接在侧边栏中。

**Comment by ChuanErbao** [comment]
第二个没仔细找实在抱歉，关于第一个 里说的返回顶部按钮是说博客园里自带的那个失效了，尝试了下demo里的也是不行的，倒是不影响使用，只是精益求精嘛，嘿嘿

**Comment by sky5454** [comment]
使用HOME键代替，不过麻烦一点

**Comment by BNDong** [comment]
今天我排查了下关于原有页面链接锚点跳转失效的问题。你是否使用了播放器？尝试取消播放器的使用。看看时候解决了该问题！

返回顶部，也可以使用页面右下角的按钮，提供了该功能的🙂

**Comment by GarudaAiacos** [comment]
请问文章右边的生成目录如何设置呢？我在文档中没有找到相关配置。

**Comment by BNDong** [comment]
> 请问文章右边的生成目录如何设置呢？我在文档中没有找到相关的配置。

文章目录，根据一二级标题自动生成，暂无相关配置！[书写规范文档](https://bndong.github.io/Cnblogs-Theme-SimpleMemory/v1.1/#/Docs/GettingStarted/writtenForm)

ps: 为了阅读体验，当前窗口宽度小于 1360px 时，不会显示文章目录！

**Comment by GarudaAiacos** [comment]
好的，谢谢您。现在还存在一个问题，就是我在使用markdown语法插入一个代码块，当代码块中只有1行代码时会出现抖动，不知道怎么回事。
![image](https://user-images.githubusercontent.com/26762507/71079539-67fb8700-21c6-11ea-8034-c032b92a7713.png)

**Comment by BNDong** [comment]
> ## 返回顶部问题
> 你好,点击返回顶部的时候,如果用户向下滚动,则出现卡顿,这个能不能是否可以改一下呢?

点击返回顶部后还要向下滚动？？我考虑下吧！

**Comment by BNDong** [comment]
此 Issues 关闭，有问题请发起新的 Issues ！
