### ISSUE TITLE
markdown不支持三级及以上的标题

### ISSUE THREAD

**Issue by sshsu** [BNDong/Cnblogs-Theme-SimpleMemory#83]
如下所示，文档的内容如下:
![image](https://user-images.githubusercontent.com/26362180/69896477-dcd36200-137a-11ea-9cad-a3e30f56c907.png)

但在实际文档中二级以上的标题就mei'xiao没效了
![image](https://user-images.githubusercontent.com/26362180/69896486-f4124f80-137a-11ea-84ef-0fbfa212d615.png)

在右侧的大纲中，更不包含二级以上标题
![image](https://user-images.githubusercontent.com/26362180/69896494-05f3f280-137b-11ea-9944-052defe7c449.png)

是我的使用方法有误，还是哪里可以配置或者修改吗？

而且右侧的大纲能否做一些修改，这个不单有显示当前所在的位置的作用，也有给予别人审视整体大纲的作用，有时候只是想看一个1级标题看看其下面有什么，所以能否在大纲旁添加一个折叠展开的按钮用来折叠展开当前大纲，谢谢

**Comment by BNDong** [comment]
关于标题目录目前就是这个样子的。其实这个目录生成的插件，来源于一位园友的分享，我只是将其扩展优化了。关于这部分后期我会重构（时间允许的情况下），优先支持多级目录。至于折叠展开，考虑一下！
