### ISSUE TITLE
为什么应用皮肤后，刷新博客页面空白

### ISSUE THREAD

**Issue by QQ2017** [BNDong/Cnblogs-Theme-SimpleMemory#86]
如题，为什么应用皮肤后，刷新博客页面空白？确定不是本地页面缓存问题，按照帮助文档做的，版本1.2.3

**Comment by wangenheng** [comment]
是不是没有js权限？

**Comment by QQ2017** [comment]
![image](https://user-images.githubusercontent.com/23667705/71759972-1f93d700-2ef1-11ea-8c5d-eff2fede827f.png)
有权限的

**Comment by wangenheng** [comment]
你这js里面这版本这不是1.2.2？

**Comment by QQ2017** [comment]
> 你这js里面这版本这不是1.2.2？

改为1.2.3都是没用的，我现在用的这个CSS
https://raw.githubusercontent.com/BNDong/Cnblogs-Theme-SimpleMemory/v1.2.3/src/style/base.min.css

**Comment by QQ2017** [comment]
![image](https://user-images.githubusercontent.com/23667705/71776747-6a851b80-2fd1-11ea-82d5-f9194243b8e0.png)

**Comment by weizexin** [comment]
我的也出现这种情况

**Comment by BNDong** [comment]
贴博客地址，我看看！

**Comment by weizexin** [comment]
现在好了，我重贴了一次

**Comment by QQ2017** [comment]
> 贴博客地址，我看看！

已经把博客地址和登陆账号密码发到您的邮箱 dbnuo@foxmail.com

**Comment by BNDong** [comment]
> > 贴博客地址，我看看！
> 
> 已经把博客地址和登陆账号密码发到您的邮箱 [dbnuo@foxmail.com](mailto:dbnuo@foxmail.com)

你的问题我看了，虽然你申请开通了JS权限，但实际并不能运行JS代码：

配置：

![Uploading WX20200109-141558@2x.png…]()

控制台输出：

![Uploading WX20200109-141732@2x.png…]()

以前也有园友遇见过这种现象，将此问题[反馈](https://group.cnblogs.com/forum/public/)给官方，让博客园官方处理该问题！

**Comment by QQ2017** [comment]
> > > 贴博客地址，我看看！
> > 
> > 
> > 已经把博客地址和登陆账号密码发到您的邮箱 [dbnuo@foxmail.com](mailto:dbnuo@foxmail.com)
> 
> 你的问题我看了，虽然你申请开通了JS权限，但实际并不能运行JS代码：
> 
> 配置：
> 
> <img alt="WX20200109-141558@2x" width="474" src="https://user-images.githubusercontent.com/21150911/72043170-6fa4dc00-32eb-11ea-970d-79341e75b9aa.png">
> 
> 控制台输出：
> 
> <img alt="WX20200109-141732@2x" width="476" src="https://user-images.githubusercontent.com/21150911/72043185-792e4400-32eb-11ea-8f53-df87309f5819.png">
> 
> 以前也有园友遇见过这种现象，将此问题[反馈](https://group.cnblogs.com/forum/public/)给官方，让博客园官方处理该问题！

好的，已经反馈了，感谢！

**Comment by QQ2017** [comment]
破案了，博客园官方回应：

> 您好，您似乎没有启用「公告」控件，请确保在 博客后台-选项-控件显示设置 处勾选了「公告」控件

![image](https://user-images.githubusercontent.com/23667705/72052652-8275db80-3300-11ea-8e17-e9a2e062e197.png)

没想到这个“公告”组件会导致不执行js，建议在帮助文档里面加以说明！

**Comment by BNDong** [comment]
好的，后期我会更新文档！这个“公告”组件会导致不执行js，我确实也不清楚。😄

**Comment by Joker-lkc** [comment]
用了1.24显示空白，是没有js权限的原因吗，我刚刚申请js权限

**Comment by BNDong** [comment]
> 用了1.24显示空白，是没有js权限的原因吗，我刚刚申请js权限

可以试着运行下 js 代码：
侧边栏添加下面代码，刷新页面，看看控制台有没有输出 `test`
```
<script>
    console.log('test');
</script>
```

**Comment by U-s-e-r-Unknown** [comment]
我也遇到过，后来重新配置就好了

**Comment by Foxer-Z** [comment]
之前我遇到一次空白，原因是gitee网站也打不开，过一会又好了，这回......哈哈哈哈，还能这样

![图片](https://user-images.githubusercontent.com/51819524/76288675-3c2e0000-62e2-11ea-88eb-fe71bb7153c4.png)

![图片](https://user-images.githubusercontent.com/51819524/76288856-b9f20b80-62e2-11ea-9e54-294f31a5407f.png)

**Comment by BNDong** [comment]
由于 Gitee 屏蔽了本项目库 😓，所有引用至 Gitee 的静态资源全部失效。如果出现页面空白、无法加载的现象，可以尝试更新版本至 v1.2.6

**Comment by Foxer-Z** [comment]
> 由于 Gitee 屏蔽了本项目库 sweat，所有引用至 Gitee 的静态资源全部失效。如果出现页面空白、无法加载的现象，可以尝试更新版本至 v1.2.6

好的

**Comment by Jason66661010** [comment]
请问这是什么错误？

![Snipaste_2020-04-26_22-21-17](https://user-images.githubusercontent.com/47680845/80310318-8f193380-880c-11ea-8dcc-90a770fb472a.png)

**Comment by zhuhuibiao** [comment]
挺好的呀

**Comment by zhuhuibiao** [comment]
https://www.cnblogs.com/zhuhuibiao/  希望大家参观我的

**Comment by xuejian-git** [comment]
能否告知一下那些配置用到了外链呢？我把这些配置取消一下，自己找了很久没有找全。。我现在只有在用梯子的情况下才可以加载首页，否则就是空白。。

**Comment by xuejian-git** [comment]
> 由于 Gitee 屏蔽了本项目库 😓，所有引用至 Gitee 的静态资源全部失效。如果出现页面空白、无法加载的现象，可以尝试更新版本至 v1.2.6

**Comment by xuejian-git** [comment]
> 由于 Gitee 屏蔽了本项目库 😓，所有引用至 Gitee 的静态资源全部失效。如果出现页面空白、无法加载的现象，可以尝试更新版本至 v1.2.6

能否告知一下那些配置用到了外链呢？我把这些配置取消一下，自己找了很久没有找全。。我现在只有在用梯子的情况下才可以加载首页，否则就是空白。。

**Comment by BNDong** [comment]
> 能否告知一下那些配置用到了外链呢？我把这些配置取消一下，自己找了很久没有找全。。我现在只有在用梯子的情况下才可以加载首页，否则就是空白。。

你用的什么版本，v1.2.6之后资源都是走的 `jsdelivr` CDN 代理，国内应该是可以访问的。寻找外链，建议使用 IDE 全局搜索，正则匹配下。

**Comment by Smile-July** [comment]
问您一下博主，为什么我更换到了最新版本1.3.2还是页面空白啊┭┮﹏┭┮ 
![image](https://user-images.githubusercontent.com/68686531/88652001-d7dad400-d0fc-11ea-9ff5-bf8804474011.png)，这是什么问题呢？

**Comment by Smile-July** [comment]
除了您发布的测试版本1.0.0  不空白之外  其他的版本用了之后都是空白的┭┮﹏┭┮

**Comment by Smile-July** [comment]
js权限我也是开了，控制台也能打印出来测试的东西，就是页面全空白😔

**Comment by Smile-July** [comment]
博主能否帮忙看一下什么原因呢？万分感谢🙏

**Comment by BNDong** [comment]
> 博主能否帮忙看一下什么原因呢？万分感谢🙏

发我配置：dbnuo@foxmail.com 或 博客园私信我。

**Comment by cuiwenkun** [comment]
> https://www.cnblogs.com/zhuhuibiao/ 希望大家参观我的
能帮我看下我的吗？

**Comment by Jandaes** [comment]
我的是申请了js权限就可以了、第一次应用也是一片空白

**Comment by 1diamondplus** [comment]
![image](https://user-images.githubusercontent.com/106752994/184365389-a65d2c94-7488-473c-93a3-246dedec78a5.png)
求助，博客配置一步一步完全按照教程来的，结果就空白了

**Comment by Maybe-me** [comment]
js权限我也是开了，控制台也能打印出来测试的东西，就是页面全空白，求助

**Comment by nianshu2022** [comment]
你好 我的主页不显示文章
![](https://gitee.com/nianshu2022/picture/raw/master/20221131667450880708.png)

**Comment by LINNGRAN** [comment]
> 你好 我的主页不显示文章 ![](https://camo.githubusercontent.com/07f5c9c42e1abd9367709435eb6327c83239eb5e19c40de904ab7ff7eb42c879/68747470733a2f2f67697465652e636f6d2f6e69616e736875323032322f706963747572652f7261772f6d61737465722f32303232313133313636373435303838303730382e706e67)

首先你确定你写文章时勾选了在主页显示吗

**Comment by ChdarkMoon** [comment]
@BNDong 
https://www.cnblogs.com/cndarkmoon
您好，我也遇到了刷新后空白的问题，并且按照您的方法调试，控制台成功输出“test”，请问为什么是空白呢？我使用的版本是2.1.4

**Comment by kksty** [comment]
> @BNDong https://www.cnblogs.com/cndarkmoon 您好，我也遇到了刷新后空白的问题，并且按照您的方法调试，控制台成功输出“test”，请问为什么是空白呢？我使用的版本是2.1.4

你解决了吗？我今天也遇到了

**Comment by BEATING-HEART** [comment]
#469 需要手动替换链接中的版本号

**Comment by Jandaes** [comment]
收到、谢谢！祝好
