### ISSUE TITLE
gitee挂了

### ISSUE THREAD

**Issue by AncientFairy** [BNDong/Cnblogs-Theme-SimpleMemory#87]
gitee挂了

**Comment by BNDong** [comment]
额！我测试了下，没问题啊？！！

**Comment by AncientFairy** [comment]
前端时间 gitee部分地区出现域名解析问题 还是希望您将那些图片迁移到gitHub吧 总感觉最近gitee老是出现问题

**Comment by BNDong** [comment]
我就是因为大家反应GitHub DNS 的问题，才将图片地址从 GitHub 迁移到 Gitee 的。😢我考虑下，图床不行迁移到博客园！

**Comment by AncientFairy** [comment]
OK
