### ISSUE TITLE
没有菜单。

### ISSUE THREAD

**Issue by pengyinghao** [BNDong/Cnblogs-Theme-SimpleMemory#88]
为啥我拷贝了css和js的基本设置 没有左侧的菜单呢 
预览地址:https://www.cnblogs.com/pengyinghao/p/12143732.html

**Comment by BNDong** [comment]
配置贴出来看看

**Comment by pengyinghao** [comment]
<script type="text/javascript">
    window.cnblogsConfig = {
        GhVersions    : 'v1.2.3', // 版本
        blogUser      : "peng", // 用户名
        blogAvatar    : "https://xxxx.png", // 用户头像
        blogStartDate : "2016-11-17", // 入园时间，年-月-日。入园时间查看方法：鼠标停留园龄时间上，会显示入园时间
    }
</script>
<script src="https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v1.2.3/src/script/simpleMemory.min.js"></script>

css版本是最新的

**Comment by pengyinghao** [comment]
> 配置贴出来看看
<script type =“ text / javascript”> window.cnblogsConfig = {GhVersions：'v1.2.3'，//版本blogUser：“ peng”，//用户名blogAvatar：“ https：//xxxx.png”，//用户头像blogStartDate：“ 2016-11-17”，//入园时间，年-月-日。入园时间查看方法：鼠标停留园龄时间上，会显示入园时间} </ script> <script src =“ https://cdn.jsdelivr.net/gh/BNDong/Cnblogs-Theme-SimpleMemory@v1.2.3/src/script/simpleMemory.min.js”> </ script>
css版本是最新的

**Comment by BNDong** [comment]
把你配置页截图发给我 dbnuo@foxmail.com
