### ISSUE TITLE
侧边栏目录无法滚动导致的问题

### ISSUE THREAD

**Issue by fatmanhappycode** [BNDong/Cnblogs-Theme-SimpleMemory#89]
以及感觉侧边栏目录最好可以独立滚动，而不是只能随着窗口滚动而滚动，
模板很好用，谢谢♪(･ω･)ﾉ

**Comment by fatmanhappycode** [comment]
像这里，我已经滚动到26了，可是侧边栏还是在22的位置
![image](https://user-images.githubusercontent.com/44257113/73810339-3049ac80-4811-11ea-91a0-87c61c3942ec.png)

**Comment by BNDong** [comment]
其实目录焦点已经过去了！这个主要是标题太多了，导致目录超出屏幕范围了。这个问题我考虑下，看看能不能通过限制最大高度，增加滚动，来解决！

**Comment by BNDong** [comment]
更新版本`v1.2.4`，已对此问题进行处理！
