### ISSUE TITLE
代码块滚动条在使用markdown编辑器时无法显示

### ISSUE THREAD

**Issue by Artoriaxx** [BNDong/Cnblogs-Theme-SimpleMemory#9]
如果使用tinymce编辑器插入代码，代码块的横向滚动条和复制代码功能都可以使用，但如果使用markdown插入代码，这两个功能都无法使用

**Comment by BNDong** [comment]
代码复制功能，是博客园自有的功能，我只是美化了一下，所以如果没有可能没办法。
关于滚动条的问题，后续我会更新解决！
