### ISSUE TITLE
目录和侧边栏异常

### ISSUE THREAD

**Issue by kjhuanhao** [BNDong/Cnblogs-Theme-SimpleMemory#94]
# 侧边栏
博客园开启的模块，标题显示异常，而自定义增加的就没有问题
![Snipaste_2020-02-21_19-25-59.png](https://i.loli.net/2020/02/21/jJZ4AuCi3BbKUdw.png)
# 目录无法显示
不知道为什么显示不了目录
![Snipaste_2020-02-21_19-28-15.png](https://i.loli.net/2020/02/21/1epihxu8G6PWNRn.png)
# 我的主题版本：v1.2.4
博客地址：https://www.cnblogs.com/huanhao/

**Comment by BNDong** [comment]
如果切换版本，样式错乱，更新下css。

版本说明里有 `更新基础 CSS 文件`  字样，说明该版本对基础 css 进行里调整，重新更新一下。

**Comment by kjhuanhao** [comment]
`我已更新CSS`，侧边栏的样式已解决，但是文章目录还是显示不出来

**Comment by BNDong** [comment]
我看着是正常的。如果屏幕分辨率过低(<=1360)，目录是不会显示的！只有一、二级标题才会生成目录；如果一篇文章只有二级标题没有一级标题也不会生成目录。

实现参考：https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/blob/master/src/script/marvin.nav2.js
