### ISSUE TITLE
markdown语法显示异常

### ISSUE THREAD

**Issue by JoeTang1** [BNDong/Cnblogs-Theme-SimpleMemory#95]
博客园的markdown  一个文章只能有一个代码块  不然就显示就雷同了  不知道什么情况
![image](https://user-images.githubusercontent.com/32047958/75089564-03c5bc80-5595-11ea-9e01-49d3dcd1a88a.png)

![image](https://user-images.githubusercontent.com/32047958/75089551-e42e9400-5594-11ea-9ceb-dfddbc24474f.png)

**Comment by BNDong** [comment]
我也用 markdown , 并没有出现这个问题，取消主题的使用看看会不会出现这个问题？

**Comment by Phoebe4869** [comment]
我也出现了代码块重复的问题，怎么解决

**Comment by BNDong** [comment]
该问题已修复。`v1.2.4` 版本使用博客园默认代码样式会出现此问题。

## 如何解决此问题

1. 加载本库代码：
    *  已做版本映射处理，无需做任何变动，自动更新加载代码版本！

2. 加载自己库代码(Fork)：
    * 拉取最新代码([bd48458](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/commit/bd48458a3f27c14300066ebb7bfc0c97c1197768))，更新自己的加载版本！

## 修复相关 commits

1. 问题修复 [2964028](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/commit/2964028d16404c351cbcbb86f206c6f58e852e07)
2. 版本映射 [bd48458](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/commit/bd48458a3f27c14300066ebb7bfc0c97c1197768)

**修复时间：2020/02/27 11:20**

**Comment by 20111521103** [comment]
请问这个博皮怎么部署呀？ 谢谢
