### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by kjhuanhao** [BNDong/Cnblogs-Theme-SimpleMemory#96]
# 建议优化一下首页文章间隔
首页的文章和文章之间间隔不是很明显，有些杂乱的感觉，建议给每篇文章加上一个”小外衣“
下面这个可以做个参考：
![Snipaste_2020-02-25_13-24-13.png](https://i.loli.net/2020/02/25/5iwaneUSD7YIWNr.png)
# 建议优化文章的【阅读全文】按钮
希望可以给阅读全文这个加上一个button之类的

**Comment by BNDong** [comment]
首先，感谢你的建议！

## 建议优化一下首页文章间隔
本人感觉文章之间的辨别已经很明显了。阴影和整体风格不搭，应该不会考虑！

## 建议优化文章的【阅读全文】按钮
我考虑一下，后期应该会优化这个问题。
