### ISSUE TITLE
关于在chrome的一点小bug

### ISSUE THREAD

**Issue by aether-rootr** [BNDong/Cnblogs-Theme-SimpleMemory#98]
在chrome中加载主页后，主页头图会遮挡一部分主页文章标题，如图
![image](https://user-images.githubusercontent.com/20625707/75541550-28200e00-5a59-11ea-90df-849516a94fcb.png)
博客地址：https://www.cnblogs.com/-aether/
但是在按F12后这个bug又消失了
![image](https://user-images.githubusercontent.com/20625707/75541661-44bc4600-5a59-11ea-9955-718ad9dc4427.png)
实测在新版edge没有出现这种bug。可能是chrome的锅。

**Comment by BNDong** [comment]
chrome 版本是多少？本人 chrome 测试无问题！

正常会出现遮挡的现象，但是会在短时间自动修正过来，不应该会一直出现遮挡！

由于 banner 区域高度不是固定的，会受屏幕分辨率、文章标题长度、文章分类和标签等因数自适应变化。所以我在一定的渲染节点都会对文章主体位置进行修正（[修正代码](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/blob/master/src/script/base.js#L359)）

**什么时候修正位置？**

1） 主页 banner 标语设置回调
2）主页 banner 渲染完成
3）屏幕大小变化
4）文章页 banner 渲染完成

**Comment by aether-rootr** [comment]
chrome版本是 80.0.3987.122（正式版本） （64 位）
请问短时间是指多久了，我开五分钟左右没有任何回调的迹象，我怀疑回调可能在打开开发者工具后才执行。另外我的屏幕是高分屏，是不是可能也有可能出bug的情况。（拿备用的本子试了下同一个版本的chrome，发现正常加载，估计是高分屏的锅）

**Comment by BNDong** [comment]
不会那么长时间，一般是 loding 后一秒左右就会修正！

我测试时没有出现问题
`chrome 80.0.3987.122（正式版本）（64 位）/  macOS Catalina 10.15.3 / 2880 x 1800`

手里没有4k屏，这个问题我注意下。复现不出问题，我也不好定位。

**Comment by aether-rootr** [comment]
我的本子是13寸的4k屏，可能受众比较小，定位比较变态？
