### ISSUE TITLE
1.2.4版本代码文章显示有问题

### ISSUE THREAD

**Issue by leo6033** [BNDong/Cnblogs-Theme-SimpleMemory#99]
刚刚从1.1.*切换到1.2.4，发现文章代码无法显示，切换到1.2.3之后代码显示正常

**Comment by leo6033** [comment]
另外，发现底部评论框的大小有点不对，comment_textarea 部分，自己做了下修改，width:850px;height:290px; 就正常了些

**Comment by BNDong** [comment]
# 关于样式问题
新版本发布都会确认基础样式，一般不会出现这种大的样式问题：

* 请提供复现示例、相关截图、文章使用的编辑器、使用的主题版本
* 如果可以请提供问题文章链接
* 如切换版本，请确认相关代码全部更新至切换版本（[详情参考文档](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory/blob/master/docs/v1.1/Docs/GettingStarted/versionSwitch.md)）

# 关于评论框
博客园今天更换了新的评论框，致使样式出现问题，这个和主题无关。不着急的朋友可以等我更新，着急的可以自行调整！

> 关于博客园官方调整页面结构，这个不是本人能控制的。如果影响主题样式，将会是所有版本的。出现此情况，只能保证最新版本样式没问题，历史版本已归档，不可更新，请大家知悉！
